### ISSUE TITLE
Feedback tabs are broken

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1000]
Come custom (read: bad, inaccessible) styles were used for the tabs on the feedback page, and those are now broken. The styles must have been removed at some point.

![CleanShot 2022-02-23 at 18 22 38@2x](https://user-images.githubusercontent.com/6351754/155426393-bea37dcb-cda6-4325-8316-66f772f0181b.png)

We should instead do something simple, like add two buttons that are jump links to each form. Maybe we could show them next to each other on desktop and stacked on mobile.

**Comment by AetherUnbound** [comment]
![The text "1000" in large gold letters](https://pm1.narvii.com/6461/c9181da91a111c5ccee94d1469f7cec612e8d22d_hq.jpg)

**Comment by krysal** [comment]
Related to #749.
