### ISSUE TITLE
Add loading indications when audio results are being loaded

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1001]
## Problem

We do not offer and feedback that audio is being loaded after the user clicks play or seeks an audio waveform. This makes the UI feel unresponsive.

## Description

We should add a loading animation.

IIRC @panchovm had a spinner in mind, potentially the new Gutenberg one from `@wordpress/components`. We'd have to port that from React to Vue.

We also need to research the a11y aspect of this and figure out the correct way to indicate this.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by panchovm** [comment]
Yes, you are right. In [this comment](https://github.com/WordPress/openverse-frontend/issues/632#issuecomment-1015858370) I showed the desired interaction. As far as I know, [this PR](https://github.com/WordPress/gutenberg/pull/37551) is the spin's last version.
