### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1003]
## Problem

https://sentry.io/share/issue/134c35673302427594fba07e60da4aa1/

## Description

Based on the stack trace it appears to be an issue with the translation banner

https://github.com/WordPress/openverse-frontend/blob/69e096f2cb3c7045a4a73fdd386961e43f10a975/src/components/VTranslationStatusBanner.vue#L14

Could be solved by adding a null check on bannerLocale, but would be nice to know why that's ever undefined.

## Additional context

Marking as `high` as it accounts for 10% of our total errors in production. This may have also already been solved in staging by @obulat's recent changes to how the banner works and just not been deployed yet.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
I checked again in Sentry, and this error _has_ been fixed  🎉

**Comment by zackkrida** [comment]
Fixed by @obulat's banner refactoring deployed in [v3.1.1](https://github.com/WordPress/openverse-frontend/releases/tag/v3.1.1)
