### ISSUE TITLE
Audio play buttons have double focus rings

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1005]
## Description

Audio play buttons in the non-box or full layouts have double focus rings:

https://search-staging.openverse.engineering/search/audio?q=dogs

<img width="559" alt="CleanShot 2022-02-25 at 11 18 55@2x" src="https://user-images.githubusercontent.com/6351754/155749904-7a5c1137-4ced-46b7-840b-5b2e191d2414.png">

**Comment by krysal** [comment]
What browser is this happening in? I don't see it in the latest versions of Firefox and Chrome

**Comment by zackkrida** [comment]
I see it in firefox (98.0b9 (64-bit)) _and_ chrome (Version 98.0.4758.109 (Official Build) (arm64)
):
![CleanShot 2022-02-25 at 15 29 16@2x](https://user-images.githubuserco
<img width="864" alt="CleanShot 2022-02-25 at 15 28 40@2x" src="https://user-images.githubusercontent.com/6351754/155797893-8a66a3ef-438c-475f-8612-9cf20141757e.png">
ntent.com/6351754/155797887-4ba8ee1b-d209-4d42-aae0-29674f5b1633.png)

**Comment by zackkrida** [comment]
@krysal you have to tab _to_ the button to see them, if you click on the button there is only one focus ring! Odd.

**Comment by krysal** [comment]
Now I see it, I confirm the issue is with tabbing, indeed odd!

**Comment by sarayourfriend** [comment]
Potentially a `focus:` vs `focus-visible:` issue. `focus` will activate when you click something _I think_ but `focus-visible` only activates when you focus into something via keyboard interaction.

The `VIconButton` implements the `focus:` styles over the `VButton` components already existing `focus-visible:` styles: https://github.com/WordPress/openverse-frontend/blob/cb1954ffaef56e256051347e429ae07ebbcc3e1e/src/components/VIconButton/VIconButton.vue#L5

Could be as simple as removing the additional focus styles from VIconButton
