### ISSUE TITLE
Providers links from Source page not working properly

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-frontend#1008]
## Description

The links from the **Source** column in the table of the Sources page return empty results in the search page. The issue here is that this is going to the general search (all media) which doesn't support the source filter and there is also no search term, this table was created when images were the only media available.

## Reproduction

1. Go to https://wordpress.org/openverse/sources or https://search-staging.openverse.engineering/sources and click in any source
2. See the empty search result page.

## Expectation

The links should lead to the image (or audio when added those sources to the table) search filtered by the clicked source, and therefore display a non-empty results page.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
> The links should lead to the image (or audio when added those sources to the table) search filtered by the clicked source, and therefore display a non-empty results page.

What should we do with providers like Wikimedia? :thinking:

**Comment by krysal** [comment]
Good question, probably have to add it twice. I guess we need an extra column in the table to indicate the media type of the providers.

**Comment by sarayourfriend** [comment]
The table data is based off the ContentProvider's API right?

https://github.com/WordPress/openverse-api/blob/a7955c86d43bff504e8d41454f68717d79dd3a44/api/catalog/api/models/models.py#L29-L32

It doesn't look like it allows for "mixed" provider types, would we just add Wikimedia there twice?
