### ISSUE TITLE
Empty audio search page shows audio track skeletons indefinitely

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-frontend#1009]
## Description

The skeletons give the feeling that something is charging but in reality, nothing will happen here.

## Reproduction

1. Go to https://search-staging.openverse.engineering/search/audio/ or try it locally
2. See error.

## Expectation

We need to define what will happen in these cases. If there is no search term but filters it should show the result(s) if any exists (this will allow exploring audio by sources or licenses for example) but if nothing is specified to search for what should happen? I see two options:
- Return the #602
- Return general results, as the API endpoint does https://api.openverse.engineering/v1/audio/. This was the behavior of the CC Search

## Additional context

The resolution here will affect #1008  

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
This specific bug is fixed, but is related to some larger inconsistencies that I've written up in #1073
