### ISSUE TITLE
Remove ClientOnly wrapper around the homepage search type switcher

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1014]
## Problem

The homepage search type switcher popover only renders client side currently.

## Description

There was some obscure error that prevented it from rendering server side (if I recall correctly) so we wrapped it in ClientOnly (originally there was some `onMounted` + `ref` logic that duplicated `ClientOnly`). We should figure out what is causing the error and remove the wrapper.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
Fixed in #1934.
