### ISSUE TITLE
Header does not fit on phones

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#1043]
## Description

The end-side of the header is cut off on smaller widths such as phones.

## Reproduction

1. Visit Openverse from a smaller width device.
2. See error.

## Expectation

The Search bar could possibly shrink to accommodate the content.

## Screenshots

![IMG_5935](https://user-images.githubusercontent.com/16580576/156537831-e04e084a-109d-43dd-af68-c25f701a35e1.PNG)

## Environment

 - Device: iPhone Xr 
 - OS: iOS 15.3 
 - Browser: Safari 
 - Version: 15.3 
 - Other info: viewport width = 414px 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
Is this new? Which version of the front-end is this?
Just for context, when I open the currently deployed site at `wordpress.org/openverse` in Firefox or Chrome on my Android phone, I don't have a problem with the header not fitting.

**Comment by zackkrida** [comment]
@obulat I believe it referrers to the header after scrolling on the search results (which only seems to change on ssr-rendered pages, interesting bug). I'm able to view this on android chrome + ff.

**Comment by dhruvkb** [comment]
The iPhone I used has just `414px` of width so that might be one of the reasons for the header getting cropped.

**Comment by sarayourfriend** [comment]
Is this and #845 related?
