### ISSUE TITLE
Replace individual `lodash.*` packages with `lodash` or remove entirely

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#1054]
## Problem

[Individually packaged lodash functions](https://lodash.com/per-method-packages) are deprecated and their usage is discouraged. They also don't work well with TypeScript as individual `@types/` packages need to be added for all of them.

## Description

The use these functions should be replaced with `lodash` or `lodash-es`.

## Alternatives

The deprecation notice provides some viable alternatives. A significant alternative is to remove lodash altogether and write some of the functions ourselves or use smaller third-party libraries with a more specific focus.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
A few reasons to remove `lodash`:

0. Lodash is huge for what it is, minified it's 73.3kb. I wouldn't want to encourage using more of it.
1. It doesn't tree shake well. Even if you use the `lodash/whatever` access the lodash library functions are all implemented in other lodash library functions so you end up still pulling in a large amount of the lodash library anyway.
2. It has unusual semantics like list-first parameter order and swallows null/undefined in ways that encourage unsafe modern JavaScript. It has the _appearance_ of something like a functional programming library but doesn't follow any conventional FP semantics (like list-last parameters or type safety).
3. It encourages reaching for a library when built-in native Array and Object functions would work just as well (and be much faster thanks to heavy engine optimization).
4. The functions it exports that _don't_ have direct native replacements are typically less-efficient and focused than one-off libraries. For example, `memize` is better at memoization than `lodash.memoize`.

**Comment by dhruvkb** [comment]
@sarayourfriend based on your points could you make a task-list of issues to remove Lodash usages one-by-one? That seems like a good way to create lots of small `good first issues`.

**Comment by sarayourfriend** [comment]
Sure thing!

**Comment by sarayourfriend** [comment]
Done! https://github.com/WordPress/openverse-frontend/milestone/14

**Comment by dhruvkb** [comment]
Let's close this issue then?
