### ISSUE TITLE
Faulty logic for audio count on the all results view

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1056]
## Description

On the all results view, the audio count is set to 0 once all audio items have been returned from the API. This number should remain correct.

## Reproduction

1. Make a search that produces image and audio results, like https://wordpress.org/openverse/search/?q=dolphin
2. Observe the '1 result' for audio in the content switcher button
3. Click the load more button at the bottom of the page
4. Scroll up and observe the '0 results' for audio in the content switcher button.

## Expectation

This should always display the correct count.

**Comment by YashxAnand** [comment]
Hi @zackkrida , I would like to work on this issue.

**Comment by zackkrida** [comment]
Hi @YashxAnand, that sounds great! If you need any help feel free to comment here. This issue gets into some interesting state management and data fetching issues.
