### ISSUE TITLE
Remove dead iframe height code

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1059]
## Problem

Openverse is now using a hardcoded height for the iframe. We can remove any iframe code related to sending the height of the window to the parent site.

To my knowledge that is this file:

https://github.com/WordPress/openverse-frontend/blob/912f1c4a9715619120287cd45ac1ea791b9c529e/src/mixins/iframe-height.js#L4

And anywhere it is implemented.

**Comment by BarokDG** [comment]
I'm working on this
