### ISSUE TITLE
Search endpoint access without a query

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1073]
The search endpoints currently have some inconsistient behavior and we need to decide from a design and product perspective how to handle them. I'll identify some issues here. We're using https://search-staging.openverse.engineering/ as our source of truth.

1. The search bar blocks access to the endpoints when they don't have a search query, which is good. however if you visit the urls directly, for [example](https://search-staging.openverse.engineering/search), the site shows the `no results for "".` message. That doesn't seem accurate because the user didn't supply a search term at all.
2. When using the content switcher on the [search](https://search-staging.openverse.engineering/search) page, a blank `?q=` parameter is set. This means that the raw results from elasticsearch are shown. Go to the search endopoint with no query and use the content switcher to observe this.
3. Clicking a source name on the sources page creates these types of urls: `https://search-staging.openverse.engineering/search/?source=animaldiversity`. These currently do not work. The question is:
    - Should they?
    - If they do, how do we reconcile that against points 1 and 2?

We need to figure out what _functionality_ we want to offer users here, and then how to best implement it. I'd love to hear from @panchovm on this from a user experience design perspective, but other people are welcome to discuss.

**Comment by panchovm** [comment]
When you say _"visit the urls directly"_ you are indicating a key aspect in the searching journey that argues my following response.

I would redirect the three cases to the homepage. The current flow does not have a suggested results page as competitors tend to have for boosting the browsing experience. Therefore, I do not envision many use cases where visitors open the url directly searching for relevant content.

However, I do think there is room to improve the experience in the mid-term future; once we have collections or curated content based on a visible criterion.

**Comment by zackkrida** [comment]
> Clicking a source name on the sources page

@panchovm What you wrote sounds okay to me; do you think we should just remove these links then?

**Comment by panchovm** [comment]
I don't have a proper response on how to do it, but as long as the solution redirects to the homepage, that is perfect.

**Comment by zackkrida** [comment]
@panchovm I think keeping these links but pointing them to redirect to the homepage would be a confusing user experience, so I'll mention that they should be removed in the issue for fixing this. Thanks!

![CleanShot 2022-03-10 at 16 27 16@2x](https://user-images.githubusercontent.com/6351754/157757781-87dc0df3-d985-48c8-bcf0-1a106ab0127d.png)

**Comment by panchovm** [comment]
I understood something completely different for point 3.

> Clicking a source name on the sources page

And you are right. Redirecting to the homepage is very confusing. In that case, I suggest removing the filtering link while keeping the domain one. Sorry for the confusion.

**Comment by zackkrida** [comment]
Closing, as these links have been removed and there's another issue to track the redirection problem: #596
