### ISSUE TITLE
Empty waveform peaks data renders an empty waveform; should render placeholder instead.

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1074]
## Description

The API returns an empty array when the waveform peaks have not been generated. The frontend currently assumes that _any_ array returned will include waveform data. However, the frontend should also check the length of the array and use the placeholder if the peaks array is empty.

Alternatively we could update the API to return `null` for the `peaks` when they haven't been generated yet.

Marked as critical because we can't deploy without this fix or we'll have empty waveforms for most audio.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
A good place to fix this would be in the `decodeMediaData` util that handles the conversion of API responses into media types that the frontend uses. We already wrangle the `title`, `creator` and `tags` fields there so extending it to `peaks` would not be too much of a leap.

**Comment by dhruvkb** [comment]
On further thought, `VWaveform` can be extended to handle the `peaks` prop being `[]`.
