### ISSUE TITLE
Audio track current time sometimes being set to non-real number

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1076]
## Description

https://sentry.io/share/issue/96afadf57a7e40acbd0fdb52a7d7d9c2/

I think this is being caused by a discrete math order of operations bug on this line: https://github.com/WordPress/openverse-frontend/blob/29bf0a0075548014a3d1280f0b56ae1f7e5f0b77/src/components/VAudioTrack/VAudioTrack.vue#L299

```
> const audioDuration = { value: null }
undefined
> const props = { audio: null }
undefined
> audioDuration.value ?? props.audio?.duration / 1e3 ?? 0
NaN
```

As you can see, if `props.audio` is null, it is still dividing `null / 1000` which is NaN. NaN isn't affected by `??` either so it doesn't default to 0.

It'd probably be best to just split this expression into multiple lines rather than keeping it a one-liner.

Also needs to be fixed in `VGlobalAudioTrack` as well.

## Reproduction
I'm not sure how to actually reproduce this

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Perhaps best tested by explicitly replacing `props.audio.duration` with `null` locally.
