### ISSUE TITLE
`audio.tags` sometimes undefined causing error when reading `filter` property

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1085]
## Description

https://sentry.io/share/issue/e8dd757830264145b5a871ae13863745/

The sentry stacktrace isn't useful, but if you open the specific bundle file that the error happened in and go to the column indicated (22007) it corresponds exactly to a call to `audio.tags.filter` on this line:

https://github.com/WordPress/openverse-frontend/blob/e8cab9fa310002f175f50705551e6c020a3a91d0/src/components/VAudioDetails/VAudioDetails.vue#L14

## Reproduction

No idea how to reproduce.

## Expectation

We should safely handle undefined here or (better) make sure it can never be undefined. Something is probably wrong with the `decodeMediaData` function, but I'm not sure what as the logic for transforming the `tags` property is quite simple.

## Additional context

Marking as low as the number of effected users is currently very low. We can escalate if that changes.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
Closing this issue because it wasn't reported in the last 2 months, and is most likely solved. If we ever see this again, we can reopen.
