### ISSUE TITLE
Create `VContentPage` component

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1090]
## Problem

When building text-heavy content pages, it's difficult to make sure the styles are correct on every page. To fix this, we could build a set of typography primitives: `<Heading level="1">` type components, and so on. Until we get to that stage, which would require a solid amount of work, it would be easier to create a `VContentPage` component that wraps raw html tags and applies styles to them using https://tailwindcss.com/docs/typography-plugin

This will allow us to make copy edits without also having to write many complex styles, and allow our content pages to be consistent by default. Then, if and when we make standalone small typography components, we can 'turn off' features of the tailwind plugin and switch to those incrementally.

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
I think Tailwind's `components` layer would be very useful to define primitives that thinly wrap basic HTML tags and only define styles. 

For example a `.heading` Tailwind component is ultra low maintenance compared to a Vue component when the only requirement is stylistic and there isn't much `<script>` functionality.
