### ISSUE TITLE
Replace `lodash.debounce` and `lodash.throttle` with `throttle-debounce`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1104]
## Problem

We are looking to remove dependency on lodash altogether (see milestone description).

## Description

Replace all usages of `lodash.debounce` and `lodash.throttle` with [`throttle-debounce`](https://github.com/niksy/throttle-debounce). It is a small implementation of both functions. Whereas lodash implements throttle as a variant of `debounce`, `throttle-debounce` does it in reverse and with about half the number of extraneous utilities pulled in.

Note: The parameter order for these functions is admittedly weird, but the implementations are sound and very small compared to available alternatives.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by harshi1122** [comment]
Hello @sarayourfriend 
I am new to open source and would like to work on this issue.
> * [x]  🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
@harshi1122 You got it! I've assigned the issue to you. Feel free to ping if you need any assistance :rocket:

**Comment by harshi1122** [comment]
Hello
I am kind of having trouble getting internet to work on the issue at the
moment
I will try to work on the issue soon.
Sorry
