### ISSUE TITLE
Wrong font size on image details page and has horizontal scrolling on mobile

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-frontend#1111]
In our effort to remove legacy styles, some changes affected parts of the image details page.

## Reproduction

1. Run the project and go to the image details page of any image
2. Observe the font size of the license descriptions, it should be the `sm` size of our tailwind config (`13px`) on mobile and `base` (14px) on desktop.
3. Notice that it presents a horizontal scrolling

## Expectation

The page should match the Figma mockups [[mobile](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=958%3A19663), [desktop](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=1228%3A21557)] and shouldn't have horizontal scrolling.

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Thanks for finding this!
