### ISSUE TITLE
Add Thingiverse and Sketchfab as `model_3d` meta search items

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1119]
## Problem

We don't have any 3d model meta search sources defined yet. We should add Thingiverse and Sketchfab, since these are our existing 3D sources but we have very few items from them. These sources will appear once #739 is completed.

## Description

Sketchfab and Thingiverse need to be added to the legacy source lookup. The key for these items should be `model_3d`:

https://github.com/WordPress/openverse-frontend/blob/f18e90a92e834cd650fbcf1f535df57918b17a0d/src/utils/get-legacy-source-url.js#L7

- SketchFab URL (license filters seem to be long unique identifiers `https://sketchfab.com/search?features=downloadable&licenses=322a749bcfa841b29dff1e8a1bb74b0b&licenses=7c23a1ba438d4306920229c12afcb5f9&licenses=34b725081a6a4184957efaec2cb84ed3&licenses=2628dbe5140a4e9592126c8df566c0b7&licenses=bbfe3f7dbcdd4122b966b85b9786a989&licenses=72360ff1740d419791934298b8b6d270&licenses=b9ddc40b93e34cdca1fc152f39b9f375&q=dogs&type=models`
- Thingiverse URL `https://www.thingiverse.com/search?q=dog&type=things&sort=relevant` filtering by license doesn't currently appear to work, but the vast majority of items use CC licenses

**Comment by dhruvkb** [comment]
This was blocked by some Pinia migration PRs, will pick this up again now.
