### ISSUE TITLE
Style update of translation and news banners

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#1123]
## Problem
As noticed in a #904's [comment](https://github.com/WordPress/openverse-frontend/pull/904#pullrequestreview-887570089) by @zackkrida, the translation and News banners have styles that look clunky and broken on mobile. The yellow background of News banner makes the page feel cut by the translation one. 

## Description

|Desktop|Mobile|
|:---|:---|
|![image](https://user-images.githubusercontent.com/895819/158445042-4a73496d-18fc-453f-b8a6-dd00e71b2563.png)|![image](https://user-images.githubusercontent.com/895819/158445074-fb7c9940-3235-463a-9b7f-51941827e48f.png)|

The proposal above has the following changes:
* Background change of News banner, from brand yellow to `Blue 1` (#3E58E1) from [News redesign](https://wordpress.org/news/).
* New close action on the far-right area on both banners.
* Both banners have `16px 24px` for paddings on both desktop and mobile.
* On desktop, texts are `label regular`.
* On mobile, the close action is center aligned and texts are `caption regular`.

Regarding banners behavior, I think both elements should show over the page instead of pushing downward the homepage main content. In that way, closing the banners do not move the page upwards.

**Comment by sarayourfriend** [comment]
> Regarding banners behavior, I think both elements should show over the page instead of pushing downward the homepage main content. In that way, closing the banners do not move the page upwards.

How would this work on the search pages? The banners would cover the header...

**Comment by panchovm** [comment]
Yes, I was referring only to the homepage. 

For all internal pages, related or not to the searching experience, I remember a PR by @obulat where the translation banner does push the content downwards, not overlapping any content. That solution worked perfectly.

However, I think the News banner should be only in the homepage.

**Comment by sarayourfriend** [comment]
Okay, thanks for the clarification @panchovm!
