### ISSUE TITLE
Europeana and SoundCloud don't support search filters

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#1128]
## Description

The meta search URL for Europeana (audio and video) and SoundCloud (audio) do not update based on the commercial/modify filters.

## Reproduction

1. Search for a strange string.
2. See the URL for Europeana and SoundCloud.
3. Toggle the commercial/modify fiiters.
4. Observe no change to the URLs.

## Expectation

The code for the URLs to change exists (but it has a bug). So by fixing it, we should have the URLs updating based on the filters.

## Additional context

The code references `search.filters` which is always undefined as there is no `filters` field on the `search` object.

Europeana audio:
https://github.com/WordPress/openverse-frontend/blob/bccbd1333fd0deb51fdd90a391d65e4666caf554/src/utils/get-legacy-source-url.js#L44

Europeana video:
https://github.com/WordPress/openverse-frontend/blob/bccbd1333fd0deb51fdd90a391d65e4666caf554/src/utils/get-legacy-source-url.js#L61

SoundCloud audio:
https://github.com/WordPress/openverse-frontend/blob/bccbd1333fd0deb51fdd90a391d65e4666caf554/src/utils/get-legacy-source-url.js#L133

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
#1040 touches this code, I will check if there is this error there, too.
Why is this critical?

**Comment by dhruvkb** [comment]
I marked this critical because it's a production bug that might lead people to the wrong results. We can surely downgrade the severity if that's too high.

**Comment by obulat** [comment]
I am undecided on whether I should add it to #1040 or not :) I have fixed this issue in [this commit](https://github.com/WordPress/openverse-frontend/pull/1040/commits/ef35db3e34789e754d4a26217704f1a57f0e6dc8). Since the underlying state changes so much in #1040, it doesn't make sense fixing it before #1040 is merged. I wonder if it's a good idea to extract this change from #1040 to simplify PR review, though, and leave #1040 with this bug :)

**Comment by dhruvkb** [comment]
It's not a very drastic change and doesn't make the review much harder than it already is, so I'd say we can fix it with #1040 itself. Thanks!

**Comment by obulat** [comment]
I reverted the changes that I've added to #1040, but it still seems to work there ☺️
