### ISSUE TITLE
Add Audio providers to the Sources page

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1155]
## Problem

On the 'Sources' page we have a table with providers, links to them and the number of items they provide. Currently, it's a single table with only image providers.

## Description

The Sources page needs to be updated to allow for adding other media types. Currently, we should add the Audio providers.

At the same time, we should make the page flexible so that in the future we can add Videos/ 3d models / books. We could either _add a media type column_, and list all the sources in the existing single table, or we could _use several tables_ for all the supported media types.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
Should we have separate tabs on that page for different media types?

**Comment by sarayourfriend** [comment]
If we do tabs then it is blocked by #749.

I like the tabs idea, just wanted to document the blocker for anyone looking at this eager to work on it :+1:
