### ISSUE TITLE
Unsafe `route` access in `VGlobalAudioTrack`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1157]
## Description

https://sentry.io/share/issue/5746823abe77499b86dbdb8fe6330e1b/

## Reproduction

No idea how to reproduce.

This should be fixable with some null checks. Can be done in tandem with #1156 in a fully audit of unsafe route access in the app.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
Fixed in #1335.
