### ISSUE TITLE
Mini RFC: Switch all linting warnings to errors

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1160]
## Problem

Currently we have several ESLint plugins that only set checks to warnings instead of errors.

Warnings can be easily ignored while coding, but they show up on _every_ PR if the warning gets merged.

What's the use case for an ESLint warning? If something is intentionally going against the ESLint rules, shouldn't we have to _force_ the use of `eslint-disable` for the rule for the CI to pass? Otherwise the warnings are just pointless noise.

Particularly worrisome ones are for example the warning not to use `@ts-ignore` because it modifies compilation. `@ts-ignore` is a powerful tool that is useful for specific situations, but should be avoided whenever possible. If it's used, then an explanation for why would be appropriate.

## Description

Should we switch all ESLint rules that are currently warnings to errors, therefore requiring the use of `eslint-disable`?

cc @WordPress/openverse-developers 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
I like the idea of not introducing any additional warnings in the PRs. The warnings might seem tiny in one PR, but when we let them build up, they really degrade the experience of looking through the logs.

One issue with the approach you suggest, @sarayourfriend , is that there were a couple of `ESLint` warnings that I couldn't remove:
- two components in one file in a test file (two wrapper components)
- unknown component in a test file: I don't know how to ensure that Vue sees a component inside a test wrapper component as registered.
_I remember a couple of times when I didn't know how to disable warnings with `eslint-disable`, it didn't work for some reason, and the warnings still appeared._

Considering that both my examples are from test files, maybe we should switch warnings to errors in the `src/` directory, and leave them in tests?

**Comment by sarayourfriend** [comment]
It looks like you _were_ able to disable the two-components in one file warning: https://github.com/WordPress/openverse-frontend/blob/e8cab9fa310002f175f50705551e6c020a3a91d0/test/unit/specs/components/v-link.spec.js#L12

Is there somewhere else it was an issue?

I'm not sure about the unknown component in a test file one, I'm not able to reproduce that one. If we can reproduce it we can debug why it's not able to be disabled.

But you bring up a good point, some errors don't make sense in test scenarios. For the multiple components in a single file (common when writing test wrappers) we could just disable that rule for the `test` directory using the [`test/unit/eslintrc.js`](https://github.com/WordPress/openverse-frontend/blob/e8cab9fa310002f175f50705551e6c020a3a91d0/test/unit/.eslintrc.js#L5).

**Comment by sarayourfriend** [comment]
@WordPress/openverse-frontend Are we fine implementing this? We've got yet another batch of ESLint warnings polluting every PR now (raw text in test components, which is not a valid warning). If they'd been errors (as that one in particular should be for the actual application code) then we would have caught the regression in how ESLint rules are applied to different parts of the codebase before committing it to main and adding a long list of noise (that you still have to pick through to make sure there isn't anything actually valid in them) to every single PR.

**Comment by zackkrida** [comment]
@WordPress/openverse-frontend please 👍 / 👎 your support for this in @sarayourfriend's comment and offer additional feedback if you don't want to move forward.

**Comment by krysal** [comment]
I very much support this, really don't like to have warnings polluting the terminal or the GitHub UI, and I think both problems @obulat mentioned have been fixed in PR #1221, tests were passing when Olga approved it but broke when merging with `main`. I'll check what happened there. It just needs another approval.

I also sent another to get rid of warning annotations on test files, please check it out #1252.
