### ISSUE TITLE
Create a `~/types` directory to store shared types and move types out of `~/models` into the new directory

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1161]
## Problem

We've been putting most of the shared types for the app into the `~/stores/types.ts` module. This module is getting long and complicated. It'd be nice to split it into smaller modules and place them in a top-level `~/types` directory.

## Description

Split `~/stores/types.ts` into several smaller modules placed in a new `~/types` directory. Additionally export types from an `~/types/index.ts` so that it's easy to import types from a single import instead of having to reach for the specific module.

As @dhruvkb pointed out there is an already existing `~/models` directory. The types from there should be moved into `~/types` and merged with the other types.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
@sarayourfriend some of my PRs have used the `models/` directory to put shared interfaces (sorry if that's anti-conventional, I was coming at this from a Django-PoV). Should we update the issue to go ahead with `models/` or move the existing code to `types/`?
