### ISSUE TITLE
`e2e/filters.spec.ts › filters are updated when media type changes` is flaky

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1162]
## Description

The `e2e/filters.spec.ts:132:1 › filters are updated when media type changes` test is flaky.

See this failed run: https://github.com/WordPress/openverse-frontend/runs/5643116770
Followed by this successful run after retrying the job: https://github.com/WordPress/openverse-frontend/runs/5643403081

Artifacts for the failed run can be downloaded here for the next 30 days: https://github.com/WordPress/openverse-frontend/suites/5752319247/artifacts/191051070

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
This issue might happen because some tapes are missing. Several PRs recently were having this issue, and adding tapes seems to have fixed it.

**Comment by sarayourfriend** [comment]
Great! I haven't noticed this one in particular failing recently.

Let's close this one for now and open a new one if we notice it failing again?

On another note, I was wondering if there was some way in CI to force the e2e tests to fail if a tape returns 404 :thinking:

**Comment by obulat** [comment]
> On another note, I was wondering if there was some way in CI to force the e2e tests to fail if a tape returns 404

If we decide to do this and find a way to fail the tests, we should exclude the `thumb` tapes from this.
