### ISSUE TITLE
Audio category filter not working correctly

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-frontend#1169]
## Reproduction

1. Make an audio search, e.g.: https://wordpress.org/openverse/search/audio?q=coffee&categories=music
2. Observe there is a mix of audio categories in the results, in the case of the previous links: Music and Sound effects
3. Select a category, e.g.: **Music** and observe the empty results page appears
4. Deselect Music and try the **Sound effects** category, observe that results are still mixed with **Music** tracks.

## Expectation

Filters should reduce the number of results to the ones falling under the selected category.

## Environment

This happens in both, the production and the staging environment.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Oh no! thanks for discovering this.
