### ISSUE TITLE
Add links out to about/our story/privacy/etc from the home page

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1174]
## Problem

Currently when you land on the home page there is no way to learn about Openverse, our privacy policy, or anything else. In fact, the only information link takes you away from Openverse (to CC).

## Description

Add a header menu to the homepage (or something) that links to our various informational pages.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by kb-0311** [comment]
Do you mean some additional line which provides a hyper link to our story / privacy/ etc  just like how this link was added here ?

https://github.com/WordPress/openverse-frontend/blob/07e67525f4e72cb69b28b6f4a6e349e643e63789/src/pages/index.vue#L73

**Comment by sarayourfriend** [comment]
This issue definitely needs design input, the homepage requires a lot of care before making design changes to it.

We'll also need to work on how this will work with the iframe removal project on the horizon.

**Comment by zackkrida** [comment]
CC @panchovm

**Comment by panchovm** [comment]
Thanks for bringing this up. And as @zackkrida said, there is a lot of improvement and room for redesigning the main content and being more explicit on project-related content.

I will assign it to myself and start working on this once we have an iframe removal deadline.

**Comment by panchovm** [comment]
Removing the `needs design` issue as this is addressed in #1433

**Comment by obulat** [comment]
I am going to close this issue in favor of #1433. We can create more development-focused issues related to it later.
