### ISSUE TITLE
Change variant name from `plain-dangerous`

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#1181]
## Description
The word dangerous in the `plain-dangerous` variant of `VButton` gives the idea that the button would be used for destructive actions and not that its use is discouraged.

See an example of the confusion here: https://github.com/WordPress/openverse-frontend/pull/1142#discussion_r834307513

## Goal

The intent of developers not using this variant can be conveyed more clearly by using synonyms for "danger" e.g. "beware" and "careful" and my favourite "avoid". I recommend renaming the variant to "plain--avoid". The "--avoid" suffix can add that little bit of friction to discourage it's usage while not confusing with the "danger" convention we use for destructive actions.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by shreyanshmalvya** [comment]
Hey, I just went over to the discussion. It would be better to update the variant to ```variant= "plain--avoid" ```. Can I take up the issue?

**Comment by dhruvkb** [comment]
Sure @shreyanshmalvya! I'll assign it to you.
