### ISSUE TITLE
Rename `get-legacy-source-url` to `get-additional-sources`

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1194]
## Problem

The term 'legacy source url' is unhelpful and is more easily understood as 'get additional sources'. We should update all references to this utility along with the file itself.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by aiethics95** [comment]
Hi, I'd like to take a look at this (:

**Comment by dhruvkb** [comment]
@aiethics95 I've been working on this in conjunction with #1119. Might I suggest peeking at [other open issues](https://github.com/WordPress/openverse-frontend/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)?
