### ISSUE TITLE
Create a simple boolean feature flag/guard for showAdditionalSources

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1195]
## Problem

We would like to show 'additional sources' in the content switcher, but there's a few pieces of discrete work needed to complete this milestone. We should put the entire feature behind a flag so we can work on it piecemeal without blocking our deploys. 

## Description

Because our feature flagging infrastructure and RFC aren't completed yet, I propose we add a simple boolean `showAdditionalSources` flag to our config file that is true in development and false in production. Behind this we can build our the necessary features to list additional sources, add pages for them, and connect those pages to meta search. 

## Alternatives

We could do nothing and block deploys, or simply use `isDev` as a guard against this work.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
@WordPress/openverse-frontend can I get some opinions here? I think the suggestion here _or_ it's alternative could work fine.

**Comment by obulat** [comment]
Can we close this issue now that we have the feature flags implemented, @zackkrida ? Or should it stay open to track the actual addition of additional sources flag?

**Comment by sarayourfriend** [comment]
This was already implemented using `isDev`. We should update it in a future PR working on these things to use a feature flag. Closing this issue as completed though.
