### ISSUE TITLE
Incorrect styles on reporting form close button

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1206]
## Description

The content reporting form shows the incorrect button styles, with a pink background that should not be present.

## Reproduction

1. Submit a mature content report.
2. Observe the incorrect button styles

## Screenshots

<img width="365" alt="CleanShot 2022-03-30 at 09 39 53@2x" src="https://user-images.githubusercontent.com/6351754/160848183-e038d810-4d5e-442b-af42-5e577178539c.png">

**Comment by HILAYTRIVEDI** [comment]
I can't able to reproduce this issue.

https://www.awesomescreenshot.com/image/24991137?key=531cf1e9486250863294ffb82672770b

**Comment by zackkrida** [comment]
@HILAYTRIVEDI this change is not live in production yet, but can be seen in [staging](https://search-staging.openverse.engineering) and locally.
