### ISSUE TITLE
Stop fetching the media twice

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1225]
## Description

If you search for 'All Content' from the homepage, you can see that instead of 2 API calls (one for images and one for audio), the API is called 4 times: twice for each media type. This is caused by calling `fetchMedia` both from the `index.vue` page and from the `search.vue`'s `fetch` function.

In addition to this particular case, we should also audit all the calls for `fetchMedia` and make sure that there are no repeated calls.

## Reproduction

1. Open the homepage, and search for something selecting 'All Content' using the search type switch.
2. Look at the requests in the console.
3. There will be 4 requests:

<img width="585" alt="Screen Shot 2022-04-03 at 4 50 03 PM" src="https://user-images.githubusercontent.com/15233243/161431209-040839d0-b2fa-4ad1-babf-480ac8616795.png">

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
@obulat it might be nice to add a locking mechanism on the image fetch requests, like some way of checking the currently running requests for the media so that if the request would be for the same parameters then it is just skipped. This could go hand in hand with the improvements in #1132
