### ISSUE TITLE
Attribution HTML sample causes horizontal scroll on small viewport widths

### ISSUE THREAD

**Issue by umeshggupta** [WordPress/openverse-frontend#1229]
## Description
Credit the creator section HTML content Cutting Off in small viewport size and Horizontal scroll bar is coming .

## Reproduction
1. Visit this following Link: https://wordpress.org/openverse/image/517bc087-ee91-4e50-9cf2-1f5220beb35f/
2. Change the screen viewport to the mobile devices.
3. You will notice that the credit the creator HTML content Cutting Off.

## Screenshots
https://prnt.sc/whlhofEEHWY8

## Environment
 - Device: iPhone 12 Pro, Pixel 5, iPhone SE, iPhone XR
 - Browser: Chrome

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
The addition of tabs fixed this issue in main(not deployed to production yet). You can see at https://search-staging.openverse.engineering/image/517bc087-ee91-4e50-9cf2-1f5220beb35f/
