### ISSUE TITLE
Correctly hydrating the server state in Pinia setup stores

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1254]
## Problem

We are almost done converting Vuex stores to Pinia ([milestone](https://github.com/WordPress/openverse-frontend/milestone/5)). However, we are incorrectly re-initializing the store on the client side instead of reusing the server-side state, and this is causing a lot of errors. 

## Description

All of the stores are now converted to Pinia setup stores.

Final conversion surfaced a very important flaw in this conversion process. During the state hydration on the client, the Pinia store setup function is ran again as is. This means that instead of reusing the state passed from the server, we are re-creating the state with initial values. This causes numerous errors in the app logic.
For example, when you click on 'Load more' button on a server-rendered search page, the media fetch state page value is set to undefined, so we are re-fetching the same page that has already been fetched. Other bugs such as the audio search page with fewer than 20 results being unresponsive, and no change when you select an extension filter and decelect it, are also caused by the incorrect state on the client.

The solution I propose (and try out in the Provider store PR) is to add a custom function for initializing the state by setting it to the initial value on the server, and adding our own hydration solution on the client. Nuxt context is not injected inside the setup store setup function. However, it is available as part of the `$nuxt` property of the global `window` object.
```
const initialState = { searchType: ALL_MEDIA }

const initializeState = () => {
    // add `isClient` checks to make sure window is not undefined 
    const serverState = window.$nuxt.context.pinia.state.search
    if (serverState) {
        // Making sure that the state is a simple object, not a proxy or a ref.
        return JSON.parse(JSON.stringify(serverState))
    } else {
        return initialState
    }
}

const searchStore = defineStore('search', () => {
    const state = reactive(initializeState())

    return { state }
})
```

This can only work if we can serialize and deserialize the state correctly. Here, the problem in the `media` store is with the current implementation of the `fetchState`, which is a composable that returns both simple properties, but also functions to change the `fetchState`. The functions cannot be stringified, and need to be filtered out when hydrating the state. We also cannot use a computed that would only return the inner simple `FetchState` object from this computed because Pinia treats computed refs as getters, and it only passes the state (i.e. the `ref`s and `reactive`s) from the server to client as part of the `window.$nuxt.context` value.
Instead, we can create the `_fetchState` as an inner composable that would handle state updates, and a fetchState `ref` that would be updated by a `_fetchState` watcher, and would be serialized by the server, and deserialized by the client to initialize client state correctly.

This conversion will be easier if the current large media store is split into separate stores: audio, image, allMedia, and singleMedia (for the image/audio detail pages), but that would make for a huge PR that would be difficult to review :(

## Alternatives

Another to go back and refactor the stores to use options API. The options store uses a separate function for creating the store, and because of that does correctly handle hydration on the client side. It calls the `state` function on the server, but hydrates the server state values and makes them reactive on the client. There is even a special `hydrate` option that is only available for the options stores.
With this solution, we won't have to _"fight the tool"_, and will be using the options it provides instead.

## Additional context

The solution for store hydration is implemented in the Provider store PR: #1158.
I have also opened a [discussion in the Pinia repository](https://github.com/vuejs/pinia/discussions/1213) about the composition store state hydration, but it's still unanswered.

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
> Another to go back and refactor the stores to use options API. The options store uses a separate function for creating the store, and because of that does correctly handle hydration on the client side. It calls the state function on the server, but hydrates the server state values and makes them reactive on the client. There is even a special hydrate option that is only available for the options stores.
> With this solution, we won't have to "fight the tool", and will be using the options it provides instead.

I am personally very tempted by this solution, even though it means we'd have to do some significant refactoring and go back on our original decision.

Unfortunately the more we "fight the tool", as you said, the further we get away from the "standard/expected implementation" which, as we know, can be quite problematic with the Nuxt situation.

If other folks are strongly opposed to switching the store style (it makes me sad to think about but I really do think it would be the better option) then I like your approach with the `initializeState` function. It could be abstracted pretty easily as well if we just pass the store key and initial state as arguments to a generic `initializeState` function.

My concern, however, is that we'd still run into issues whenever we've defined individual state values as `ref`s, instead of a single reactive state object.

On the other hand, it seems like the `initializeState` function could be implemented upstream as a helper. Like `initializeSsrState` or something in an additional ssr specific package. Did you happen to open a discussion or issue in Pinia about this by any chance?

**Comment by obulat** [comment]
I think there could be an abstraction that would initialize the state both when created using individual `state` reactive, and separate `ref`s. The state object that we can get from `window.$nuxt` contains all of the data as an object, so we could simply iterate the keys/values, and create the state based on that. It would be better to standardize the state creation to use either single state OR a set of refs (I'd prefer state) should we select this approach.

Even though I feel really proud of myself for creating the `initializeState` solution, I do agree that using `standard/expected` implementation can save us a lot of headache in the future, and be much more maintainable.

**Comment by obulat** [comment]
I am going to go ahead and create issues to convert the stores. `active-media` store can stay a `setup` store because it does not use server state on the client.
- [ ] `nav` store
- [ ] `search` store
- [ ] `media` store: split into `media-results` for individual `mediaType`s, `single-media` for the media detail pages, and `all-media` for 'All Content' view.
- [ ] `related-media` store
- [ ] `provider` store
