### ISSUE TITLE
Home page should reset the media results on mounted

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1261]
## Problem

If you use search, then go back to the home page using the Openverse logo in the header, and search from the search bar, you can see the flash of previous results. Description in another PR's comment: https://github.com/WordPress/openverse-frontend/pull/1259#discussion_r848567479

## Description

We should reset the results in the home page `onMounted` hook. 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
Fixed in #1260.

**Comment by obulat** [comment]
Thank you @krysal  ❤️
