### ISSUE TITLE
No results after changing search term

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1263]
## Description

Sorry of the vague title, but it is easy to reproduce. This does not happen in production but does occur in staging (`search-staging.openverse.engineering`).

## Reproduction

1. Search for "galah" from the homepage
2. Select the pdm filter
3. Search for "birds" from the header (the resulting query will be `q=birds&license=pdm`)
4. You will now see a "no results" page (even though there are results for pdm licensed bird content)

## Additional context

Marking as critical because it's very easy to reproduce.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
Fixed in #1216.
