### ISSUE TITLE
No audio results after searching from single audio result page

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1264]
## Description

Searching for `"birds"` from the single galah audio result page will result in an all results page that does not include any audio results (even though there's lots of audio for birds).

## Reproduction

1.  Search for "galah" from the homepage
2.  Switch to the audio results view and select the single audio result
3.  Search for "birds" from the header of the single audio result page
4. Note that there are no audio results.

If you refresh the page (searching for birds again) there will be lots of audio results.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
This was fixed in #1216.
