### ISSUE TITLE
Audio results are not re-fetched if re-searching from the homepage after using back button

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1265]
## Description

The audio results are no re-fetched if you use the back button to get back to the homepage and search for a different term.

## Reproduction

1.  Search for "galah" from the homepage
2.  Use the browser back button and then search for "dogs"
3.  Note that the single "galah" audio result is the only audio result shown for the "dogs" search

## Additional context

Marking as critical because it's easy to reproduce and likely that a user will run into this.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
Fixed in #1216.
