### ISSUE TITLE
"Back to search results" link is missing in image/audio detail page 

### ISSUE THREAD

**Issue by KAJALwp** [WordPress/openverse-frontend#1266]
## Description
When we are in detail page of image/audio and click on any related image/audio then there is no any option to come back to the previous page.
For better understanding I provide video attachment link.

## Reproduction
1. Search for image like “Nature” in openverse.
2. Select any image/audio.
3. On the above of image there Is an option of “Back to search results” which is redirecting us to search result page.
4. Select any image/audio from related item.
5. On the above of image there Is no any option of “Back to search results” so we cannot come back to the previous page.

## Video
https://screencast-o-matic.com/watch/c3fihhVqgz1

## Environment

 - Device: Macbook
 - OS: Monterey 12.2.1
 - Browser: Chrome Browser
 - Version: 99.0.4844.84 (Official Build) (arm64)

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
Thanks for the report @KAJALwp!

@panchovm what do you think about this? Should we persist the "back to search results" button through to related results?

**Comment by panchovm** [comment]
Hi @KAJALwp 

If you see the [last release's mockups](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Audio-Release?node-id=133%3A6869), the idea with single results view is to show a close button on the top-right side, outside the modal. The current implementation is temporary.

Now I wonder if the browser's back button needs to go back to the previous view when a user jumps between related results in the single result view, as in the video shared above. My response is yes, as long as it always shows the close button in the modal to close it and see the search results grid.

Regarding modal implementation, I think it is blocked by moving openverse out from the current site. Am I correct @sarayourfriend?

**Comment by sarayourfriend** [comment]
@panchovm the modal is blocked by not having a clear way of implementing the navigation inside it I think. I still have the issue assigned to me but I haven't looked at it in a while.

**Comment by KAJALwp** [comment]
Hello @panchovm, @sarayourfriend 

I think we should persist the "back to search results" button through to related results because there is no ways to go back in search page for the related detail page. As we can see that we don't have link in related image/audio detail page.

Thanks

**Comment by sarayourfriend** [comment]
@panchovm would that be a reasonable stop-gap until the modal is able to be implemented?

I'll start looking at the modal again once the frontend stability has settled down.

**Comment by panchovm** [comment]
Yes. That is very reasonable. Thank you both

**Comment by obulat** [comment]
The stop-gap solution of showing the "Back to search results" link on the single results pages opened from a Related image link has been implemented as you can see in the video:

https://screencast-o-matic.com/watch/c3XY1AVUZz3
