### ISSUE TITLE
Homepage search type buttons for small width viewports run off screen in languages with longer labels

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1295]
## Description

Long search type titles (like in RU language) render off screen on small viewports

## Reproduction

Visit `/ru` on a small viewport and observe the off-screen rendering of the page.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by panchovm** [comment]
Removing the `needs design` label as #1433 addresses this change.

**Comment by obulat** [comment]
Fixed in #2087
