### ISSUE TITLE
Strip extensions from audio results where the title appears to be a file name with extension

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1303]
## Description

Example: https://search-staging.openverse.engineering/audio/b9487d22-4927-4d09-a3f0-465e3ec4ceb6

Originally reported by @dhruvkb 

This would probably require compiling a list of common audio file extensions. mp3, wav, ogg, flac are probably the biggest ones (except for flac I've noticed each of those with this problem before).

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
This is an issue for the catalog (though I understand if it wants to be hidden in the interface first), we did the same for Wikimedia images.

**Comment by sarayourfriend** [comment]
Should we make a companion issue in the catalog or move this one there?

**Comment by zackkrida** [comment]
I know this doesn't look good, but I'm weary about manipulating the titles of works based on what appear to be file extensions. Silly example, but [this song](https://www.youtube.com/watch?v=ON7chZBcZ_Y) is called `adventure.exe`, for example. These names with the file extensions were submitted to the sources this way. How far would we take this? For example, should we automatically title-case names; replace '_' with ' ' in names, or do other manipulations? Should we infer that `my_awesome_song.mp3` should be `My Awesome Song`?

**Comment by sarayourfriend** [comment]
Wouldn't we keep a list of audio extensions? Someone could still call their vaporwave song `cool-jam.mp3` though. :confused:

**Comment by zackkrida** [comment]
My primary concern is with the entire concept of 'editing the creator-supplied title'. I don't think we should do that. And yes, your example is a good one!

**Comment by sarayourfriend** [comment]
To be fair, I don't think it's clear that the are always a creator supplied title _of the piece of media_ though. I doubt that there are that many edgy bird audio recorders naming their bird sounds with vaporwave naming conventions, and yet we have lots of bird audio that is `something.wav`. The problem is that we can't tell the difference once it gets to us.

**Comment by zackkrida** [comment]
@panchovm I would love to hear your thoughts on this from a product and design perspective, and also knowing that you've talked to audio creators in the past while doing user testing.

**Comment by obulat** [comment]
My vote is _for_ stripping the extensions because I agree with @sarayourfriend that _most_ of the time the extension was not intended by the user to be a part of the title. And it's sometimes confusing when the title has a different extension than the file itself.
