### ISSUE TITLE
Improve visibility of three-dot menu

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-frontend#1305]
## Description
The three-dot menu icon is small and difficult to see.

## Alternatives

We could adjust the weight of the three dot icon to improve visibility, or consider using a text label instead of the button when possible while accounting for screen width.

## Additional context

Originally reported by @zackkrida 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
I am going to close this issue because implementing #1699 will fix it.
