### ISSUE TITLE
Unable to open modal more than one time per page load

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-frontend#1308]
## Description

The mobile content switcher can only be opened once on iOS.

## Reproduction

1. Go to `/search?q=greyhound`
2. Tap the content switcher and either select a different Content Type or tap the x to close and return to the search results.
3. Tap the content switcher a second time; nothing happens, and the content switcher does not open.

## Environment

 - Device: iPhone XS
 - OS: iOS 15.4.1
 - Browser: Chrome
 - Version: 100.0.4896.85
 
Original reporter @panchovm. This could not be reproduced in Firefox on Android.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
I can reproduce it on my Android, with Firefox.

**Comment by sarayourfriend** [comment]
I'm able to reproduce on desktop in small viewports as well.

This is a problem with the modal component itself, you can reproduce it in the modal storybook here: https://wordpress.github.io/openverse-frontend/?path=/story/components-vmodal--default

**Comment by sarayourfriend** [comment]
This is blocked by https://github.com/WordPress/openverse-frontend/pull/1275 and https://github.com/WordPress/openverse-frontend/pull/1279.
