### ISSUE TITLE
Can't scroll page while mousing over "Report Content" modal

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-frontend#1310]
## Description

If you open the `Report Content` modal on a single result page, you are only able to scroll the body of the page if your cursor is hovering outside the modal.

## Reproduction

1. Open any single image page.
2. Click `Report this content` to open the modal
3. Move your cursor outside of the modal (but do not click). See that you can scroll the page.
4. Mouse over the modal itself, and attempt to scroll. See that you can no longer scroll the page (and the modal itself is not scrollable).

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by anton202** [comment]
@stacimc can`t recreate this. am i doing something wrong?

https://user-images.githubusercontent.com/29175506/204260676-4b82a2e3-57c6-466b-bc26-6106da545ca3.mp4
