### ISSUE TITLE
Component scaffolding generator

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1323]
## Problem

When creating a new component, there's a few things you need to add in various places that can make the initial set up a little cumbersome:

1. The SFC itself
2. The tsconfig.json includes entry
3. The storybook `.mdx` file (with all it's boilerplate)
4. The unit test file
5. The storybook snapshot tests

All of this could be templated out using something like lodash templates (or maybe something else :shrug:) and a package.json script could be created to scaffold out all the support for a new component.

## Description

To keep things simple, we could use something like https://github.com/ItsJonQ/remake to implement the whole process top-to-bottom.

Adding the `tsconfig.json` includes entry would need to happen separate from remake as I don't believe it has the ability to update existing files, just generate new ones.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by anton202** [comment]
working on it

**Comment by anton202** [comment]
hi @sarayourfriend 
regarding: 5. The storybook snapshot tests
you mean that we need to create a file inside of: `test/storybook/visula-regression`
that contains something like this:
```
import { test, expect } from '@playwright/test'

test.describe('component-name', () => {
  test.describe('default', () => {
    test.beforeEach(async ({ page }) => {
      await page.goto('/iframe.html?id=components-componentName--default-story')
    })
  })
})
```

**Comment by sarayourfriend** [comment]
Yup, precisely! It'd be nice if the template actually used the `breakpoints` utility as well:

```ts
import * as breakpoints from '~~/test/playwright/utils/breakpoints'

breakpoints.describeEvery('component-name', () => {
  // ... the rest of what you had in here
})
```

That way we can encourage testing across breakpoints. @obulat Maybe you have some opinions about which breakpoints to include for these. Should it be all of them or maybe just one mobile and one desktop? :thinking:

**Comment by zackkrida** [comment]
Awesome suggestion, I love this kind of thing. A few years ago I had put something together for Next.js that got a bit of traction in the community: https://github.com/zackkrida/next-codegen

**Comment by anton202** [comment]
@zackkrida  https://github.com/zackkrida/next-codegen Nice!

**Comment by anton202** [comment]
any suggestions, ideas on how to add the component name to tsconfig.ts includes property ?
should i just create a Node.js script to do that?

**Comment by sarayourfriend** [comment]
A script to do it sounds good, yeah :slightly_smiling_face:
