### ISSUE TITLE
Related results never load for SSR

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-frontend#1339]
## Description

In some cases, the "related results" loader spins continuously and never loads results.

## Reproduction

1. Visit https://search-staging.openverse.engineering/ru/audio/a56ff303-9983-4c21-a7f4-e1e454153ebe
2. Observe that related results never load

## Environment

 - Device: Mobile & Desktop
 - OS: Android & Ubuntu
 - Browser: Firefox

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
Changing this to critical as it's part of the critical path of the search experience.
