### ISSUE TITLE
Discrepancy between action buttons on single result page

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-frontend#1341]
## Description

The "action" button on a media's single result page is different between images and audio. For images, it says `Go to image's website`, but for audio it says `Download`. For users looking to download media, this discrepancy can create confusion.

## Reproduction

* Image example: https://search-staging.openverse.engineering/image/0439408c-11ae-490e-a10a-8139766f68fb
* Audio example: https://search-staging.openverse.engineering/audio/5a679d59-5868-4339-b208-50a05770a2a2

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
I had a thought for the language here, potentially "Review and download <type> from the source"? Something along those lines? It's wordy though, which may be an issue.
