### ISSUE TITLE
Header size change is jarring on mobile

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-frontend#1342]
## Description

Quickly scrolling to top of page on mobile causes jarring header size changes.

## Reproduction

1. Visit a result page on mobile and scroll down so that the scrolled header shows.
1. Quickly scroll back to the top. 
1. Note the jarring header resizing after the scrolling has stopped.

## Screenshots

https://user-images.githubusercontent.com/10214785/165646939-6e9abbbd-762e-4554-b0fb-edb9d46fe08f.mp4

## Environment

 - Device: Mobile
 - OS: Android
 - Browser: Firefox

## Additional context

From @sarayourfriend:
> Could be fixed by showing the un-scrolled header when you scroll up at all rather than waiting to reach the top

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
I am going to close this issue because we plan to use the new header layout that does not have this issue soon.
