### ISSUE TITLE
Audio 'File type' filters are missing types

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1347]
## Description

Currently, Audio only shows `mp3`, `ogg` and `flac` **File type** filters.

We need to add `wav` and `aif` to the list (any other type I missed?).
First reported by @dhruvkb 

## Reproduction

1. Go to `https://search-staging.openverse.engineering/search/audio?q=sound&extension=mp3,ogg,flac`
2. Open the filters if they are closed. Scroll down to the File type section.
3. You can only see 3 items in the list.

## Screenshots

<img width="154" alt="Screen Shot 2022-04-28 at 8 29 16 AM" src="https://user-images.githubusercontent.com/15233243/165682731-e2c2d6f4-5892-47a7-8485-cd0cd5f1f1bf.png">

## Additional context

Audio filtering by extension is still under development on the API and the Catalog side, so it's difficult to test.
I could only get results for filtering by `mp3` extension (which includes all the audio results).

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
I wonder if these should be returned in the audio stats request (maybe same with the photos one) so we're not trying to hand maintain a list of all the formats we've catalogued.

**Comment by obulat** [comment]
For context, here are the `filetype`s we currently have in the audio database:

| filetype |
|----------|
| mid      |
| mp32     |
| oga      |
| wav      |
| webm     |
| flac     |
| mp3      |
| opus     |
| ogg      |
