### ISSUE TITLE
Incorrect text styles on image single result page on mobile

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1365]
## Description

The single image result page has different text styles.

This issue is blocked until @panchovm confirms the necessary changes.

@panchovm , Could you please update this issue, correcting any wrong todos here? I copied the styles with their names from the Figma mockup, but the styles with the same name have different values 🤷
- Update only for mobile (below `md` screen)?
- Update the  _Go to image's website_ button text style to **Caption bold**:
```
font-family: Inter;
font-size: 12px;
font-weight: 600;
line-height: 16px;
```
- Update the image title text style to **Description bold**:
```
font-family: Inter;
font-size: 14px;
font-weight: 600;
line-height: 18px;
```
- Update the image author text style to **Description bold**:
```
font-family: Inter;
font-size: 14px;
font-weight: 600;
line-height: 18px;
```

## Reproduction

1. Go to the single result view of an image (eg. https://search-staging.openverse.engineering/image/f9384235-b72e-4f1e-9b05-e1b116262a29).
2.  The text styles of CTA (_Go to image's website_ button), image title, and image author all look different. This feels odd and inconsistent.

## Additional context

Figma mockup of the single image result page: https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Audio-Release?node-id=958%3A19663

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by panchovm** [comment]
Your description is correct. Thanks for asking
