### ISSUE TITLE
Executing search on mobile using the keyboard 🔎 key does not close the keyboard

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1367]
## Description

When you use mobile keyboard's 🔎 key to submit search from the header, the keyboard doesn't close. 

## Reproduction

1. Open https://search-staging.openverse.engineering/search/image?q=cat on a mobile phone.
2. In the header search bar, change the search term.
3. Press the mobile keyboard 🔎 button. 
4. See error: the keyboard is still open.

## Screenshots

https://user-images.githubusercontent.com/15233243/166218654-2760bf88-f0c5-4a5f-96a3-de0ff3468b76.mp4

## Environment

 - Device: Samsung phone
 - OS: Android
 - Browser: Firefox

## Additional context

The solution is probably to `blur()` the input element on search form submit.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
Can reproduce on iOS as well. My search also resulted in recommendations to manually invoke `blur` so we should just go ahead and do that.
