### ISSUE TITLE
Openverse logo shifts when opening filter sidebar

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-frontend#1375]
## Description

When opening the filter sidebar on mobile in the results page, the Openverse logo shifts up and down slightly.

## Reproduction

1. Visit https://search-staging.openverse.engineering/search/image?q=food on mobile
2. Open the filter sidebar
3. Observe that the logo shifts slightly

## Screenshots

https://cln.sh/qLyzpg

## Environment

 - Device: Mobile
 - OS: Android & iPhone
 - Browser: Chrome & Firefox

## Additional context

From @panchovm

> We fixed this bug for one of the two menus but now it is broken on both

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
I have this fixed in #1272 :slightly_smiling_face:
