### ISSUE TITLE
Load More button appearing below related results

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1377]
## Description

The load more button is appearing below the related results.

See on main at `/image/c3dd51ac-f900-48a4-a957-380061a55cb7`.

## Reproduction

1.  Visit `/image/c3dd51ac-f900-48a4-a957-380061a55cb7`
2.  Scroll down and see the load more button

## Additional context

Found while testing https://github.com/WordPress/openverse-frontend/pull/1349

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
Reassigned to @obulat who fixed this in #1349.
