### ISSUE TITLE
Add minimum threshhold to bundle size analyser

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1380]
## Problem

Currently the https://github.com/WordPress/openverse-frontend/blob/main/.github/workflows/bundle_size.yml workflow shows many, many changes to files that are all less than ~5b different. This seems like noise that we could filter out with the `minimum-change-threshold` [attribute](https://github.com/preactjs/compressed-size-action#increasing-the-required-threshold). Perhaps we could set it to around 10 bytes?

```
minimum-change-threshold: 10
```

**Update**

Some discussion went on below. Let's implement the following:

1. minimum-change-threshold to 10 as originally suggested
2. exclude the translation bundles

**Comment by sarayourfriend** [comment]
I don't personally think this is necessary and would like to wait longer before investing in this. It's also not possible with the compressed-size-check as far as I can tell and would require upstream changes. In my experience the maintainers are _really_ busy with other projects and are not quick to respond to PRs (even when they have lots of :+1: and comments in support), they're just too busy.

**Comment by zackkrida** [comment]
@sarayourfriend I suppose the threshold shouldn't relate to the actual output we're seeing, but what size we actually care about. For example, I personally don't think anything less than 1kb is something I'd want to know about and would consider such a change 'noise'. We definitely don't need to rush into this at all, however.

**Comment by dhruvkb** [comment]
Along the same lines but a bit more extreme, I also think we could just not show differences that reduce the size of the bundle. If there is an increase (above a certain threshold) we flag it, otherwise we just let it pass as is.

**Comment by sarayourfriend** [comment]
> Along the same lines but a bit more extreme, I also think we could just not show differences that reduce the size of the bundle. If there is an increase (above a certain threshold) we flag it, otherwise we just let it pass as is.

I do like being able to celebrate wins against bundle size.

I am really of the opinion that if we take an "every byte counts" approach, that we can see significant gains over time. Being able to see even small reductions can feel good, like progress.

**Comment by zackkrida** [comment]
Here's an example of a so-called 0% change that is a change of 96 total bytes:

https://github.com/WordPress/openverse-frontend/pull/1381#issuecomment-1116679054

Hypothetically, if `minimum-change-threshold: 20` was set on this PR, I wonder what would happen? Would the bot post that there was _no change_, or would it post that there was a 0% change but show no changed files? The later might be really confusing.

**Comment by sarayourfriend** [comment]
@zackkrida in that case it would report it because it's over the threshold of 20 bytes, right?

But point taken. I would assume it just filters them out and reports no change if everything is less than the threshold.

Could we set it to 10 and see what happens?

**Comment by zackkrida** [comment]
@sarayourfriend my thought was at the threshold was per changed file, not for the total diff. In that last example the total change was 96 bytes but no individual file had a change greater than 20b.

**Comment by sarayourfriend** [comment]
Oh, I misunderstood, I thought you meant that each file had changed by 96. Then yes, it would report no changes in that case if none have changed more than 20 bytes.

Part of our problem is we have a huge number of bundles and no control over them really. And then there are the mysteriously named `236.js` type bundles.

**Comment by sarayourfriend** [comment]
I wonder if we should also exclude the translation bundles. They're about 50% of the bundles measured.

**Comment by dhruvkb** [comment]
I'd be in favour of removing them. Translation bundles are beyond our control so having them in the list doesn't add any value imo.

**Comment by sarayourfriend** [comment]
I updated the issue description with the recommended changes and removed the discussion label. This is ready for work now :+1:
