### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-frontend#1416]
## Problem
https://sentry.io/share/issue/6c7aecd9d89d4fd5a1b9ef160d9a7696/

## Description
This appears to have been caused when the user visited this audio file and (from what I can tell) clicked the play button repeatedly: https://search.openverse.engineering/audio/b4ccb2bd-3adf-43df-b609-dbb05cdf77ff

Our only other reference to `ResizeObserver` was last updated in #795

## Reproduction
I tried resizing the screen while hitting play/pause via the space bar repeatedly but was not able to reproduce the issue.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
Sentry details are lost. This is probably fixed in #795 so I'm closing it.
