### ISSUE TITLE
Non existent target on VTeleport mount: "skip-to-content"

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-frontend#1417]
## Problem
https://sentry.io/share/issue/8fc0b4ebdcb84a4b84475fc4d61a4f51/

## Description
From my guess it looks like the page loaded and attempted to teleport to a section of the page that either didn't exist or hadn't rendered yet.

The closest related issue I could find is #817

## Reproduction
I was unable to reproduce, and this appears to only be happening in Edge on Windows 10

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
Related issues: #615, #1078. 
This is related to how we are handling VTeleport destruction, probably destruction on page reload, but I'm not sure how to solve it. When we move to Nuxt 3 with Vue 3, we can probably fix this issue by using the Vue implementation of the Teleport.
