### ISSUE TITLE
Back to top button present when page has no scroll

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#1423]
## Description
The Back to Top button is still visible although it does nothing if the page has no room to scroll. Reported by @stacimc 

## Reproduction
I could not reproduce the bug on desktop, whereas all results show the action due to the page's height on mobile. I landed on search results with no more than four items, and the scroll button was not visible.

## Additional context
Issues with similar behavior reported:
* #1151
* #1348  

## Resolution
- [ ] 🙋 I would be interested in resolving this bug.

**Comment by stacimc** [comment]
👋 I've just tried this again and was also unable to reproduce; maybe something was fixed in the interim. I think this can be closed 👍

**Comment by zackkrida** [comment]
Can't repro this either, nice!
