### ISSUE TITLE
Wrong format displayed in the Credit the creator box

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#1425]
## Description
When opening an URL to see the single result view of any content, tabs in Credit the creator box show an incorrect format of the attribution information. Rich text tab shows HTML content, HTML tab shows plain text, and Plain text shows nothing. 

This does not happen when opening a result from the search results page.

## Reproduction
1. Open [this result](https://search-staging.openverse.engineering/image/0fc8d459-6c59-4370-ae20-cc83c4a64e65).
2. Play with the tabs of the **Credit the creator** box.
3. See the error

## Screenshots
![CleanShot 2022-05-12 at 12 08 29](https://user-images.githubusercontent.com/895819/168120330-30f4dd60-97d7-4a67-b97e-79627932b594.gif)

## Environment
 - [Staging](https://search-staging.openverse.engineering)
 - Device:Macbook Pro M1 13-inch
 - OS: MacOS Monterey 12.3.1
 - Browser: Firefox
 - Version: 100.0

## Resolution
- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
This seems to be a problem on _server-rendered_ single image results. It appears that the indices of the tabs are off by one somehow, which results in a default state of _no_ active tab, and each tab being shifter over one position.
