### ISSUE TITLE
"/search/video" URL crashes app

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-frontend#1428]
## Description

Navigating to `/search/video` causes the app to crash.

## Reproduction

- https://search.openverse.engineering/search/video/
- https://search-staging.openverse.engineering/search/video

## Additional context

https://sentry.io/share/issue/0168474ee4fd4a62b3f891089a2f21d9/

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
I might consider downgrading this to `high`; there's no user-facing link to `/search/video` that I'm aware of

**Comment by obulat** [comment]
These errors are mostly caused by the CC Search redirects.

**Comment by zackkrida** [comment]
Oh, that's right, CC Search had a video url. Its shows up in google searches as well!

<img width="633" alt="CleanShot 2022-05-13 at 09 42 58@2x" src="https://user-images.githubusercontent.com/6351754/168296716-6b58b17c-6efb-474d-bb96-f01fd1bb7de9.png">
