### ISSUE TITLE
Redesign homepage for the standalone site

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#1433]
## Problem
As Openverse will be in a standalone site, out of [wordpress.org](https://wordpress.org/), we need to update the homepage to this new context. The page needs to be more explicit about what Openverse is, how to contribute to the project, showing content about the project living inside the site, and its relation with WordPress.

Besides the above, the page needs to fix showing the content types in the content switcher by meeting a11y and i18n requirements.

Since the scope of this change is moving Openverse to a new site, current functionalities and tweaks must tend to be as minimum as possible, mainly to accomplish the primary goal described above.

## Issues related
- #991 
- #978 
- #1198 
- #1295
- #1174 
- #125 

## Proposal
https://user-images.githubusercontent.com/895819/170377079-ef058db0-bd42-4a85-bc81-96b452cb0cf2.mp4

https://user-images.githubusercontent.com/895819/170377728-d253d3f0-e859-442f-9ece-ea99e6af72fe.mp4

### Description
As you can see, compared to the current menu, this one has fewer items since I made the following changes:
- All items have no dropdown elements.
- There is a “Get involved” item linking to either the make blog or the handbook.
- Sources, Our story, Search Guide, and Meta Search pages are inside About as page’ sections instead of separated pages. I think we do not need most content from the Meta Search page as the feature should explain itself by using it, except for the paragraph describing why we have it.
- API is a page in Openverse instead of external. I suggested this time ago, but I would like your thoughts. I am not thinking of redesigning the page but placing it in the openverse site.

The main title has a light font weight to balance the page contrast and not compete with the openverse logo.

Once opening the switcher, content-type items have smaller icons to reduce the popover size, and the video option was removed. This last point is a significant change for the user experience, but the reason is not providing a content type that sets the expectation of browsing content as the others, to then finding a white page with links to external sites. The promise of searching for relevant content would not be met.

Nonetheless, the video option still will be in the search result page. I would like to see your comments on this proposal.

I displayed the sample search results in a row at the bottom and added an interaction showing the content title. I did not want to hide content depending on the viewport, but I do not have a clear idea about how it looks like on big screens.

To show that openverse relates to WordPress, I added a small note in the footer. I was thinking of adding more content but could not find any reason why do it.

On mobile, I think the best way to solve the content type labels is by hiding them and letting users tap the icon to see the options. If we show the content type names, we will have to deal with i18n all the time.

The bottom-up box to see select a content type is an idea I like, but it would work only on this page. The current flow of *leaving the site* when seeing a full-size modal to select a content type feels odd at this stage of the search journey.

This proposal has many nuances, so I am happy to hear your thoughts and try new ideas. 

## Mockup
- Figma: [3D model support and homepage redesign](https://www.figma.com/file/IFIqt7Q3MEKMLSnBedzHBO/)

**Comment by obulat** [comment]
I love the design, @panchovm ❤️ 

> On mobile, I think the best way to solve the content type labels is by hiding them and letting users tap the icon to see the options. If we show the content type names, we will have to deal with i18n all the time.

I really like the content type selector interaction on mobile! Having only an icon in the searchbar is great because it fits well on a narrow screen. I was wondering if we could add an `x` button for clearing the mobile searchbar: on mobile, clearing up a long string without it is a frustrating experience. On the other hand, we are an image search engine, so the users probably don't use long queries...

> The bottom-up box to see select a content type is an idea I like, but it would work only on this page. The current flow of leaving the site when seeing a full-size modal to select a content type feels odd at this stage of the search journey.
This feels much more natural for mobile experience!

**Comment by panchovm** [comment]
Glad that you loved the design @obulat 🙂 

> I was wondering if we could add an x button for clearing the mobile searchbar: on mobile, clearing up a long string without it is a frustrating experience

You are very right. I forgot to add it. I will work on that.

I actually understood something different before reading the whole sentence. I thought you referred to closing the modal for selecting a content type, and that part can be improved too. The only actionable element is the gray bar in the modal's top area to drag it down, and replacing it with an explicit close action seems clearer and more effective.

**Comment by panchovm** [comment]
Here is a new flow fixing the input clear and closing the switcher.

https://user-images.githubusercontent.com/895819/170731173-d427ab09-c0a1-4b2b-9802-052fb6282cc0.mp4

**Comment by zackkrida** [comment]
Sorry about not getting you feedback sooner, @panchovm! I love the overall layout and the addition of the menu items, along with the dark-background mobile menu. Some feedback on points you made:


> All items have no dropdown elements.

👍 

> There is a “Get involved” item linking to either the make blog or the handbook.

👍 

> Sources, Our story, Search Guide, and Meta Search pages are inside About as page’ sections instead of separated pages. I think we do not need most content from the Meta Search page as the feature should explain itself by using it, except for the paragraph describing why we have it.

I agree that 'meta search' doesn't need its own page, I am not sure about the Sources and search guide. I think those are both a lot of content and warrant their own pages. However, we could add links to those pages on the "About" page. In general, maybe the About page would be a good thing to leverage as a sort-of landing/marketing page for the project. 

Alternatively, we could add more content 'below the fold', like DuckDuckGo does: 

https://duckduckgo.com/

> API is a page in Openverse instead of external. I suggested this time ago, but I would like your thoughts. I am not thinking of redesigning the page but placing it in the openverse site.

I am not sure about this, but I don't think it blocks this proposal at all. It's a matter of having the external icon or not, really. 

---

One thing I still think we need to address is having a little more content and clearer content on this page. From a SEO perspective but also one of user understanding. 'items for reuse' is not as clear to folks as 'free stock photos' or 'free to use images' or whatever. Obviously those terms aren't correct for this project, but we still need to develop more and better content for this page and it would be nice to do alongside the redesign. 

My very last thought: The new page looks amazing, but it loses a bit of the WordPress jazzy-ness of the current page, which has movement from the diagonal lines of the staggered images on desktop. I don't think we _have_ to keep that feel, but I wonder if there are ways to preserve it in some sense.

**Comment by panchovm** [comment]
Coming back late here too.

> maybe the About page would be a good thing to leverage as a sort-of landing/marketing page for the project.

You are right about this, and that Sources deserves its page. My main discrepancy with the Search Guide content is putting it inside a page rather than explaining its potential through the search experience, i.e., showing the syntax commands in the recent searches popover. I would like to explore a solution for this idea to be more explicit about my point.

> I am not sure about this, but I don't think it blocks this proposal at all. It's a matter of having the external icon or not, really.

Exactly 👍 

> The new page looks amazing, but it loses a bit of the WordPress jazzy-ness of the current page, which has movement from the diagonal lines of the staggered images on desktop. I don't think we have to keep that feel, but I wonder if there are ways to preserve it in some sense.

I like the feeling you are bringing. I can definitely work more on this aspect.

In general, it seems that your comments @zackkrida point to enhancing the page look and feel by bringing more brand and jazzy elements. I agree with the idea but my initial plan was to narrow the implementation scope as the upcoming domain change might require us to move quickly.

But that is open to change indeed.

**Comment by zackkrida** [comment]
@panchovm I think the page would be a great improvement. If we end up prioritizing the iframe project we could definitely launch this page as-designed here.

**Comment by panchovm** [comment]
Coming back to share a new version of this page as we are facing a new context based on four points:

1. Openverse will be placed in a standalone site under openverse.org. This shift boosts the product independency while meeting a new scenario for the brand. However, we need to highlight that it is part of the WordPress project, and therefore, link to its site.
2. The current copy was updated weeks ago (#1756) and does not need new updates.
3. The new header (#1669) changes the search flow, and therefore, this page needs to be consistent with that new interaction. 
4. The new footer (#1811) brings back the locale component (#1810) and the feature needs to be present from the beginning.

Without further details, here are the mockups.

## Desktop `lg`
<img width="1510" alt="Home (LG)" src="https://user-images.githubusercontent.com/895819/202435449-4f5e8dee-cc3f-4391-b6fd-f8f59b5ac838.png">

## Mobile `sm`
|Home|Menu|
|:---|:---|
|<img width="375" alt="Home (SM)" src="https://user-images.githubusercontent.com/895819/202435471-9028808b-2db6-4ce6-b7cf-5c28617cca52.png">|<img width="375" alt="Menu" src="https://user-images.githubusercontent.com/895819/202435474-7f1f22d5-42aa-479c-bf38-6396ea38d0b4.png">|

### Interaction flow
https://user-images.githubusercontent.com/895819/202456748-30b0694b-27c5-45eb-b76e-9e6074a9432b.mp4

---

On desktop, each image takes you to its single result view. Instead of cropping the gallery section, this proposal shows all images and remains fixed on the right side. As the viewport goes smaller, I was thinking of hiding columns of the gallery until showing nothing on `sm` view.

For the switcher flow, I reused the new drawer and replaced the main button with "Search" to ease seeing the results.

The pages listed in the header should solve the content needs we have, so it is fully open to changes whether we consider adding or removing pages.

What do you think of the idea?

**Comment by panchovm** [comment]
To your points:
1. ⭐ 
2. I also like the boldness of the current grid, but this layout eases the domain change and sets a baseline for improving the layout. I am not getting rid of the full-size image idea, but this one simplifies the upcoming update.
3. It does have UX problems. The main one is how the image size meets a11y requirements and adapts to viewports as it goes bigger with breakpoints. Cropping images has interaction problems, and it will require deep thought to reuse the idea without jeopardizing the content navigation.
4. I am not concerned about the footer inconsistency as this page is the "cover" context introducing the project. With that in mind, we need to highlight the WordPress dependency, and the mention in the footer felt insufficient. However, I agree with your point on showing the WordPress project and library license texts across the site, but for now, this solution allow us to make a quick change and leave room for those improvements in the future.

I appreciate your approach @dhruvkb. Thanks

**Comment by AetherUnbound** [comment]
I am +1 on @dhruvkb's first and second points!

Your examples also show the disclaimer for CC licensed content no longer linking to https://creativecommons.org/licenses/ - is that an intended change?

![image](https://user-images.githubusercontent.com/10214785/203163522-9c927692-1812-4bd7-a390-cf1d637e3d59.png)

**Comment by panchovm** [comment]
My mistake @AetherUnbound, thanks for noticing it. It should link to the CC licenses page. The link should have the same style, an underline in the resting state.

**Comment by panchovm** [comment]
Adding the discussion label to make clear the design proposal is not done yet.

**Comment by panchovm** [comment]
Here is a new version of the page.

|`xs`|`xl`|
|:---|:---|
|<img src="https://user-images.githubusercontent.com/895819/207672970-1c66acc2-d9f9-4d7b-919e-35038801bf70.png">|<img src="https://user-images.githubusercontent.com/895819/207672999-479fde68-33ec-4874-867e-4ba7dd34d271.png">|

The changes made are:
1. Replacing the WordPress logo with the [simplified version](https://wordpress.org/about/logos/) to make the mention less prominent.
2. Moving the WordPress mention to the footer to make it consistent with the last component update (see #2015).
3. Moving the CC license disclaimer below the search bar.

I also added the breakpoint variants. Here is a real-size frame with all mockups.

![Redesign i4](https://user-images.githubusercontent.com/895819/207673503-c1afe4de-0d0f-4b28-9bbf-87c7ad6c2df5.png)

---

# Questions and feedback
My main feedback request: What do you think of this version?

From `xs` up to `lg`, search area is the main content and is wrapped in the center by paddings on both sides. But from `xl` and beyond, search area's width is fixed, and the gallery appears on the right side.

The idea of this is to prevent a huge search bar on big screens, but since the right side would look empty, I was thinking of adding columns of images as there is available space, with a maximum of five columns. Once reaching the five columns, the gallery can float fixed on the right to balance the layout's white space. What do you think of this? Adding an example of how it might look like.

![imagen](https://user-images.githubusercontent.com/895819/207678230-8a6b6ab9-4cb0-4aa3-b776-849b1f0d8ff3.png)

**Comment by zackkrida** [comment]
@panchovm It looks great to me. 

I like the idea of adding columns to fill available space. I'm also fine with the logo swap to the "W" mark.

I'll connect with other WordPress.org community stakeholders to make sure the reduced prominence of the WordPress project callout is acceptable.

**Comment by AetherUnbound** [comment]
I think it's a great idea to limit the search bar size and fill in the extra space with more images! The new design looks fantastic 😄

**Comment by zackkrida** [comment]
We're good to move forward here 😄

**Comment by panchovm** [comment]
Awesome. I will start preparing the assets ✨

**Comment by panchovm** [comment]
# Final design
* [Presentation](https://www.figma.com/proto/lCE1be8juDzhXgyYsIIFHB/Homepage-redesign?page-id=26%3A13657&node-id=703%3A6498&viewport=320%2C523%2C0.13&scaling=contain&starting-point-node-id=703%3A6498)
* [Mockups](https://www.figma.com/file/lCE1be8juDzhXgyYsIIFHB/Homepage-redesign?node-id=22%3A13656)

---

The file assets are done. Changing the discussion label to ready for work ✨ 🚀

**Comment by dhruvkb** [comment]
@panchovm could you share the cropped square images that will be used (preferably along with the UUID identifiers so that we can link to their single result pages)? I assume there will be many, considering ~ 15 images per set.

These image sets will be needed when implementing the image grid.

**Comment by panchovm** [comment]
Sure! This week I am also selecting the remaining images for Universe, Olympic Games, and Indigenous pottery. So sharing them here as soon as possible.

**Comment by AetherUnbound** [comment]
These photos are excellent!

**Comment by panchovm** [comment]
@olga asked a great question in [the mockups](https://www.figma.com/file/lCE1be8juDzhXgyYsIIFHB/Homepage-redesign?node-id=705%3A6533&t=EJPJUnoE9RmYHZFI-4), and moving it here to see other thoughts.

> What should happen when you click on "See results" here (_when opening the switcher drawer without typing a search term_)? If you are redirected to search, then it can get confusing if the user hasn't entered a search term yet. We might have to indicate that they need to enter the search term then. And if it simply closes the modal, then the button label should be something like "Confirm selection/content type"

(Note added by me in _italic_)

Showing a message in the input field makes sense, but I wonder if Openverse might search regardless instead. Interrupting users from seeing results because they did not type a term seems like missing an opportunity to show Openverse. I am thinking of the `Universe`, `Olympic Games`, and `Pottery` as the default terms to match the homepage's gallery.

In this way, if users do not type anything, clicking on the search button or selecting a content type and then searching would take them to a result.

What do you think?

**Comment by obulat** [comment]
> In this way, if users do not type anything, clicking on the search button or selecting a content type and then searching would take them to a result.

Interesting idea!
It might also be confusing for the user who wanted to 1. Select the search type and then 2. type in the search term.
I wonder if focusing the search bar after you click the CTA button in the search type selection modal would be more or less clear... Would be nice to have some user feedback :)

**Comment by dhruvkb** [comment]
Taking them to a predefined search term based on the gallery seems wrong to me because:

- It's not immediately clear that the gallery consists of searchable, indexed content in Openverse. To a new user, it might seem like a curated collection of very high-quality CC works. This is further reinforced because when you search for something like "universe" or "pottery", none of the gallery results are on the first page.

- Since the gallery theme is not written anywhere, it is hard to relate a word like "universe" or "pottery" to the list of images in the gallery. So if clicking search takes them to the results page, it will seem like a random search. On mobiles, the gallery is not even visible, so there is even less reason to know why choosing a media type led them to a seemingly random search term.

- I agree with @obulat that people might want to choose a media type first and enter the term later. In that case, their planned interaction is interrupted. If we take them to the search box and they choose to hit search anyway, then the idea of taking them to some predefined search makes sense. We still need to make sure that the results for the term are very high quality, currently searching for pottery shows a very NSFW image.

Other search engines do nothing when the search button is clicked without a query. Taking the user to the search field and using the `required` attr for that field seems the most reasonable approach to me.

<img width="649" alt="Screenshot 2022-12-26 at 3 09 40 PM" src="https://user-images.githubusercontent.com/16580576/209542400-b1d57591-3676-4cc5-bd72-362ec568c944.png">

**Comment by panchovm** [comment]
> It might also be confusing for the user who wanted to 1. Select the search type and then 2. type in the search term.

You are very right. In that vein. Showing the "See results" button in the drawer does not make much sense as selecting a content type could close it and go back to the homepage showing the content type icon selected.

On the other hand, you are right @dhruvkb. The randomness feeling, especially on mobile. The relationship is not clear and the results might frustate if does not fit the expectation. Hence, requiring to type a search term is more clear.

Here is a prototype based on the flows advised above.

https://user-images.githubusercontent.com/895819/209559655-9d327b91-4636-438f-8328-af67897f304f.mp4

**Note:** _The prototype has spacings for interaction purposes, but are not part of the mockup._

I moved the content area slightly upwards so snackbar does not overlap the search bar. This change would require a different flex lauyout setting.
