### ISSUE TITLE
Audio seeking warning in Chrome displays poorly on small displays

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1436]
## Description

![CleanShot 2022-05-13 at 12 50 09@2x](https://user-images.githubusercontent.com/6351754/168331289-ee4155c7-d7ed-4c1d-9441-65c605a81af5.png)

On medium and below viewports, the seek warning message for Freesound and Jamendo tracks in Chrome looks terrible.
We should reduce the font size, line height, and center the text, and move the existing css font class sized to be be breakpoint prefixed.

## Reproduction

1. Go to any audio search result list in Chrome and hover a Jamendo or Freesound result, on a small-ish > 1000px browser width

## Environment

- Browser: Not Safari or Firefox
- Viewport: Between 600-1200px, roughly

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by ramadanomar** [comment]
I would be interested in resolving this bug.

**Comment by krysal** [comment]
@ramadanomar a PR is welcome. Thanks! I assigned it to you.
