### ISSUE TITLE
Filter sidebar styles are incorrect after rezing window horizontally from small back to large

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1440]
## Description

After resizing one's browser from a typical desktop size to small enough to view the mobile filters ui, returning to the desktop width results in a broken user interface. The `has-sidebar` css class fails to be reapplied to the main element.

## Reproduction

1. On a desktop display, open the filter sidebar
2. Drag the width of the window to around 300px, to switch to the mobile filter view
3. Drag the window back to the original width
4. Observe the site's `main` element is missing the `has-sidebar` class and that the sidebar is covering the site content

## Screenshots

<img width="1162" alt="CleanShot 2022-05-13 at 15 27 24@2x" src="https://user-images.githubusercontent.com/6351754/168376180-b2842cc6-52c0-42d1-8e49-8f5fa5818906.png">

**Comment by krysal** [comment]
I cannot reproduce the issue anymore (tested on Chrome and Firefox in [staging](https://search-staging.openverse.engineering/search/?q=galah)).

**Comment by zackkrida** [comment]
Yes, indeed it is fixed! I believe it was resolved by #1716
