### ISSUE TITLE
Global audio player track title is incorrectly pink

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1469]
## Problem

The global audio player is displaying the audio name link in pink text:

![CleanShot 2022-05-24 at 06 55 32@2x](https://user-images.githubusercontent.com/6351754/170019181-5e84118a-03e0-406a-a8f5-abe90ea1025e.png)

## Description

This text should be black, per the designs.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by VincentvI023** [comment]
Test
