### ISSUE TITLE
Audio detail page does not have horizontal padding on lg screen

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1478]
## Description

Audio page doesn't have horizontal padding, the content is right on the edges on the `lg` width (1024px).
## Reproduction

1. Set your screen width to 1024px.
2. Open an audio detail page.
3. See error.

## Screenshots

![Image of Openverse audio detail page without padding](https://user-images.githubusercontent.com/15233243/171220520-cdcaa9bf-53ea-4e7c-8fb3-7859a35defe9.png)

## Additional context

It would be nice to unify the paddings with the image detail page.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by carlosreyesmunoz** [comment]
🙋 I would be interested in resolving this bug.
