### ISSUE TITLE
[Feature] Audio track button focus styles

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#148]
## Problem
Similar to the waveform focus styles issue but easier to solve, the play/pause button needs some focus styles to indicate to sighted keyboard users that the button is focused.

## Description
Potentially add a ring around the button to indicate that it is focused (similar to how WP components does it)

<img width="224" alt="Captura de Tela 2021-08-23 às 13 49 36" src="https://user-images.githubusercontent.com/24264157/130517491-d3becbac-a41e-4c2a-8630-0ec102b287f8.png">

## Alternatives
We could also change the color of the button depending on whether it is focused but this might also be tricky to deal with certain types of color blindness. Typically I think I see a "focus ring" style on most buttons anyway.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
@panchovm could you please share a mockup of what the focus style should look like?

**Comment by panchovm** [comment]
Sure. After being done with the browser extension, I will go back to the single result pages, and this task will be the first one. I assigned myself as well.
