### ISSUE TITLE
Parallelize Playwright snapshot tests

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1491]
## Problem

Our multi-breakpoint Playwright snapshot tests take a long time to execute currently. We can parallelize these tests safely because they do not depend on each other.

## Description

Apply https://playwright.dev/docs/test-parallel#parallelize-tests-in-a-single-file to parallelize as many of our tests as possible that cannot be split into separate files.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
No doubt about why the [execution](https://github.com/WordPress/openverse-frontend/runs/7206074158?check_suite_focus=true#step:4:67) is so [slow](https://github.com/WordPress/openverse-frontend/runs/7206074158?check_suite_focus=true#step:4:5706) 😬
```
playwright_1  | > openverse-frontend@2.2.1 test:playwright:local /app
playwright_1  | > playwright test -c test/playwright
playwright_1  |
playwright_1  |
playwright_1  | Running 268 tests using 1 worker
```
