### ISSUE TITLE
Pages are loading slowly

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1516]
## Description

We have recently moved to using `asyncData` for search pages to fix the API being called twice for each page. This, however, had the unintended consequence of slowing the page load. Now, when you navigate to the search page from the homepage, it loads only after all the API calls have been completed, instead of loading the page skeleton first and showing the images/audio as soon as they are available.

## Reproduction

1. Open the homepage at https://search-dev.openverse.engineering
2. Search for something, and then open one of the results.
3. If you are on a not extremely fast network, you should see the loading indicator (black line) at the top of the pages instead of the more smooth page transitions, just like in the screenshot below.

## Screenshots

![transition](https://user-images.githubusercontent.com/15233243/173015245-1bf97794-7331-4358-9a4e-fcc940544052.gif)

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
@obulat Should we use asyncData only for SSR renders? :thinking:
