### ISSUE TITLE
[Feature] Decide on the placement of PO, POT and POT generator files

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#153]
## Problem
To use [GlotPress](https://wordpress.org/plugins/glotpress/) for translations, we need to convert strings from `Vue-i18n`'s json format into PO format, and to vise-versa.
Therefore, the following files will be added to the repository:
- script that converts `json` to `.pot` files (#151)
- script that converts `.po` files for different languages to the corresponding `json` files.
- folder with the `.po` files with translations done using GlotPress.

We need to decide where it makes sense to put the conversion scripts and the folder with `.po` files, and move them accordingly.

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
We decided to use subdirectories in the `locale` folder.

**Comment by zackkrida** [comment]
Placement is determined, we still need to fix some file naming issues related to casing but that will be addressed in a separate PR.
