### ISSUE TITLE
Add clarification for length filters

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1538]
## Problem

It can be difficult to understand what the length filter names mean.

## Description

We should add clarification. Something like:
- [ ] shortest under 30 seconds
- [ ] short 30 seconds - 2 minutes
- [ ] medium 2 - 10 minutes
- [ ] long above 10 minutes
Before implementing this, we need a design for it. This is what the current filters look like:
<img width="297" alt="Screen Shot 2022-06-19 at 7 11 18 AM" src="https://user-images.githubusercontent.com/15233243/174465852-df6e9e8d-9ab4-455d-925f-cb40f80ae349.png">

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
@panchovm since we need updated design for this component, should we tag this issue as `aspect: design`?

**Comment by panchovm** [comment]
The `needs design` label is sufficient. From this, I can start working on a proposal and sharing it under the `aspect: design` label.

**Comment by zackkrida** [comment]
Do we need additional design? Could we not keep the checkboxes and redesign it later?

**Comment by obulat** [comment]
I think we need to know which font to use for the labels and the exact wording.

**Comment by panchovm** [comment]
For the checkbox elements, we need to use the existing element. But I was thinking of exploring different solutions for this filtering need.

Before, we considered using a number field for setting the duration time, a slider, or multiple radios instead of checkboxes. Nonetheless, and as @zackkrida said, we can implement the solution shown in the description and review alternatives afterward.

**Comment by zackkrida** [comment]
@obulat Have we officially updated these values in the API, yet? Or to ask differently, are the times outlined in this issue accurate?

```
shortest (>30s)
short (30s-2min)
medium (2-10min)
long (>10min)
```

@WordPress/openverse do you think 's' for seconds, and 'min' for minute, along with using greater-than and less-than symbols, is good for the English translation? Here's a mockup:

<img width="247" alt="CleanShot 2022-06-27 at 15 21 08@2x" src="https://user-images.githubusercontent.com/6351754/176019419-ac7a1839-9fa1-4f23-aa40-77b4f092c850.png">

**Comment by obulat** [comment]
Yes, I've actually copies the values from the API, so they are accurate. At least for the newly-indexed audio items.
