### ISSUE TITLE
Generate a version.json file based on the ref of the current build

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1557]
## Problem

We'd like to have an Nginx sidecar container to go along with our Nuxt container in ECS. This nginx container at first will just be responsible for serving the https://search.openverse.engineering/version JSON file.

## Description

Add a second stage to the Dockerfile for the repository that builds an nginx image. Add building and publishing this image to the GHCR workflow. Push it to `openverse-frontend-nginx`. Generate a `version.json` file in the Nginx container based on the ref of the current build. For staging, it'd be nice to list the actual commit SHA of the `main` branch that is deployed rather than just `main`. It might be nice to update the staging build to do this as well anyway, instead of always just using the `main` tag.

## Alternatives

Generate and push the `version.json` file into the `static` directory inside the docker image so that Nuxt can serve it. This might be easier and could put off having to mess with and deal with potentially complicated nginx configurations. I think I prefer this approach but want to hear from @WordPress/openverse-maintainers before committing to it.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
This concept of a "sidecar image" is new to me, interesting! Could you add some context of why it is needed/what problem it aims to solve compared to how it's done currently?

**Comment by sarayourfriend** [comment]
Sure! The "sidecar" idea is related to the way an ECS Service's task definition works. You can only route to a single exposed port for each service, but you can run multiple containers within a single service. This means, for example, you can run your "primary" service and have any number of "sidecar" containers that asist the primary one, choosing only one as the "entrypoint" to the ECS Service. In production we basically do this anyway, but with Nginx running in the same context as pm2 (which runs the Nuxt app). The "sidecar" container is just a way of replicating this in ECS that allows us to separate concerns. We could also run Nginx within the Nuxt container, but then we'd have to go through the hassle of installing Nginx in the Nuxt container rather than just using [the Nginx image](https://hub.docker.com/_/nginx). It may be easier that way, I'm not sure exactly what the trade offs would be :thinking: 

The main need right now to get the ECS deployment ready for fulltime usage, is to serve the `version.json` file. Whether this is done with Nginx or Nuxt is probably negligible.

If we decide to go with Nginx, we'll for now we can just serve the `version.json` file and pass everything else through to the Nuxt container. One way or another, eventually we'll want the Nginx, either as a sidecar or within the same container, for static files: nginx is faster at serving static files than Nuxt, and we can freeup Nuxt for actually generating HTML.

**Comment by sarayourfriend** [comment]
I decided to go with the Nuxt static file approach for now and allow it to close this issue. If we want Nginx in the future to serve static files we can revisit that, but I don't think it's necessary right now.

**Comment by krysal** [comment]
Thanks for the explanation! I agree with using Nuxt to serve the file for now if that will allow unblocking the deployment actions.
