### ISSUE TITLE
Allow configuring an API key to use for server-side Openverse API requests

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1558]
## Problem

Currently the production frontend exempts itself from the API throttling by auto-magically adding its IP address to the list of exempted IPs in our production Redis. This has several bad problems:

1. It requires managing bespoke throttling classes (see https://github.com/WordPress/openverse-api/issues/585) to enable this behavior
2. It requires bad and leaky permissions to be given to the frontend EC2 instances for it to be able to access and write to the Redis cache that it otherwise does not need access to. This creates a new potential vector for someone to attack our API.

We don't want to replicate the second part in our ECS deployment (indeed, it would be a pain in the butt!) so let's just remove this anti-pattern altogether and use API keys which are expressly designed for this purpose.

## Description

Add a new environment variable to the Nuxt app, `OPENVERSE_API_KEY` that is used for server-side API requests. Ensure that it is _only_ used for server side requests and that the key is under no circumstances leaked to the client.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
The same way they are now: anonymously throttled. Is that what you're asking?

**Comment by zackkrida** [comment]
Yes, I forgot the current allowlisting was by ip and not by hostname so doesn't apply to the frontend at all. Thanks!

**Comment by dhruvkb** [comment]
That^ was accidental, sorry.
