### ISSUE TITLE
Footer section appears cut off

### ISSUE THREAD

**Issue by javierarce** [WordPress/openverse-frontend#1583]
The footer section that suggests new sources after [a successful search](https://wordpress.org/openverse/search/image?q=cute%20dog) appears cut off.

<img width="1201" alt="Screenshot 2022-07-26 at 15 25 06" src="https://user-images.githubusercontent.com/4933/181016837-55dfcbba-ae73-43e8-a6fc-a2b75bc57dbc.png">

Tested on Chrome, Firefox, and Safari on desktop.

**Comment by zackkrida** [comment]
Ah, I see, w.org updated so that the admin bar appears on every site for non-logged-in users (it didn't previously for Openverse). Thanks for reporting this!

**Comment by ramadanomar** [comment]
I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
@ramadanomar here's some context; this has to be fixed all the way inside of a WordPress theme inside of a separate repo, here:

https://github.com/WordPress/wordpress.org/blob/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-openverse/css/openverse.css#L5

Which will also need to factor in the `--wp-global-header-height` variable now.

**Comment by ramadanomar** [comment]
> Which will also need to factor in the `--wp-global-header-height` variable now.
I tried my best to get node-sass to run on my local machine but it failed.[ The fix should be pretty simple tho, i made a PR.](https://github.com/WordPress/wordpress.org/pull/93)

**Comment by zackkrida** [comment]
Ah,I made a mistake in explaining this, I meant to say that the `var(--wp-admin--admin-bar--height)` variable also needs to be included.
