### ISSUE TITLE
Size of license definition popover is different for every license

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#1584]
## Description
The size of license definition popover changes and it depends on the content placed inside. This variation feels odd and a fixed width, like the one defined [in mockups](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Audio-Release?node-id=1109%3A26741), looks more balanced.

## Reproduction
1. Search for anything.
2. Open the filter sidebar.
3. Click on the question mark of CC BY-NC license to see its definition.
4. Now click on the question mark of CC BY-ND license.
5. Compare the popover size difference.

## Screenshots
|CC BY-NC|CC BY-ND|
|:---|:---|
|<img width="300" alt="CleanShot 2022-07-26 at 09 21 44@2x" src="https://user-images.githubusercontent.com/895819/181016136-a2e925f5-2aaf-44b3-bb4c-2bec639eb9fe.png">|<img width="310" alt="CleanShot 2022-07-26 at 09 22 07@2x" src="https://user-images.githubusercontent.com/895819/181016198-a9e2ba75-3d16-4d50-86e5-c219d81f2457.png">|

## Resolution
- [ ] 🙋 I would be interested in resolving this bug.

**Comment by ritesh-pandey** [comment]
I looked into the issue. Adding `w-60` class on `div` with `popoverRef` should fix this. But style rule for `w-60` class seems to be missing in our version of Tailwind. The next best I can use is `w-64`. This works perfectly.

Here is how it looks with `w-64`
![Screenshot from 2022-08-01 19-54-27](https://user-images.githubusercontent.com/1433681/182170010-657573ba-e838-4408-ba88-0b0b6a87c8f4.png)

**Comment by zackkrida** [comment]
@ritesh-pandey if you'd like to make a PR with that change, go for it! That looks pretty good based on the screenshot.

**Comment by ritesh-pandey** [comment]
Git pre-commit hook is failing for me with following message:

```
test/playwright/utils/navigation.ts:15:25 - error TS2307: Cannot find module '~/locales/ar.json' or its corresponding type declarations.

15 import rtlMessages from '~/locales/ar.json'
                           ~~~~~~~~~~~~~~~~~~~


Found 1 error in test/playwright/utils/navigation.ts:15

 ELIFECYCLE  Command failed with exit code 2.
husky - pre-commit hook exited with code 1 (error)
```

Is there any problem in my setup?

**Comment by zackkrida** [comment]
@ritesh-pandey that's a bug we're fixing (see https://github.com/WordPress/openverse-frontend/issues/1598).

In the meantime if you run `pnpm build` once you'll have the necessary locale files on your machine. It's a good temporary fix to the problem.
