### ISSUE TITLE
Incorrect text styles in metadata information

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#1587]
## Description
In the single result view of audio content, the metadata information shown in the Audio information section has incorrect styles. The font size is `16px` and line-height `32px`, while it should follow the [metadata item component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=1043%3A3305) definitions.

## Reproduction
1. Search for anything and see audio results.
2. Click on any audio track to see its details.
3. See the Audio information section.

## Screenshots
<img src="https://user-images.githubusercontent.com/895819/181034199-d159de74-0a6f-4ea9-b356-971857555e3a.png" width="500">

## Resolution
- [ ] 🙋 I would be interested in resolving this bug.

**Comment by ramadanomar** [comment]
🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Sounds great, thank you @ramadanomar!
