### ISSUE TITLE
Text styles in no results page are incorrect

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#1588]
## Description
Title and description texts in the no results page do not follow the styles defined in [the mockup](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Audio-Release?node-id=1479%3A20842). H1 should be `Heading 4` and the text below be `Description regular`.

## Reproduction
1. Open openverse on mobile or within the smallest breakpoint.
2. Search for "asd32asda"
3. Notice that title and description texts, above source links, are bigger than mockups.

## Screenshots
|Implementation|Design|
|:---|:---|
|<img width="270" alt="CleanShot 2022-07-26 at 14 36 56@2x" src="https://user-images.githubusercontent.com/895819/181085401-8b48c5fb-4014-4e79-8c6e-e0cd67796536.png">|<img width="270" alt="CleanShot 2022-07-26 at 14 35 21@2x" src="https://user-images.githubusercontent.com/895819/181085067-afb7899a-c315-4fe4-b894-0ea391222668.png">|

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by RudyBecker** [comment]
Working on this issue!

**Comment by RudyBecker** [comment]
My friend [kickeyhickey](https://github.com/kickeyhickey) will be creating a PR for this! Thanks!
