### ISSUE TITLE
Incorrect focus outline in audio waveform when used in row layout

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#1592]
## Description

The focus outline of the waveform does not render correctly when it's connected to the right with the play pause button in the row layout.

<img width="755" alt="Screenshot 2022-07-29 at 9 07 12 PM" src="https://user-images.githubusercontent.com/16580576/181794768-efbeb910-50e1-41ef-be68-026307f19784.png">

Notice how
- the left edge is rounded when it should not be
- the yellow bleeds out of the top-left corner
- the black bleeds out of the bottom-left corner

## Additional context

The focus outline is currently drawn using SVG `<rect>` so it's not possible to use different radii for each corner. Changing that to `<path>` would solve this but generating the paths programmatically is not trivial. 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
@dhruvkb am I understanding correctly that with the composite component work in #1297 the waveform itself would no longer have a focus ring, instead the whole audio track would?

**Comment by dhruvkb** [comment]
Yes @zackkrida that's true. Once that is implemented, we can remove all focus-related ornamentation from the component and close the issue.
