### ISSUE TITLE
`NotSupportedError: The operation is not supported` raised in audio search in blink browsers (Safari + Chrome)

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1605]
## Sentry link

https://sentry.io/share/issue/48703a876a6445429029dda4f1b4cbea/

## Description

This issue is exclusively raised on Safari. I don't have access to Safari so I can't reproduce this. Based on the breadcrumbs it appears the user just searched for `podcast` audio and then tried to play a couple files.

Marking as low because it does not affect very many people but I can't tell whether it breaks the search page. If someone on @WordPress/openverse-frontend with Safari 15 could test this that'd be great and reprioritize if it's not that severe.

**Comment by dhruvkb** [comment]
I searched for podcast audio on Safari 15. Playing/pausing and seeking all seem to be working as expected. I was unable to reproduce this error (or any error for that matter, it was all working normally).

**Comment by sarayourfriend** [comment]
Sounds good to me, thanks for testing it. It's ~1 event per day so I'm expecting it to be some strange edge case.

**Comment by zackkrida** [comment]
This problem occurs when an audio src is invalid. We need to start handling exceptions on the `.play()` audio event and, in the case of an error, figure out how to proceed. We might want to at a minimum stop the audio track, clear the active media, and flash an error message, perhaps using the new #1561 component.

**Comment by zackkrida** [comment]
There is more detail in #1680, but after adding many new Jamendo records that don't appear to support audio streaming this problem is occurring much more often, on nearly every search.

**Comment by zackkrida** [comment]
We're seeing this because of this issue:

Jamendo urls are sending out CORB errors Cross-Origin Read Blocking (CORB) blocked cross-origin response https://prod-1.storage.jamendo.com/download/track/176092/mp32 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details. which causes an unhandled exception when we try to play an audio track.

Regardless of the cause, some error handling should be implemented asap.

**Comment by sarayourfriend** [comment]
The error handling is recommended in #1600 as well.

**Comment by zackkrida** [comment]
This problem is occuring much less commonly with the fixed Jamendo URLs, but we should still add this level of error handling as a best practice and to cover all edge cases.
