### ISSUE TITLE
Update Sentry SDK to fix ReportingObserver

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1610]
## Sentry link

https://sentry.io/share/issue/e9e7e5a4046b4b90b93b7ed4543328ac/
https://sentry.io/share/issue/51442701efbf49deaa31f275aa83ff49/
https://sentry.io/share/issue/82a9b8bdba394bf6a86425acaf14134f/
https://sentry.io/share/issue/d61390890df04f9e88fd5b21dd3361db/

## Description

All our ReportingObserver errors in Sentry are missing most (all?) of the helpful information for identifying the source of the reported-on usage.

This should resolve itself if we update sentry to the latest version: https://github.com/getsentry/sentry-javascript/issues/5056

If the Nuxt module doesn't list the latest sentry version, then we may have to force it to the most recent version using the pnpm-file.cjs like we do for TypeScript.

**Comment by ramadanomar** [comment]
I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
I've assigned the issue to you @ramadanomar, thanks.
