### ISSUE TITLE
Add breadcrumb in Sentry via plugin to indicate whether the error came client or server side.

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1620]
## Problem

We currently are not really able to tell easily whether an error comes from the client or server. To fix this, we can add a breadcrumb based on `process.server` and `process.client`.

## Description

Add a new plugin to add a new `render-context` breadcrumb to Sentry. It should be either `"server"` or `"client"` depending on `process.server` and `process.client`.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by anton202** [comment]
working on it
