### ISSUE TITLE
Prettier works differently for directory and single file

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#1658]
## Description

Prettier can be run in two ways.
- `pnpm lint` which runs Prettier against the entire codebase.
- `lint-staged` which runs Prettier selectively against staged files.

Due to some reason (yet to be determined), the behaviour of Prettier is different in both cases, which means files which pass locally may fail the workflow on GitHub and those that pass the workflow on GitHub may fail locally.

## Reproduction

In a fresh install of the codebase
- Run prettier with a single file (e.g. `src/components/VSkipToContentContainer.vue`) argument.
- Run prettier with a directory (e.g. `src/`) as argument.

## Screenshots

<img width="1102" alt="Screenshot 2022-08-12 at 5 56 33 PM" src="https://user-images.githubusercontent.com/16580576/184353871-43d76808-9d14-4e6c-9732-ea51a9544d52.png">

## Additional context

This PR has been marked 'critical' as it affects developers trying to commit their code, forcing them to use workarounds.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
I tried looking into it today and got nowhere, unfortunately.

What I wonder is this: [Prettier docs](https://prettier.io/docs/en/integrating-with-linters.html#notes) say that `eslint-plugin-prettier` is not a good solution anymore, and it was useful when Prettier was very new.

I tried removing it thinking maybe it could be a quick fix, and got a lot of [vue/multiline-html-element-content-newline](https://eslint.vuejs.org/rules/multiline-html-element-content-newline.html) errors.
So, anyways, do you think we should re-think how we run prettier and eslint?

**Comment by dhruvkb** [comment]
Same @obulat. This issue seems so simple on the surface so I too ended up putting in a disproportionate amount of time without finding the cause.

While https://github.com/prettier/eslint-plugin-prettier is not recommended, I think https://github.com/prettier/eslint-config-prettier should still be used to disable ESLint rules that can conflict with Prettier's choices.

**Comment by ramadanomar** [comment]
Hey, i've been spending quite a lot of time on this issue as well. Forcing a newer version of prettier and eslint in package.json appears to fix the problem but i am not sure on how to test if other problems are created in the process.

**Comment by obulat** [comment]
I'm afraid that the solution to this issue is buried somewhere in this issue's comments: https://github.com/prettier/prettier/issues/10918 . I tried debugging the way Prettier reformats the code, and got to the Vue HTML parser changing the order of the class names, but couldn't figure out why it's doing that.

We can either remove the tailwind plugin or wait until it plays well with Vue. 

I tried updating the prettier and eslint versions, too, @ramadanomar . And I thought that the problem was fixed, until I realized that the class order in `src/components/VSkipToContentContainer.vue` was actually still incorrect :(

**Comment by ramadanomar** [comment]
Can't we just add a  `<!-- prettier-ignore --> ` tag for the moment with the mention that it produces different results on different machines?

**Comment by ramadanomar** [comment]
```
<template>
  <div ref="containerNode">
    <slot />
    <VTeleport to="skip-to-content">
      <!-- prettier-ignore -->
      <VButton
        class="ms-2 z-50 mt-2 focus:fixed focus:absolute"
        :class="$style.skipButton"
        @click="skipToContent"
        >{{ $t('skip-to-content') }}</VButton
      >
    </VTeleport>
  </div>
</template>
```
Something like this?

**Comment by obulat** [comment]
Considering that we haven't found a way of actually fixing this issue, and we have a workaround that allows us to keep committing the code, I have lowered the priority to medium. Hopefully, this will be solved in the future, but in the meantime, we can use the solution from #1673.
