### ISSUE TITLE
Improve Tailwind Documentation

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1674]
## Problem

Tailwind is a large part of the frontend developer experience and requires knowledge of a bespoke set of custom css classes.

## Description

We should improve documentation about Tailwind, by wither adding a designated Tailwind section to our CONTRIBUTING document or our README. I think this is important enough where I might prefer the later. Some suggestions for that section are:

- Link to our Tailwind config frontend https://wordpress.github.io/openverse-frontend/tailwind/
- Link to Tailwind's documentation
- Mention the css class ordering part of our linting
- Mention the official [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss)

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by ramadanomar** [comment]
#1712

**Comment by ramadanomar** [comment]
Issue was resolved by pr #1712!
