### ISSUE TITLE
Unsupported media type not handled when playing audio

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-frontend#1680]
## Sentry link

https://sentry.io/share/issue/48703a876a6445429029dda4f1b4cbea/

## Description

Error message: `NotSupportedError: The operation is not supported`

This error is being thrown for certain audio tracks when you click the Play button on the result _from the search results page._ I've been able to reproduce on Mobile Safari

## Reproduction

1. On mobile Safari, search `https://search-production.openverse.engineering/search/audio?q=transformation`
2. Click the 'play' button on the first result (for me, this was https://search-production.openverse.engineering/audio/8ac410f1-cc13-403a-b540-3c5f8c50c4a5. See screenshots below. Click the button on the search results page, rather than the clicking through to the individual result) You should see a notification that `this audio format is not supported by your browser`.
3. Now click the `play` button for the second result (for me, https://search-production.openverse.engineering/audio/f3f763b7-288b-46ac-8ffe-40424dea0197, see screenshots)

In my case I immediately saw a new Sentry error, and the page froze.

<img width="222" alt="Screen Shot 2022-08-16 at 4 33 55 PM" src="https://user-images.githubusercontent.com/63313398/185002878-8a41d21f-9273-44c7-97a0-075d369b83a4.png">

**Comment by zackkrida** [comment]
I was just noticing this as well, I think it's related to the surge of new Jamendo tracks. I can replicate in desktop Chrome. 

The first two tracks here are jamendo:

https://search-production.openverse.engineering/search/audio?q=transformation

Attempting to play one throws an error that borks _all_ audio players on the page and keeps the interacted-with track in a permanent loading state:

![CleanShot 2022-08-16 at 19 40 01@2x](https://user-images.githubusercontent.com/6351754/185003530-4ac71d50-4d25-4fca-a386-5854e993d224.jpg)

**Comment by stacimc** [comment]
In the example steps I included in the PR description, I think I noticed another bug as well: if you click play on the _third_ result in those search results, you'll see the `This audio format is not supported by your browser` message, but the track actually _does_ play.

**Comment by zackkrida** [comment]
Hm, for the third track (Robotic Transformer 4), I'm able to play it without issue if it's the first thing I press play on.

If I've already clicked play on one of the first two tracks, _all_ audio tracks are permanently hit with the `This audio format is not supported by your browser` but the third track will still play correctly.

**Comment by stacimc** [comment]
Ah, not reading closely enough -- I think you're right!

**Comment by stacimc** [comment]
I'm going to close this one as a duplicate of the original issue https://github.com/WordPress/openverse-frontend/issues/1605, which I unfortunately did not notice.
