### ISSUE TITLE
Copy improvements in the search flow

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#1701]
## Problem
While reviewing the current search flow, I noticed that is not very clear what is the search engine for and how to interact and use the content found. We can make significant improvements by tweaking some copy areas and make Openverse more precise and consistent.

Starting from the homepage, the terms “items” and “reuse” do not explain themselves in the context of having Openverse in the WordPress site with other CMS-related content. We can improve this by being more transparent about what Openverse displays and what visitors can do with the content they find.

On the other hand, the single result view has an inconsistent experience depending on where you land. In the image details view, main action opens the image from a “Go to image’s website” button, but in audio details, it shows “Download" even when you can not download it directly. 

For the latter, we have discussed it before, and our main concerns surround the traffic aspect of redirecting visitors. But a small tweak in the button label can improve the experience significantly.

### Issues related
* #1341 
* #1690  

## Proposal
|Homepage|Single result|
|:---|:---|
|![Home](https://user-images.githubusercontent.com/895819/188505220-74453837-ef98-4650-bf42-fb9f7f5e27fd.png)|![Single result](https://user-images.githubusercontent.com/895819/187240260-e16c12aa-8bef-4c52-b92b-d879fd64734b.png)|

### Homepage
In this page, I am replacing the description below Openverse logo to be “Discover more than 600 million media to use” and aligning it to the left with the rest of the content. At the same time, making the font-size `46px`, the line height `60px` , and shifting to a regular font weight to reduce its boldness. This text style is new but not sure about adding it as a variant since it will be used for this page only.
- [x] #1756

### Single result
For the single result view, I simplified the CTA button by replacing its label with “Get this `content-type`” and adding an external icon to be explicit on what will happen when clicking on it. Even when you do not download the content from here, it indicates the flow and final action.
- [x] #1741

On the other hand, the "Reuse content" title changes to "How to use" and a description paragraph is added below to give more context about how to give attribution.
- [x] #1757

## Mockups
* Figma: [Copy improvements in the search flow](https://www.figma.com/file/ClEKESZzZxudMoHbHq3A66/Copy-improvements-in-the-search-flow?node-id=0%3A1)
* Presentation: [Slides](https://www.figma.com/proto/ClEKESZzZxudMoHbHq3A66/Copy-improvements-in-the-search-flow?page-id=26%3A13657&node-id=427%3A9251&viewport=461%2C537%2C0.3&scaling=min-zoom&starting-point-node-id=427%3A9251)

---

What do you think of these changes? I am not good with copy so I would love some help on area.

**Comment by dhruvkb** [comment]
## Homepage

The use of Discover over Browse is good. I would, however, refrain from mentioning media types like this because it can get cumbersome as more media types are added. Also the line break "600 million images" / "and audio" makes it seem like (600M images) + (audio). I feel like "openly-licensed works" or "creations" would be better instead of "images and audio".

## Single result

The addition of the "How to use" section is good. I think we should explore some approach for combining it with the existing "License" and "Credit the creator" sections. For example, when we say "Make sure to credit the creator by showing the attribution information", it isn't exactly clear that by attribution we mean the content in the bottom-right tab-pane. Also this unduly emphasises the BY portion of the licenses and reduces the prominence of other conditions like ND, NC, and SA.

**Comment by sarayourfriend** [comment]
> I feel like "openly-licensed works" or "creations" would be better instead of "images and audio".

Additional benefit here is not having to change that when we eventually introduce additional types of media.

> Also this unduly emphasises the BY portion of the licenses and reduces the prominence of other conditions like ND, NC, and SA.

+1

**Comment by panchovm** [comment]
Good points @dhruvkb

I wonder if we can find a single term that includes all content types. I agree that "image and audio" has a short lifespan when we add more types, but naming all content types also becomes problematic in the long run due to its extension. The main point of this proposal is to be straightforward on a page where we introduce Openverse value.

I would like to work on redesigning the attribution flow. There is room for steering visitors on what is and how to give attribution, plus showing the next steps in source sites where they need to create an account for downloading the content. Nonetheless, this description tweak is clearer than not having it on how to use the content.

Fully agree with your approach, but I am afraid it will require more time and delay the copy enhancement.

**Comment by DanSoschin** [comment]
"media" is a catch-all term that might encompass both images, audio, and potentially other things down the road.

I'd also recommend using "more than" versus "over". 

Generally speaking, I do agree that we could enhance the copy on the home page and about page to provide some additional descriptions, explanations, features, benefits, etc. I'd be happy to assist.

**Comment by panchovm** [comment]
"Media" and "more than" sound like a good idea. I will try both.

> I do agree that we could enhance the copy on the home page and about page to provide some additional descriptions, explanations, features, benefits, etc. I'd be happy to assist.

Thanks for the help. Please drop your thoughts here and I can bring up a new version. This issue is for design iteration ❤️

**Comment by zackkrida** [comment]
"Get this [media]" was recently proposed as a unified piece of copy for the primary CTA on single results. There's a PR for this now: https://github.com/WordPress/openverse-frontend/pull/1741

**Comment by obulat** [comment]
I love the changes that make the site language simpler!
I think "Discover over 600 million images and audio to use" shouldn't have a period in the end, @panchovm?

It would be nice to have a better link between the sentence in "How to use" that reminds to credit the creator, and the "Credit the creator" tabs, making it clear that users can copy the already-available attribution sentence.

**Comment by panchovm** [comment]
You are right about the period @obulat and that reminds me I forgot to attach the home's last version.

> Better link between the sentence in "How to use" that reminds to credit the creator, and the "Credit the creator" tabs, making it clear that users can copy the already-available attribution sentence.+

I think we can address this attribution flow with a redesign initiative. It goes beyond the copy, and there is room for improving the flow by showing a more straightforward design.

---

## Home

![Home](https://user-images.githubusercontent.com/895819/187239334-242939dd-f4ae-4e7f-83ff-102b965b8bdd.png)

**Comment by obulat** [comment]
@panchovm, I've created the issues for "How to use" section and for the Homepage descriptive text, and added the links to them here. We can use this issue to track the overall progress.

**Comment by panchovm** [comment]
Thanks a lot @obulat that was very smart ❤️ 

I updated the mockups in [this comment](https://github.com/WordPress/openverse-frontend/issues/1701#issuecomment-1230490187) and [the initial post](https://github.com/WordPress/openverse-frontend/issues/1701#issue-1343626099) so now all texts are correct.

**Comment by AetherUnbound** [comment]
This is a great thing to address! It's a small change that could have a big impact. I like the idea of using something like "creative works" rather than "media" (even though that isn't one word). **Discover more than 600 million creative works to use** or even **Discover more than 600 million creative works available for use** sound a little bit better to me than "media".

**Comment by zackkrida** [comment]
I apologize for adding to confusion, I have been thinking through ideas for this homepage copy on the specific homepage issue (where I also mention the phrase 'creative works' so ➕ there)

https://github.com/WordPress/openverse-frontend/issues/1756

**Comment by panchovm** [comment]
Closing this issue as all related work is done and merged. Great work folks ✨
