### ISSUE TITLE
`Object Not Found Matching Id` unhandled error

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-frontend#1702]
## Sentry link

https://sentry.io/share/issue/30550627d9004513ae496fa41e81774d/

## Description

We've gotten ~700 of these over the last seven months:
```
UnhandledRejection
Non-Error promise rejection captured with value: Object Not Found Matching Id:1
```
(for varying values of 'id'). It appears to be happening for the most part on single image result pages, but there is no further information.

All events are on Chrome on Windows 10.

This is either intermittent or just rare, and has been ignored or resolved due to activity and reopened multiple times.

## Reproduction

Could not reproduce.

**Comment by vj27111997** [comment]
hey @stacimc  I want to work into this issue will I go ahead with this

**Comment by zackkrida** [comment]
Sure, thanks @vj27111997! Feel free to ping `@WordPress/openverse-frontend` if you need anything.

**Comment by vj27111997** [comment]
hey @zackkrida  please reassign me this issue due my mistake i wrongly pressed unassigned I would request you to please reassign me

**Comment by zackkrida** [comment]
Closing as this hasn't been observed for several months.
