### ISSUE TITLE
[Bug] ResizeObserver not available for Waveform on SSR

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#171]
## Description

The `Waveform.vue` component cannot be rendered on the server because it requires `ResizeObserver`, which is only available in the browser, not in node.

## Reproduction

1. Checkout `single_audio` branch
2. Run `npm run dev`
3. Open `http://localhost:8443/audios/242c1a4c-0623-436c-a600-7847412d28b6` page in your browser.
4. See error:
```
 ERROR  [Vue warn]: Error in data(): "ReferenceError: ResizeObserver is not defined"                                                                             
found in

---> <Waveform> at src/components/AudioTrack/Waveform.vue
       <AudioTrack> at src/components/AudioTrack/AudioTrack.vue
```

## Expectation

Waveform should load both with SSR, and with CSR.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
^ Initialising the ResizeObserver inside the `onMounted` hook seems to fix the issue.
