### ISSUE TITLE
Some images don't have "Related images" but the header for the section is still displayed

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-frontend#1719]
## Problem

One of our current featured images (the one shown on the homepage) appear to have no related images after some modifications in the API endpoint (WordPress/openverse-api#865). This is likely happening with more images, so will be better to hide the header when the section is empty.

The details page of this featured image:
https://search-production.openverse.engineering/image/648b566f-0228-4819-83d5-8f1d324ec06d

![Screenshot 2022-08-22 at 15-06-24 File The victorious English 400 m  women's relay swimming team at Wellcome V0048555 Openverse](https://user-images.githubusercontent.com/9145885/185999966-e14df6ed-477f-415d-8a99-6bd4193d9db7.png)

## Alternatives

This is open to alternatives while is reworked on the API.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Just to confirm, there are definitely no related images returned by the API endpoint, interesting:

https://api.openverse.engineering/v1/images/648b566f-0228-4819-83d5-8f1d324ec06d/related/

**Comment by obulat** [comment]
I wonder if it's cache related. Checking now, I can see both the frontend and the API results for this link.

**Comment by zackkrida** [comment]
Ah very strange, I can now as well. I don't think it's the cache though, because I've been testing this by appending unique query strings. Something else may be going on in the API 🤔

**Comment by dhruvkb** [comment]
In any case, given that there is a possibility that we might have images that are unrelated to anything else, we should add the check to not show the heading unless there is content to go below it.

**Comment by shreyanshmalvya** [comment]
Just visited the link given in the issue, but it shows Related Images to me.

![image](https://user-images.githubusercontent.com/80682098/186599814-1f98fc85-3eb8-43bf-af41-58802f2d669b.png)

**Comment by krysal** [comment]
@shreyanshmalvya Yes, it was something that happened for a few moments, we need to find out why does that happen but also to hide the section when there is no related images available.

**Comment by shreyanshmalvya** [comment]
@krysal Yes, I am, I even checked out the code to find any errors.

**Comment by dhruvkb** [comment]
@0kyn, it's been 2 months since @shreyanshmalvya commented. Feel free to take this up.
