### ISSUE TITLE
Frontend Memory Leak

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1722]
Somewhere in our Nuxt application is a memory leak that grows dramatically in correlation with traffic. This can be observed in production but also locally by taking a heap snapshot before and after simulating heavy traffic with a tool like `ab`, `swarm`, or other load testing tools.

**Comment by obulat** [comment]
The main suspect for the memory leak is the `use-fetch-state` composable, which seems to retain the memory in the computeds. We decided to refactor the stores to simplify the fetch state properties.

**Comment by obulat** [comment]
Closing this issue after #1747 (see the memory profiling data in the comment https://github.com/WordPress/openverse-frontend/pull/1747#pullrequestreview-1087355085).  We can always reopen if new leaks are discovered.
