### ISSUE TITLE
Test in `e2e/mobile-menu-spec.ts` is flaky

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#1737]
## Description

The following test case appears to be flaky:

```
e2e/mobile-menu.spec.ts:20:1 › Can open filters menu on mobile at least twice
```

## Occurrences

In both occurrences, the test passed in attempt no. 2.

- https://github.com/WordPress/openverse-frontend/actions/runs/2927043708/attempts/1
- https://github.com/WordPress/openverse-frontend/actions/runs/2921645603/attempts/1

## Environment

Since both the failing and passing occurrences are from the same CI environment, the flakiness is not environment-specific.

**Comment by ramadanomar** [comment]
This appears to have been fixed by #1751 👍🏻
