### ISSUE TITLE
Standardize z-index layers by importing the tailwind config in JS/TS files

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1742]
## Problem

We currently use bespoke z-indices in a few places, or manually specify our z-index scale to validate props in a few different files.

## Description

Instead, we should import our tailwind config with something like this:

```js
import resolveConfig from 'tailwindcss/resolveConfig'
import tailwindConfig from './tailwind.config.js'

const myconfig = resolveConfig(tailwindConfig)
```

That would allow us to access the list of valid z indices.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
Waiting on #1686.

**Comment by obulat** [comment]
#1686 has been merged, so it's unblocked now, @dhruvkb .
I just found a note about importing from config on the Tailwind docs[^1]:
> Note that this will transitively pull in a lot of our build-time dependencies, resulting in bigger bundle client-side size. To avoid this, we recommend using a tool like [babel-plugin-preval](https://github.com/kentcdodds/babel-plugin-preval) to generate a static version of your configuration at build-time.

[^1]: https://tailwindcss.com/docs/configuration#referencing-in-java-script
