### ISSUE TITLE
Filter sidebar is empty and frontend is broken on search endpoint SSR loads 

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1748]
## Description

When making a server-side rendered visit to any of the `/search/` endpoints of the frontend, the page is completely broken, if the filter sidebar was opened on a previous client-side visit. 

This was fixed by rendering the sidebar client-side only in #1749 and pushed in https://github.com/WordPress/openverse-frontend/releases/tag/v3.4.6. We'll want to remove the `<ClientOnly>` component and fix this to remove the slight layout shift introduced by the hotfix.

## Reproduction

> **Note**
> This can only be reproduced locally in the built application with `pnpm build` and `pnpm start`. It is not observable using `pnpm dev`.

1. Remove `<ClientOnly>` around the sidebar
1. Visit https://search-staging.openverse.engineering and submit a search
2. Open the filter sidebar
3. Refresh the page
4. Observe the site is broken
5. Repeat steps 1-4 but _close_ the filter sidebar, and observe the site works correctly on the SSR loads.

## Screenshots

![CleanShot 2022-08-26 at 15 51 13@2x](https://user-images.githubusercontent.com/6351754/186980908-57d37546-d18f-473e-9fd7-c1ba8a1db82a.png)

**Comment by dhruvkb** [comment]
Reassigning to @obulat because she has already the fix.
