### ISSUE TITLE
Update Playwright to version ^1.25.0

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1754]
## Problem

#1646 updated Playwright version to 1.24. However, the update to the most recent version, 1.25, was impossible due to some problems in rendering Arabic fonts.

## Description

We need to investigate what changed in Playwright version 1.25 that caused the RTL rendering problems. Here is an example snapshot of the wrong Arabic version. Notice the `NUL` signs:

![image](https://user-images.githubusercontent.com/15233243/186696445-803f4295-df2c-4cd4-9653-2cf0594bb972.png)

## Additional context

This could be to some regression in Chromium that is bundled with Playwright Docker image.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Interesting, this is using our custom webfonts so I wouldn't expect a character rendering issue to be associated with a browser release like this. I wonder if we can:

- Identify the character that isn't rendering
- Check if it works locally/in a browser
- Identify why it would no longer work in Playwright

**Comment by obulat** [comment]
The Arabic letters in the 1.25 snapshots seemed to be more squished into each other, for what it's worth. The letters were the same, mostly.
