### ISSUE TITLE
Update the homepage description

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1756]
## Description

The description below the Openverse logo on the homepage needs to be updated.

The new text is "Discover more than 600 million media to use", and the styles are as follows:
All fonts are Inter, style Regular.
### Desktop
**Subtitle**
Font size: 46px
Line height: 60px
Line height: 130%
Margin-bottom: 16px

**Description**
Font size: 27px
Line height: 35px
Line height: 130%
Margin-bottom: 24px

### Mobile
**Subtitle**
Font size: 19px
Line height: 25px
Line height: 130%
Margin-bottom: 24px

**Description**
Font size: 14px
Line height: 22px
Line height: 160%
Margin-bottom: 32px

## Screenshots
 
<img width="619" alt="Screen Shot 2022-09-06 at 7 26 01 PM" src="https://user-images.githubusercontent.com/15233243/188687452-1e82c12a-c26d-472c-a350-76d17c6bfd49.png">

## Mockups
* Figma: [Copy improvements in the search flow](https://www.figma.com/file/ClEKESZzZxudMoHbHq3A66/Copy-improvements-in-the-search-flow?node-id=0%3A1)
* Presentation: [Slides](https://www.figma.com/proto/ClEKESZzZxudMoHbHq3A66/Copy-improvements-in-the-search-flow?page-id=26%3A13657&node-id=427%3A9251&viewport=461%2C537%2C0.3&scaling=min-zoom&starting-point-node-id=427%3A9251)

**Comment by zackkrida** [comment]
'discover' is definitely better than 'browse' but I feel like this still needs some more discussion. I'm nervous about removing 'image' and 'audio' directly as they're important keywords from an SEO perspective. 

In general, I think we need a bit more copy on the homepage, like another sentence below this one with a different fontsize.

I'll share some ideas in a bit!

**Comment by zackkrida** [comment]
This is far from perfect but I want to quickly propose adding a second block of text, something like this:

![CleanShot 2022-08-31 at 14 56 53@2x](https://user-images.githubusercontent.com/6351754/187760387-1b9886f7-9eef-433f-b235-f66de531c869.png)

```
# Discover and use Creative Commons media
## Over 500 million free stock photos, images, songs, and audio files.
```

**Comment by zackkrida** [comment]
Maybe "creative works" could be a better term than "media"?

**Comment by panchovm** [comment]
We should not reduce Openverse visibility due to SEO, definitely. I am not sure about adding Creative Commons words in the main call as it might not be clear to all users. We are already mentioning CC by linking it with the licenses, making the relationship clearer.

In any case, I will share it with [Dan Soschin](https://github.com/DanSoschin) as he was interested in helping us. I would not like to convert this into a redesign as the copy is a quick win, and we have a different issue (#1433) for revamping up the homepage once we start moving openverse out of the WordPress site.

**Comment by DanSoschin** [comment]
Here are some of my thoughts for additional consideration...

- I agree with Zack that "creative works" fits better than "media". Media has an odd-sounding conjugation in English; and in this case, it doesn't seem to flow/sound right for our intended goal.
- Another option for the main heading could be something like: "Explore more than 600 million creative works"
- A sub-header along the lines of  "An extensive library of free stock photos, images, and audio, available for free use."
- I think one of the primary keywords here is "free stock photos"... this likely has a very high search volume, so we take advantage of that here. You could swap "extensive" with "searchable"
- This fixes the issue of "media" and adds in more context via a sub-heading with some SEO...

**Comment by zackkrida** [comment]
That's great, thanks @DanSoschin! I really agree a subheader is necessary here, hopefully we can find a way to add one without going into 'redesign' territory as @panchovm mentioned. I mocked up your suggestions, I like it!

![CleanShot 2022-09-02 at 12 52 50@2x](https://user-images.githubusercontent.com/6351754/188202065-74a1201c-3692-4b94-ad37-a128b122e3d2.png)

**Comment by panchovm** [comment]
Here is a design idea for desktop and mobile. It has the same content shared by @zackkrida's version but with style tweaks.

## Desktop
![Home 03 desktop](https://user-images.githubusercontent.com/895819/188480129-81aa2087-a8e8-4c4e-bf78-f5af050b7ef3.png)

## Mobile
<img src="https://user-images.githubusercontent.com/895819/188480408-2bffa5c7-6bbd-42d1-908a-2879c5f84544.png" width="350">

**Comment by panchovm** [comment]
I will update the design issue and Figma file
