### ISSUE TITLE
Update the wording in Reuse content (How to use) section

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1757]
## Description

We need to replace "Reuse content" title with "How to use" and add a descriptive paragraph to give more context about how to give attribution.

### Desktop (image)

<img width="610" alt="Screen Shot 2022-08-30 at 9 10 55 AM" src="https://user-images.githubusercontent.com/15233243/187362821-86f4b618-7672-456a-83fa-77ae051d3468.png">

### Mobile (image)
<img width="231" alt="Screen Shot 2022-08-30 at 9 11 10 AM" src="https://user-images.githubusercontent.com/15233243/187362805-96e8f7a3-72b3-41e0-9518-6902e014db19.png">

### The image description text:
Visit the image’s website to download and use it. Make sure to credit the creator by showing the attribution information where you are sharing your work.

### The audio description text:
Visit the audio’s website to download and use it. Make sure to credit the creator by showing the attribution information where you are sharing your work.

## Mockups
Presentation: [page 7](https://www.figma.com/proto/ClEKESZzZxudMoHbHq3A66/Copy-improvements-in-the-search-flow?page-id=26%3A13657&node-id=435%3A4760&viewport=461%2C537%2C0.3&scaling=min-zoom&starting-point-node-id=427%3A9251)
Figma: [desktop](https://www.figma.com/file/ClEKESZzZxudMoHbHq3A66/Copy-improvements-in-the-search-flow?node-id=418%3A5722) and [mobile](https://www.figma.com/file/ClEKESZzZxudMoHbHq3A66/Copy-improvements-in-the-search-flow?node-id=418%3A3288)

@panchovm: Please note that Grammarly proposed to remove the second `to` from this sentence:
Visit the image’s website to download and ~~to~~ use it.

**Comment by ramadanomar** [comment]
A quick question, does this issue contain all of the changes in the copy/text? I think one PR would suffice to include most of the changes (ex. from use this image to Get this image with an icon ) etc.

I'll have a PR ready by today's slack meeting

**Comment by obulat** [comment]
We try to create small PRs that are easy to test and review, @ramadanomar, whenever possible.
The changes to the 'Get this <media>' are already done in a separate PR, so this issue is specifically about the "How to use" section.

**Comment by panchovm** [comment]
Grammarly suggestion is correct @obulat, let's go with what you described.
