### ISSUE TITLE
The link to report at the source is incorrectly linking to the direct URL

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1784]
## Description

After submitting a report for an item on Openverse, the user is encourage to submit the same report at the source of the media item. The link should be to the `foreign_landing_url` of the image which has the "Report it" button, not the direct URL (that opens the original image).

## Screenshots

<img width="436" alt="Screen Shot 2022-09-05 at 4 22 24 PM" src="https://user-images.githubusercontent.com/15233243/188460269-d9471bab-bb02-403d-b111-9396ce3fa7d6.png">

## Additional context

This line should have `media.foreign_landing_url` instead of `media.url`:
https://github.com/WordPress/openverse-frontend/blob/bf0c72e5ea660354e20ffa33a4caf0abd65a5db9/src/components/VContentReport/VContentReportForm.vue#L13

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by chandu-jadhav** [comment]
hey can I work on this issue?

**Comment by zackkrida** [comment]
That would be great, @chandu-jadhav! thank you.

**Comment by SincerelyBrittany** [comment]
I am also interested in working on this issue. Let me know if anything pops up. :)

**Comment by obulat** [comment]
Thank you for opening your PR, SincerelyBrittany. Please note that it is expected that we give the person who expressed interest in an issue (@chandu-jadhav) about a week to come up with a PR before transferring the issue to someone else.

@chandu-jadhav, I am sorry that you didn't get the chance to open a PR for this issue. Please, look at other '[good first issue](https://github.com/WordPress/openverse-frontend/labels/good%20first%20issue)' or '[help wanted](https://github.com/WordPress/openverse-frontend/labels/help%20wanted)' issues to see where else you could contribute.
