### ISSUE TITLE
Add a disabled style to three components

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#1798]
## Problem
As noted in tickets #1791 and #1790, some components need a "disabled" state to deny the use of some features, but the current Design Library does not have styles for the Content switcher and Filters components.

## Description
To make this state visually consistent with other components, the Design Library was updated with a new variant in each Figma component mentioned. Here is the style for each one

### Content switcher
<img src="https://user-images.githubusercontent.com/895819/189162406-3ce5b185-96bd-4233-8509-4536691018f2.png" width="350">

### Filters
<img src="https://user-images.githubusercontent.com/895819/189162426-1a831326-f33b-43f9-acbe-389ea5455805.png" width="170">

### Filters value
<img src="https://user-images.githubusercontent.com/895819/189162452-f7763fa2-b9e2-4f1d-8d25-1eb6af6827cd.png" width="250">

In all components, the style has `dark-charcoal-10` as the background color, and `dark-charcoal-40` for texts and icons.

### Pointer update

As also noted and developed in #1790 it would be great to implement a style change in the pointer for all current and upcoming components, like the example below.

<img src="https://user-images.githubusercontent.com/895819/188936368-b229349a-b8cf-4176-80e9-21fe154ee44c.png" width="150">

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sourav25998** [comment]
Hi @dhruvkb . I would like to work on this issue. Please assign this to me.

**Comment by dhruvkb** [comment]
Sure @sourav25998. Please go ahead.

**Comment by sourav25998** [comment]
Hi @dhruvkb . I'll be continuing with my issue that has been assigned to me in openverse-api at the moment. I shall come back to frontend once I am done with that issue. Thus, I am unassigning myself from this issue right now. Hope you understand

**Comment by vinzesiddharth29** [comment]
Hi @dhruvkb , 
It seems @sourav25998 is continuing with another issue, so I would like to work on this instead.
This issue is likely to be a good start of my journey towards contribution to FOSS projects.
Please assign this to me.

**Comment by obulat** [comment]
I've self-assigned this issue because it's been a while, and it's marked as high priority. If you are interested in contributing, @vinzesiddharth29, please feel free to select another issue, and to reach out to the maintainers on the public Slack channel.
