### ISSUE TITLE
Openverse footer

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#1811]
## Description
Since we plan to move Openverse out from the WordPress.org site and implement the new header (#1669), we need to allow visitors to see the internal pages, mark the search as a WordPress project, and add the language selector in the future.

In that vein, the footer has two contexts:
* **Footer content:** To be used in results and single content details. Internal pages are always present
* **Footer internal:** To be used in content pages where the internal pages move to the header.

The design includes a new component for shifting language. Since this idea has not been discussed nor defined with a milestone, we do not need to create the element but take into account its space.

And finally, I added a new version for smaller devices called `< sm` as `sm` breakpoint starts from `640px` and leaves out other mobile use cases.

### Footer content
![imagen](https://user-images.githubusercontent.com/895819/190179012-b97198b7-ad6e-4e1e-aa6d-a9c4a0e7030e.png)

### Footer internal
![imagen](https://user-images.githubusercontent.com/895819/190179214-7d80db94-f1af-4fcd-bf2a-3969468adc88.png)

---

### Figma file
The footer is already available in the "[Upcoming components: Footer](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=3018%3A7629)" page in the Design Library. This name is due to the pending design documentation. While the uses are in the [New header component](https://www.figma.com/file/KxkZmBNk218V2Fke1GeYCu/New-header-component?node-id=0%3A1) file since header and footer depend on each other.

- **Figma:** [Footer component in Design Library](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=3018%3A7629)
- **Figma:** [Applications in New header component](https://www.figma.com/file/KxkZmBNk218V2Fke1GeYCu/New-header-component?node-id=424%3A56729)

## Implementation

- [ ] 🙋 I would be interested in implementing this component.

**Comment by dhruvkb** [comment]
Linked to #1809.
