### ISSUE TITLE
Disable component auto-injection for duplicated named header components

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1830]
## Problem

We currently get a ton of errors during build:

```
 WARN  Two component files resolving to the same name VSearchBar:                                                                        19:36:21

 - /home/sara/projects/openverse-frontend/src/components/VHeaderOld/VSearchBar/VSearchBar.vue
 - /home/sara/projects/openverse-frontend/src/components/VHeader/VSearchBar/VSearchBar.vue


 WARN  Two component files resolving to the same name VSearchButton:                                                                     19:36:21

 - /home/sara/projects/openverse-frontend/src/components/VHeaderOld/VSearchBar/VSearchButton.vue
 - /home/sara/projects/openverse-frontend/src/components/VHeader/VSearchBar/VSearchButton.vue
```

## Description

Let's disable component auto-injection for these components or better yet just disable it altogether.

## Additional context
Marked high because it could theoretically cause a probably hard-to-debug issue if auto-injection was used by accident.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
I was hoping to remove the old unused components in that list by fixing #1836. The PR fixing that issue will remove most of the popover/modal components because we no longer need them, and the buttons will be used only either on mobile screens or on desktop screens. Then we could just rename anything that's left.
