### ISSUE TITLE
Update background color for the search bar

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#1879]
## Description

The [new header search bar](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8z/Openverse-Design-Library?node-id=2960%3A8190) is darker when not focused and becomes white when focused to type. This is the opposite of the current design and must be updated.
![Header content](https://user-images.githubusercontent.com/16580576/193615971-f28e0073-a577-46b5-adce-5e8ff4f54cad.png)

**Comment by obulat** [comment]
We also need to add the Clear button to the desktop search bar.
