### ISSUE TITLE
[Feature] Waveform keyboard seek to start/end

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#190]
## Problem
Some keyboard navigable audio/video seek bars are able to be jumped to the start or end of the audio by using `cmd/super + left/right` or `home/end`. We don't currently implement this. 

## Description
Add the ability to seek to the start or end of the audio using the keyboard either through `meta + left/right` or `home/end`

## Additional context
I got this idea checking out this other media player's implementation: https://github.com/IET-OU/mediaelement/commit/25eb64a2097f25bffd5c1420807f5605cbe4e0b0#diff-219f920a90e9fec6455e5cb6863cf6e51831182cd586184b53e5ae3a4e94b32aR102-R108

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
I see the value of being able to seek-to-start so as to replay a song. But since we don't have a playlist feature, I'm interested to know how the seek-to-end would be different from just pausing the track.
