### ISSUE TITLE
[Bug] Play/pause button needs rounded corners

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#191]
## Description
The play/pause button current has square corners, but should be updated to match the design and have rounded corners: https://www.figma.com/file/vEoItpMQyFZb5AZV9aoP7I/Audio-integration?node-id=1107%3A12561

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
What is a "UA style"?

**Comment by sarayourfriend** [comment]
User Agent style. I'll update the issue to remove the abbreviation, sorry!

**Comment by sarayourfriend** [comment]
Wait, I just looked at the figma designs again and noticed that the play/pause button actually does have rounded corners now 🙂 I think we can update this issue to be to add the rounded corners to always show on the play/pause button!

from: https://www.figma.com/file/vEoItpMQyFZb5AZV9aoP7I/Audio-integration?node-id=1107%3A12561

<img width="363" alt="Captura de Tela 2021-09-06 às 10 42 09" src="https://user-images.githubusercontent.com/24264157/132249867-c6ade2c6-373f-48fa-a068-473f15084aea.png">
