### ISSUE TITLE
Add top bar for former CC Search users

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#194]
Anyone visiting wordpress.org/openverse from a domain containing `creativecommons.org` should see a special banner at the top of the site. This is intended so that CC Search users aren't confused when they are redirected to Openverse, and so we can control the narrative about what a positive change for the project this is.

## Mockup

<img width="872" alt="CleanShot 2021-09-06 at 21 26 26@2x" src="https://user-images.githubusercontent.com/6351754/132270648-036a8a50-6078-4d60-923d-c4a723609465.png">

> Figma link: https://www.figma.com/file/BlUTIXRHLOq5mRITpDpi3E/Transitional-styles?node-id=418%3A2025

Please only show if the referrer is from a `creativecommons.org` domain. And make sure to localize the text. Link should go to https://wordpress.org/news/2021/05/welcome-to-openverse/

**Comment by dhruvkb** [comment]
@panchovm I have a few questions about this bar.

- Should this bar be dismissable, for example, with an X icon?
- Will this be shown again to the same user if they follow the redirect again?

**Comment by dhruvkb** [comment]
@zackkrida what approach will CC be employing to perform the redirect? It's very likely that the referrer will be empty unless the user reaches the page by clicking a link. All approaches like 301/302 redirects, JavaScript `window.location` are leading to the referrer being blank.

**Comment by zackkrida** [comment]
Typically a 301 preserves the referer, but I suppose we could also have them add a query parameter or other more reliable method of showing the banner!

**Comment by dhruvkb** [comment]
Even if 301 would preserve the referrer, wouldn't that point to the domain that sent them to CC Search then, and not the CC Search domain itself? Query param would be awesome 👍 if they can do that. Our theme anyways has the path forwarding set up so it'll reach the Vue `iframe` automatically.

**Comment by zackkrida** [comment]
OH duh. This whole time I've been conflating the original referrer _to_ search.creativecommons.org with search.creativecommons.org itself. We will _definitely_ have them add a query param, thank you!

**Comment by panchovm** [comment]
Arriving late here, but coming to say that we talked about having the message for a period of time (TBD).
