### ISSUE TITLE
`VInputFieldOld` component naming consistency

### ISSUE THREAD

**Issue by 0kyn** [WordPress/openverse-frontend#1948]
## Description
The `VInputFieldOld` component is currently named  as [VInputField](https://github.com/WordPress/openverse-frontend/blob/a8742ebaabb2c192cfe35ca704085f9939a95356/src/components/VInputFieldOld/VInputFieldOld.vue#L46), whereas others `V[...]Old` component are named with the _Old_ suffix. 

## Screenshots
I noticed this while inspecting components

![Capture d’écran 2022-10-30 à 12 36 36](https://user-images.githubusercontent.com/29523399/198876463-69d8283d-ef3a-4e98-8972-8a00a1c3153d.png)

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
I don't think this is a bug. The 'Old' suffix is only used for components which have a different design in the new UI and new component `.vue` files. 

The design of `VInputField` hasn't changed so there aren't two different `VInputField` components, both old and new components use the same `VInputField`.

**Comment by 0kyn** [comment]
Hi @dhruvkb,

I worded it wrong, `VSearchBarOld` component uses `VInputFieldOld` from `'~/components/VInputFieldOld/VInputFieldOld.vue'`. [import](https://github.com/WordPress/openverse-frontend/blob/a8742ebaabb2c192cfe35ca704085f9939a95356/src/components/VHeaderOld/VSearchBar/VSearchBarOld.vue#L37-L39)

But `VInputFieldOld` component name is currently defined as 'VInputField' instead of 'VInputFieldOld' to avoid confusion. [component definition](https://github.com/WordPress/openverse-frontend/blob/a8742ebaabb2c192cfe35ca704085f9939a95356/src/components/VInputFieldOld/VInputFieldOld.vue#L46)

I'm unsure to word it better this time, I probably misunderstood something else. 😅

**Comment by dhruvkb** [comment]
Thanks for clarifying @0kyn and sorry about my inaccurate comment. Could you open a PR to fix this?
