### ISSUE TITLE
`screen at breakpoint sm with width 640 › filters are updated when media type changes` is flaky

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1963]
## Description

See this run for flaky test: https://github.com/WordPress/openverse-frontend/actions/runs/3420250078/jobs/5694859665

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
Yes, this issue seems to be fixed. We can re-open it if it starts showing up again
