### ISSUE TITLE
Replace the border color in the LanguageSelect

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1970]
## Problem

The language select uses the shade scale instead of the opacity scale of the dark charcoal colors.

## Description

The `VSelectField` border should be dark charcoal with 20% opacity. This allows us to simplify the code because both variants (yellow and not yellow) have the same border color.

https://github.com/WordPress/openverse-frontend/blob/5dacba4a40907885aed2b25678ec140736c9f159/src/components/VSelectField/VSelectField.vue#L5

This line can be removed, and replaced with `border-dark-charcoal border-opacity-20`.

## Additional context

For more context and screenshots, look at the comments here: https://github.com/WordPress/openverse-frontend/pull/1936#issuecomment-1313861604

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by Mayank-Jain-1** [comment]
Can i work on the issue?

**Comment by obulat** [comment]
Sure, @Mayank-Jain-1! I'm assigning the issue to you.

**Comment by Mayank-Jain-1** [comment]
I think, as after the change the class would not be changing it should be removed from ```:class``` and should be added to the ```class```
- In ```:class```
```javascript 
<div
    class="relative m-0.5px box-content block w-fit overflow-hidden rounded-sm border text-sm focus-within:m-0 focus-within:border-1.5 focus-within:border-pink hover:border-dark-charcoal focus-within:hover:border-pink"
    :class="
      'border-dark-charcoal border-opacity-20'
    "
>
```
- In ```class```
```javascript
<div
    class="relative m-0.5px box-content block w-fit overflow-hidden rounded-sm border text-sm focus-within:m-0 focus-within:border-1.5 focus-within:border-pink hover:border-dark-charcoal focus-within:hover:border-pink border-dark-charcoal border-opacity-20"
  >
```

**Comment by Mayank-Jain-1** [comment]
Can you please review these pull requests and update me?
