### ISSUE TITLE
Only install pre-commit if it isn't already downloaded

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1971]
## Description

Right now every `pnpm install` invocation will re-install pre-commit. This adds some time to the installation and even `pnpm dev`. Could we update `install-pre-commit.sh` to check for the `pre-commit` executable and only download it if it isn't present?

## Reproduction

1.  Run `pnpm install` and see pre-commit installing.
2.  Run `pnpm install` a second time and see pre-commit needlessly downloading and installing again.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by jalajk24** [comment]
Can I work on this issue?? I don't know a lot about how to proceed with this

**Comment by sarayourfriend** [comment]
You're more than welcome to work on it, @jalajk24. To resolve this issue, please add a check to the `install-pre-commit.sh` file that checks for the `pre-commit` executable and skips installation if it is already present.

**Comment by dhruvkb** [comment]
@jalajk24 are you familiar with how Git and GitHub work? If not start with the [GitHub docs' intro to Git](https://docs.github.com/en/get-started/using-git/about-git).

Next you should read the [`CONTRIBUTING.md`](https://github.com/WordPress/openverse-frontend/blob/main/CONTRIBUTING.md) and [`README.md`](https://github.com/WordPress/openverse-frontend/blob/main/README.md) files for an overview of the code contribution process.

Feel free to comment here if you need any additional help!

**Comment by dhruvkb** [comment]
Closing #1966 in favour of this issue because there has been more discussion here.

**Comment by sarayourfriend** [comment]
Ah, sorry about that, should have searched harder for an existing issue.
