### ISSUE TITLE
Add Sources and Search Guide pages to the new header

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1987]
## Problem

The new header/footer navbar is missing the Sources and Search guide pages. The pages are already available in the `/pages` directory, they just need to be added to the `use-pages` composable.

## Description

We need to add the pages here, between the Licenses and Get involved pages:
https://github.com/WordPress/openverse-frontend/blob/cc3f802c2d727417bfb2adb9f268e8739f9a1723/src/composables/use-pages.ts#L13-L22

```
        {
          id: 'sources',
          name: 'navigation.sources',
          link: app.localePath('/sources'),
        },
        {
          id: 'search-help',
          name: 'header.search-guide-nav-item',
          link: app.localePath('/search-help'),
        },
```

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by rajdeepdas2000** [comment]
🙋 I would be interested in implementing this feature.
