### ISSUE TITLE
Update the About page to add the text from "External sources" page

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1989]
## Problem

To better organize the information about Openverse, we need to remove the top-level "External sources" navigation link and move all the information from it to the About page.

## Description

Move the information from the External sources page to an appropriate place in the About page. This updated text should only be shown when the `new_header` is on.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by anton202** [comment]
can i work on it?
