### ISSUE TITLE
Set up redirect from `/external-sources` to `/about` page

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1990]
## Problem

We are moving the text from the External sources page to the About page.

## Description

To make sure that we do not break any links, we need to setup the redirect from `/external-sources` page to the `/about` page for when the `new_header` is on.

We already re-direct `/meta-search` to `/external-sources`. `meta-search` should also redirect to the About page.

https://github.com/WordPress/openverse-frontend/blob/cc3f802c2d727417bfb2adb9f268e8739f9a1723/nuxt.config.ts#L244

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by anton202** [comment]
can i work on it?

**Comment by obulat** [comment]
@anton202 , I think this issue is blocked. This redirect should only work if the `new_header` flag is set on, and I don't think we can get the flag value inside `nuxt.config.ts`, where the redirects are set up. Sorry for not noticing that earlier.

**Comment by obulat** [comment]
I haven't realized that this is not really tied to the `new_header` flag, @zackkrida! Then, we can un-block this issue, but make sure that both the redirect and the text changes in #1989 are merged at the same time.
