### ISSUE TITLE
Pages menu final item does not have correct bottom margin

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#2008]
## Description

![image](https://user-images.githubusercontent.com/24264157/203904715-f85781de-7b1d-4262-8af7-e111358a99fc.png)

## Reproduction

Visit any page (https://search-staging.openverse.engineering/search/?q=galah, for example), and open the pages menu (the three dots menu next to the search bar) and focus/hover over the final item in the dropdown menu. Focusing/hovering shows the incorrect margin very clearly, but it is still wrong when unfocused (i.e., it's not an issue with the focus box).

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by rajdeepdas2000** [comment]
🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
@rajdeepdas2000 Thank you! I've assigned the issue to you. If you have any questions, feel free to ping the maintainers at `@WordPress/openverse-frontend` for help.

**Comment by rajdeepdas2000** [comment]
Hi @sarayourfriend I managed to solve the issue using inspect element from the browser but I am unable to find the exact file in which the change is to be made.

**Comment by rajdeepdas2000** [comment]
I have raised PR #2037 to solve this issue. Kindly look into the PR. Thanks.
