### ISSUE TITLE
Menu and breakpoint improvement in new header

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#2009]
## Problem
After the implementation of the new header, there are three needs we need to tackle as improvements.

### 1. Internal pages
The current site has internal pages that were not included in the new header design as the content discussions did not settle and ended up in a insufficient list of item in the new mockup.

Due to the above, @obulat revisited the content of each page and shared with me questions and thoughts.

### 2. Active state
The new header did not consider an active state for the page link.

### 3. List extension in breakpoints
On the other hand, the page list overlaps Openverse logo in `md` breakpoint whereas in cases with available space, the full-page menu covers the device screen unnecessarily.

The second point does not show a UX problem, but it does have room for reaching a cleanest design.

### Issues related
- #1989
- #1987 

---

### Menu pages

After reviewing the content of each page in the menu, I propose having these pages in the following order:
1. **About:** To show Openverse story and link to ways of contributing.
2. **Licenses**: It has made sense to link a Creative Commons page, but I envision users not knowing exactly what CC licenses mean. In that vein, I like having a page explaining the CC licenses’ scope. This page can also gather future licenses if we aim to add more.
3. **Sources:** To list current sources and guide visitors on suggesting new ones. I remember that time ago, we talked about writing a guide for non-expert folks on *how to connect* their database to Openverse.
4. **Search guide:** To get search tips. In the future, we can delete this page to suggest search tips *during* the search experience.
5. **Get involved (external):** In the new header, this link lands in the [Openverse handbook](https://make.wordpress.org/openverse/handbook/).
6. **API (external):** Directing to the API site.
7. **Privacy:** To describe our privacy approach and link to WordPress pages if necessary.
8. **Feedback:** To report bugs and send miscellaneous feedback.

The order proposed goes from generic to specific: The project story (About); describe the content displayed (Licenses, Sources); tips on searching (Search guide); how to contribute at a more expert level (Get involved, API); and finally the privacy approach and asking for feedback.

I removed the “External sources” page from the list as I think we can put the content in the About page. It relates to the Openverse ethos of why we want to highlight sources not connected yet; it can also be moved to the Sources page. But linking a page from the header to this feature looks vague and needs more context.

Since the menu has a mirrored version in the footer component (content version), the proposal includes a footer update as well.

#### Header internal
![imagen](https://user-images.githubusercontent.com/895819/203973874-083d2012-9420-4a27-ac38-c3c0fa618bbb.png)
- [ ] Update header internal styles

#### Footer content
![imagen](https://user-images.githubusercontent.com/895819/203973777-2763b07c-a2da-4de1-88e4-3b7492ad476a.png)

### “Link” component
For the active state needed, I created a new "Link" component with resting, hover, and disabled states for its active and inactive versions. The component can be reused in other areas as is consistent with other actions across the site.

<img src="https://user-images.githubusercontent.com/895819/203974012-c9306c32-01e0-44db-a0e9-20d851be09f5.png" width="130">

### Breakpoint change
To show all pages correctly in every breakpoint, the design proposes using the burger version in both `sm` and `md` breakpoints. However, the full-screen menu is shown differently in `md` to tap into the viewport's available space.

The menu popover has Popover item components to be consistent with the Design Library’s elements available. At the same time, the label of each item is based on the “Link” component mentioned above to keep consistency.

#### `< sm` breakpoint
<img src="https://user-images.githubusercontent.com/895819/203974519-acba93df-c8bf-4b68-ba54-1d2d67fe004a.png" width="600">

#### `sm`, `md` breakpoints
![imagen](https://user-images.githubusercontent.com/895819/203974832-7247bae4-1f37-4879-8239-c6d7a7aeceab.png)

## Mockups
- Header component: [Design Library, upcoming header page](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=2959%3A6490). 
- Footer component: [Design Library, upcoming footer page](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=3018%3A7629&t=gjE9wqTv3hxc2Kek-0).
- Link component: [Design Library](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=3667%3A9753&t=gjE9wqTv3hxc2Kek-4).
- Header interaction and examples: [New header component](https://www.figma.com/file/KxkZmBNk218V2Fke1GeYCu/New-header-component?node-id=424%3A56729&t=Lfxr0YWtq30e0xnV-0), same as #1669 design issue.

## Implementation
- [x] #2012
- [x] #2013
- [ ] #2014

**Comment by AetherUnbound** [comment]
The proposed footers and drop-down menu for mobile look great!

**Comment by bengreeley** [comment]
Thank you for the screenshots, @panchovm! This is very helpful to visualize what the full experience will be like.

**Comment by sarayourfriend** [comment]
@panchovm These look great so far. Can you add mockups of the full version that includes a hover and focus states for the links including the following edge cases?

* First item focused/hovered
* Last item focused/hovered
* One item focused and another hovered (at the same time)

**Comment by jasmussen** [comment]
Lots to like here, nice work as always. 

One small niggle I have personally is with the "external link" icons. When intermixed with the other items, they clash between being both first and second class citizens at the same time. I'd love to find a way to remove them (which shouldn't block any efforts here, but is mainly shared for posterity). I understand they are there because technically they link to openverse.engineering. But I'm curious if we could just omit the icons still: if I've decided to click "API", I'd probably expect going somewhere technical, and I can always press "back". Screenreaders would still read the link to be external, of course.

Alternately, you could create a landing page on the main site to link to, without the external link — a "meta get started" page, and then link externally from there. This might also be a better experience for menu items intermixed with consumer-first items.

**Comment by panchovm** [comment]
I like the idea of landing pages to introduce certain topics, but I also like how Get involved takes you to the WordPress site and reinforces the project relationship. It is definitely food for thought, which visitors' data can enlighten once we start collecting analytics.

**Comment by panchovm** [comment]
I did not understand your request correctly @sarayourfriend, but I added a new section called [Link states](https://www.figma.com/file/KxkZmBNk218V2Fke1GeYCu/New-header-component?node-id=1035%3A69718&t=ey34xWOibP57pLy3-4) in the Header file where I put the states you mention. Here is a screenshot for a quick glance.

<img width="2439" alt="Header. Link states" src="https://user-images.githubusercontent.com/895819/204605069-55466cb7-30a0-40e8-9ab5-e39be66afb71.png">

I did not add a Link states section in footer as it lives in the Design Library. Nonetheless, here is a mockup echoing the header example.

<img width="1644" alt="Footer. Link states" src="https://user-images.githubusercontent.com/895819/204605729-ce666f84-72ec-4842-b9de-44cbe072cd07.png">

---

## Note
You can see the Link component's details used in Header and Footer components in Figma. Select the Footer component, open the internal layers, select the Link component, and open the component in the Inspect tab.

#### 1. Select the "Link" component in "Footer" component
<img src="https://user-images.githubusercontent.com/895819/204606808-6054a5b6-946e-4092-a0bd-b58551e92381.gif" width="200">

#### 2. Open the "Link" component from the Inspect tab
<img src="https://user-images.githubusercontent.com/895819/204607072-f909aaa6-55de-4a24-b028-35c27e64969a.gif" width="200">

**Comment by sarayourfriend** [comment]
That is perfect, thank you, Fracisco.

**Comment by obulat** [comment]
@panchovm, I wanted to confirm with you before closing this issue. We can close it now, right?

**Comment by panchovm** [comment]
Yes. We can close it. The outcome looks excellent ❤️
