### ISSUE TITLE
Update footer layout

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#2012]
## Footer screenshot
Please see the design issue #2009

The footer layout should be updated to match the screenshot.

## Mockup 
- Footer component: [Design Library, upcoming footer page](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=3018%3A7629&t=gjE9wqTv3hxc2Kek-0).

**Comment by aarushisoni** [comment]
hi i want to work on this issue.

**Comment by obulat** [comment]
Hi, @aarushisoni, this issue was already assigned and has a PR. You can look through other `help wanted` issues that are not assigned and don't have a PR: https://github.com/WordPress/openverse-frontend/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee
