### ISSUE TITLE
[Bug] Incorrect ISO codes for languages

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#202]
## Description

The ISO codes defined for the languages are incorrect. The ISO codes of languages are calculated in one of two ways:
- just using the ISO 639-1 two-letter language name (such as 'en', 'fr' or 'es')
- appending the ISO 3166-1 alpha-2 two-letter country name with a hyphen (such as 'en-GB', 'en-US', 'fr-CA' or 'es-VE')

The formula currently in use is incorrect.
https://github.com/WordPress/openverse-frontend/blob/5b3c545bbaa0f12021df9a80d15fce16bc770044/src/locales/scripts/get-validated-locales.js#L9

## Additional context

In the absence of ISO 3166-1 alpha-2 two-letter country name, it would be better to
- drop the ISO code and just inherit the lang from the WordPress theme
- just use the ISO 639-1 two-letter language name

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
I'm in favour of picking option 1 because that keeps us consistent with the parent WordPress page. Option 2 could be a fallback in such a setup (if a fallback is even needed).

**Comment by zackkrida** [comment]
Option 1 sounds great, thank you! I think when I wrote this i conflated `639-2` and `3166-1 alpha-2`.

**Comment by dhruvkb** [comment]
Understandable @zackkrida, I was also very confused at first and had to go line by line to see why the output was different from expected.
