### ISSUE TITLE
Add instructions to use `volta` to install node in the READMe

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#2038]
## Problem

We've gotten at least two newer contributors confused about which Node version to use. We pin the node version using Volta, but do not specifically direct the reader of the README to initialise volta in the repository. This seems to be a gap in the assumptions of what we think people will know on their own.

## Description

Add a new bit to the README before the `pnpm` installation instructions to run `volta install node@16.15.0`. I believe there's a way to get volta to automatically install Node at the pinned version (I thought that was the entire point) but I haven't found it in the docs yet and I don't have time right now to research it further. If whoever is working on this can figure that out, make sure the instructions specify to follow that method. Maybe it has something to do with using `volta run pnpm dev` instead of `volta run pnpm`? Additionally, we should add to check the package.json volta pinned version to see which version of Node the project currently expects (if that is indeed our canonical node version for the project).

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by rajdeepdas2000** [comment]
Raised PR #2040 addressing this issue, kindly review it. Thanks

**Comment by zackkrida** [comment]
I wrote a bit about how volta works [here](https://github.com/WordPress/openverse-frontend/pull/2040#pullrequestreview-1216306170):

> Volta automatically symlinks the correct node version, but it only does its check to create the correct symlink the first time node or npm is evoked in a directory. So if someone has volta installed, clones the frontend, and runs a command like `node -v` in the repo root, at that point volta will automatically install and symlink node v16.15.0 before evoking the command.
