### ISSUE TITLE
Add the search term as a query parameter to the single result page

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#2082]
## Problem

Currently, the single result page re-uses the search term value saved in the store to set the value of the search bar in the header. This works when browsing without the browser navigation. However, if you hit the browser `back` and `forward` buttons, there is no way in the app to understand the navigation direction and set the search term accordingly.

## Description

- [ ] Set the search term as a query parameter of the single result page. 
So, when navigating from the search result for "cat" to the first result, your route would be `/image/f9384235-b72e-4f1e-9b05-e1b116262a29?q=cat`
- [ ] Update the search store search term in `beforeRouteEnter`
Only update if navigating from the "search" page, and the "q" query parameter is available.

## Alternatives

We could also wait until we update to Nuxt 3, which makes it possible to understand whether the user pressed the "forward" or "back" button. However, we would still have to save the search term history somewhere to update it correctly.

## Additional context

For more discussion of this issue, look at the comments in #2046.

**Comment by anton202** [comment]
hi, i have a couple of questions :)
1. can i work on this issue?
2. iv\`e noticed that the `recent-searches` local storage array isn\`t populated with search result values when i search for things,
and that if i search, for example for: cat, then search for dog, then search for mouse. when i click on the browsers back button  
the browser fetches again dog and cat search results.
so i`m just wondering if thats just something that hast been implemented yet (taking the same search results from the local storage)?
