### ISSUE TITLE
On mobile, homepage content switcher gets cut-off at the bottom

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#2110]
## Description

The bottom part of the homepage is cut off on mobile. On an Android phone, it is worse on Chrome than in Firefox:

## Reproduction

1. Open http://staging.openverse.org on your mobile phone
2. Try changing the search type by clicking on the content switcher button inside the search bar.

### Firefox
On Firefox, if you try scrolling on the homepage, the footer is visible:
<img alt="Chrome homepage screenshot" src="https://user-images.githubusercontent.com/15233243/215804535-56daee38-a319-4249-82df-4f697ca4ef21.jpg" width = "200" />
But the last item in the content switcher is still cut off:
<img alt="Chrome homepage screenshot" src="https://user-images.githubusercontent.com/15233243/215804540-00a37df2-b6d2-4e1c-977b-a14a48b17511.jpg" width="200" />
### Chrome

WordPress logo in the bottom of the footer is cut off:
<img alt="Chrome homepage screenshot" src="https://user-images.githubusercontent.com/15233243/215804509-56688704-6b44-4211-b54c-4f94003a4bfc.jpg" width = "150" />
The last item in content switcher is cut off:
<img alt="Chrome homepage screenshot" src="https://user-images.githubusercontent.com/15233243/215804526-b597ce4b-afc9-4c41-b449-55f033cdeb05.jpg" width="150" />

## Environment

- Device: Samsung phone
- OS: Android
- Browser: Chrome, Firefox

## Additional context
The issue is caused by the way mobile browsers handle the height in `vh` units and hiding /showing the address bar.

One quick fix would be to add padding at the bottom of the homepage footer and the content switcher with a height equal to the height of the address bar.

Another would be to set the height to "100%". However, due to the way Nuxt layout is nested, we would need to add the height value to several nested divs. Also, 100% height is the height of the viewport without the height of the address bar. This means that when the address bar is hidden, there will probably be some space at the bottom.

@WordPress/openverse-frontend, what do you think is the best solution here?

**Comment by zackkrida** [comment]
Switching the .app to `min-height: 100dvh;`  should be the cleanest fix for modern browsers. Support is here: https://caniuse.com/mdn-css_types_length_viewport_percentage_units_dynamic

we could do

```css
.app {
  min-height: 100vh;
  min-height: 100dvh;
}
```

The fallback would still cut off a little. I don't know what our exact device usage is but I know most of our traffic is desktop.

Alternatively I think we'd want to do a JS-based approach where we set a CSS variable to determine the min-height of the app.

**Comment by zackkrida** [comment]
@obulat thats a perfect idea! Awesome
