### ISSUE TITLE
[Bug] Remove button styling from "no results" text

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#215]
## Description

When there are no image or audio results available, the "No more images" text is styled as a button and includes a `:(` frowning emoticon. We should replace this with a plain style that doesn't suggest interactivity like a button does. We should also replace the copy.

## Solution

When reaching the end of a set of search results, show nothing:

> before 

<img width="1281" alt="CleanShot 2021-09-15 at 14 41 04@2x" src="https://user-images.githubusercontent.com/6351754/133490932-da88a911-d020-4c51-a54f-a70e06e94c97.png">

> after

<img width="1281" alt="CleanShot 2021-09-15 at 14 41 33@2x" src="https://user-images.githubusercontent.com/6351754/133490948-c5e9a551-e055-4f34-8dd7-e9f0c05cea56.png">

When a search term has _zero_ results, remove the error message and "no more images" button, and _instead_ modify the "Not finding what you're looking for?" text to read "No {media} results for {search term}", like so:

> before

![CleanShot 2021-09-15 at 14 43 23@2x](https://user-images.githubusercontent.com/6351754/133491302-fb54d3e1-b1b8-4191-b5f7-2db6856e6871.png)

> after

![CleanShot 2021-09-15 at 14 46 39@2x](https://user-images.githubusercontent.com/6351754/133491588-44cd0274-cc97-411c-a877-a5e70c2705c0.png)

**Comment by Kevan-Y** [comment]
Hi, I'm a newbie here. I don't have that must knowledge in Vue.js. But it's a little bit similar to React.js framework. 
I would like to try this issue. Can I work on it?

**Comment by zackkrida** [comment]
Sure @Kevan-Y you can try!

**Comment by Kevan-Y** [comment]
@zackkrida I’m doing this as part of Hacktoberfest and open sources class and wondered if you’d mind adding the label Hacktoberfest

**Comment by zackkrida** [comment]
The repository has the `hacktoberfest` topic so it will count!
