### ISSUE TITLE
Add old search portal link to "About" page

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#217]
The "About" page at https://wp.org/openverse needs a final sentence "Looking for the old CC Search portal? Visit https://oldsearch.creativecommons.org." added.

**Comment by theshakeabhi** [comment]
Do we have to add "Looking for the old CC Search portal? Visit https://oldsearch.creativecommons.org." in  https://wordpress.org/openverse/about ?

**Comment by dhruvkb** [comment]
I think the language could be a little refined, as "old CC Search portal" suggests that Openverse is the new one, but Openverse technically **isn't** the new CC Search.

**Comment by theshakeabhi** [comment]
> 
> 
> I think the language could be a little refined, as "old CC Search portal" suggests that Openverse is the new one, but Openverse technically **isn't** the new CC Search.

So could it be like:
Looking for the previous version of portal? Visit https://oldsearch.creativecommons.org.

**Comment by zackkrida** [comment]
Let's do "Coming from CC Search, and looking for the old portal? Visit oldsearch.creativecomons.org"

**Comment by zackkrida** [comment]
Sorry about this @theshakeabhi but the more I think about this, I think we do not actually need this feature at all. Thanks for suggestions and for chiming in as well @dhruvkb
