### ISSUE TITLE
[Bug] Fix nav link to the API

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#218]
The navigation link in the "Resources" menu dropdown should link to https://api.openverse.engineering/v1/

![CleanShot 2021-09-15 at 16 13 50@2x](https://user-images.githubusercontent.com/6351754/133502902-d3bd5f73-f776-4bde-a30c-4ced252932ca.png)

**Comment by theshakeabhi** [comment]
Hi, @zackkrida I have found the fix and implemented it on my local machine.
