### ISSUE TITLE
Add translator note for Dutch translation of `search-guide.example.prefix.content`

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#2189]
We should include a notice for translators for this string `search-guide.example.prefix.content`, because translating "Netherlands" could remove the prefix used to explain this search syntax.

From a commenter in Slack:

>  I just wanted to say that for this string: https://translate.wordpress.org/projects/meta/openverse/nl/default/?filters%5Bstatus%5D=[…]inal_id%5D=12384661&filters%5Btranslation_id%5D=100956682 I'd add an additional comment so that it's clear that they don't translate the whole string for batum since e.g. Netherlands in Dutch is Nederland. Which wouldn't be correct with "Net" in the previous sentence of the string.

**Comment by NekoJonez** [comment]
Excellent. You made this commenter happy
