### ISSUE TITLE
[Bug] Title spacing on content pages

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#223]
There should be 48px between the title of a page and its content. This issue currently affects a few pages:

- ~https://wordpress.org/openverse/feedback~ Fixed.
- https://wordpress.org/openverse/search-help

<img width="385" alt="CleanShot 2021-09-15 at 16 00 35@2x" src="https://user-images.githubusercontent.com/6351754/133501342-20bbf52f-de60-4037-bca7-54447f01cf29.png">

**Comment by theshakeabhi** [comment]
Hey all, I am new to open source and I was wondering if I could take this up. @zackkrida

**Comment by dhruvkb** [comment]
@theshakeabhi you're welcome to! For issues labelled 'good first issue' you don't need to ask.

**Comment by theshakeabhi** [comment]
> 
> 
> @theshakeabhi you're welcome to! For issues labelled 'good first issue' you don't need to ask. [Our handbook](https://make.wordpress.org/openverse/handbook/new-contributor-guide/) might be a helpful read for you as a new contributor.

So once I set up this repo on my local, make a dedicated branch for this and make changes I can put a PR?

**Comment by zackkrida** [comment]
Exactly @theshakeabhi 😄 I reccommend you check out the [Local Development](https://github.com/WordPress/openverse-frontend#local-development) section of the README.

**Comment by 0kyn** [comment]
Hi everyone,

As a first timer open source contributor I'd like to contribute too. Of course, I'm not really sure about my process :sweat_smile:

@zackkrida you mention this url : https://wordpress.org/openverse/feedback, but it seems there is already a spacing between the title and the content on the main branch. Maybe I missed something?

By the way thank you for opening contribution to baby open source contributor !

**Comment by zackkrida** [comment]
You are right @0kyn it looks like `/search-help` is the only affected page!
