### ISSUE TITLE
[Bug] "To the top" arrow visually button broken

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#247]
## Description
The "to the top" arrow button in the corner of the results page is broken visually

## Reproduction
Go to `/search/image?q=dogs` and observe the to the top arrow button in the bottom corner.

## Expectation
The arrow should be centered

## Screenshots
<img width="103" alt="Captura de Tela 2021-09-20 às 13 19 34" src="https://user-images.githubusercontent.com/24264157/134069956-3f0b2202-fb8f-4c5f-a5b4-dcb2cdc4df67.png">

## Environment

 - Device: laptop
 - OS: macOS
 - Browser: Confirmed in Chrome and Firefox
 - Version: Evergreen

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
This should additionally be redesigned @panchovm 
The thinness of that icon! 😢

**Comment by theshakeabhi** [comment]
While inspecting this button, I found that when you remove the `display:block`, it automatically realigns itself.
If we change from `display:block` to `display:inline` it should correct itself and  `vertical-align: middle` doesn't work with `display:block`

**Comment by panchovm** [comment]
I am using the [chevron arrows](https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library) from the WordPress Library. In this case, the `chevron-up`. The [Figma file](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=8%3A13) has a `24px` square size version and I am using it as it is there.
