### ISSUE TITLE
[Bug] Use camelcase in prop names

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#254]
## Description

These components use the string 'URL' in the prop name.

https://github.com/WordPress/openverse-frontend/blob/428be354eada6b29dc3d63f21c7960e42386b423/src/components/ImageDetails/ImageInfo.vue#L65
https://github.com/WordPress/openverse-frontend/blob/428be354eada6b29dc3d63f21c7960e42386b423/src/components/ImageDetails/ImageAttribution.vue#L24
https://github.com/WordPress/openverse-frontend/blob/428be354eada6b29dc3d63f21c7960e42386b423/src/components/MediaInfo/MediaLicense.vue#L72
https://github.com/WordPress/openverse-frontend/blob/428be354eada6b29dc3d63f21c7960e42386b423/src/components/MediaInfo/CopyLicense.vue#L188

This leads to the following syntax where the component is used with props:

```html
<Component :something-something-u-r-l="value"/>
```

This is not looking good. Changing the props from 'URL' to 'Url' would fix this.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by theshakeabhi** [comment]
I have been going through the code in the `main` and I found these:
`ccLicenseURL` has been used 20 times in 9 different files
`licenseURL` has been used 14 times in 5 different files
`openverseLicenseURL` has not been used till now.

Should one changes every occurance of it?

**Comment by krysal** [comment]
@theshakeabhi that is correct, it should be changed in all places to keep uniformity. Contributions to this are very welcome!

**Comment by theshakeabhi** [comment]
@krysal these changes that @dhruvkb mentioned is on a specific branch `https://github.com/WordPress/openverse-frontend/tree/428be354eada6b29dc3d63f21c7960e42386b423`. So should I pull this branch and make this as base branch and make modification or should I take the `main` branch as the base branch?

**Comment by dhruvkb** [comment]
@theshakeabhi Make the changes on `main`. I used the absolute commit has so that the issue remains valid after the fix is pushed.

**Comment by theshakeabhi** [comment]
@dhruvkb That's intresting. Thank you directing me.
