### ISSUE TITLE
New 404 Page

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#256]
## Problem

Our current 404 page is unhelpful to users and unattractive. We should implement a new one with a built-in search bar and styling that reinforces Openverse's brand. 

## Description

**Edit: the page is designed and ready for work!**

Figma Link: https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A6869

![image](https://user-images.githubusercontent.com/895819/144856173-d6221f0a-d574-41c4-8e50-636e71aadcf4.png)

## Original brief

> 
> We should design a new page (cc @panchovm) that provides better functionality and aesthetics. Some ideas for functionality:
> 
> - A center search bar to encourage a user to submit a query
> - More helpful information (for example, if they 404 on a `/photo/{id}` url, say something like "The photo you tried to view may have been removed" etc.)
> - Perhaps some featured collections or a random piece of media

**Comment by panchovm** [comment]
Perfect. I assigned it to myself and will back with a proposal.

**Comment by panchovm** [comment]
Here is the version I like most. It works as a template for the whole WordPress.org site.

Each section (TBD which ones) will have a customized version where background color and prompts change. There is also space for the section menu below the main header. The component is optional, but it should remain simple.

## Mockup
![image](https://user-images.githubusercontent.com/895819/144856173-d6221f0a-d574-41c4-8e50-636e71aadcf4.png)

**Comment by panchovm** [comment]
I updated the [Releases file](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A6869) with the mockups for Desktop and Mobile.

**Comment by krysal** [comment]
Solved by #583.
