### ISSUE TITLE
[Bug] Audio row icon spacing issues

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#258]
## Description

The audio row license icons have odd spacing irregularities.

<img width="1029" alt="CleanShot 2021-09-23 at 11 58 08@2x" src="https://user-images.githubusercontent.com/6351754/134542291-cf2eb0a9-2fb5-4664-b3ff-49132404923c.png">

## Reproduction

1. 
2. 
3. 
4. See error.

## Environment

 - Device: 
 - OS: 
 - Browser: 
 - Version: 
 - Other info: 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
It was intentional on my part to separate the CC logo from the license aspect logos. In hindsight, it was a poor decision on my part.

None of the audio component mockups on Figma show how to present CC licenses (with more than one icon). It's always PDM which is a single circle.

**Comment by zackkrida** [comment]
Ah, I totally understand your intention, thanks for clarifying. I went with a uniform gap between icons and a larger gap between the icons and license name in #259, but I'll check with Francisco.

**Comment by dhruvkb** [comment]
Yeah, some mockups for CC icons will help clarify the inter-icon and icon-text spacing. Will hold off on the PR review till we have that.
