### ISSUE TITLE
[Bug] Running `npm run dev` on Windows failed

### ISSUE THREAD

**Issue by 0kyn** [WordPress/openverse-frontend#291]
## Description
Running `npm run dev` on Windows returns an error.

## Reproduction

1. run the command above
```bash
npm run dev
```
2. See error.
> 'ENABLE_AUDIO' is not recognized as an internal or external command,
operable program or batch file.

## Expectation
Expecting dev environment watching for changes

## Screenshots
![image](https://user-images.githubusercontent.com/29523399/135931602-b9f665ee-149c-4236-a63f-14bb3b73db71.png)

## Environment
 - Device: Virtual Box
 - OS: Windows 10
 - Terminal: Powershell 5.1

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

### Solution 1

Add the following line in `scripts` section in `package.json` 

```json
{
    "scripts": {
        "dev-win": "set ENABLE_AUDIO=true && nuxt",
    },
}
```

### Solution 2

Add [cross-env](https://www.npmjs.com/package/cross-env)

```bash
npm install -D cross-env
```

```json
{
    "scripts": {
        "dev": "cross-env ENABLE_AUDIO nuxt",
    },
}
```

I actually prefer the first solution as it doesn't need others Node dependencies, but `cross-env` might be more scalable?

**Comment by zackkrida** [comment]
Thanks for raising this issue, even though it adds a new dependency I think `cross-env` is the most robust solution.
