### ISSUE TITLE
[Bug] Frontend fails to run if translations aren't fetched first

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#298]
## Description
Sometimes new translations will be available for the frontend but if you don't run `i18n:get-translations` before running `npm run dev` the API will crash after building.

## Reproduction

1. Checkout the repository and delete a translation `.json` file
2. Run `npm run dev`
3. See error about missing translation files

## Expectation
Missing translations shouldn't crash the server

## Additional context
Expectation according to @zackkrida 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by 0kyn** [comment]
Hello @sarayourfriend, it might not help but `i18n:get-translations` has been removed in the following commit https://github.com/WordPress/openverse-frontend/commit/e94c0f973b88e094ae256aa9a9883108ffc5f686

**Comment by sarayourfriend** [comment]
@0kyn yeah, I think it was removed because getting translations isn't meant to be a pre-requisite for running the site locally. Correct me if I'm wrong though @zackkrida
