### ISSUE TITLE
Visiting english site doesn't set english locale

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#308]
If you visit a translated site like es.wordpress.org/openverse and then return to wordpress.org/openverse, the locale cookie for the Spanish site remains set.

**Comment by obulat** [comment]
The problem for English is the fact that we search for the wpLocale code, ie `en_US`, for default English locale:

https://github.com/WordPress/openverse-frontend/blob/9d06701afac1c61c10350d21c066df2f821bb527/src/mixins/i18n-sync.js#L11-L17

But the default locale in `nuxt.config.js` does not have a `wpLocale` property:
https://github.com/WordPress/openverse-frontend/blob/9d06701afac1c61c10350d21c066df2f821bb527/nuxt.config.js#L177-L182

We can keep this issue for the English locale, and open a new one for the problem with other languages mentioned by @sarayourfriend .
