### ISSUE TITLE
Improve transitional design of the homepage media type chooser

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#322]

**Comment by zackkrida** [comment]
@panchovm Thanks for these! The reason I went with the approach in #271 is that it's very simple to code. Building a new dropdown or search input seems like a bit too much work for the transitional styles.

> All ideas have a content type selected by default. Another idea I haven't reject yet is showing both content types as buttons but working as radio. 

I would be interested to see this! I _do_ like the idea of introducing the new icons in this.

**Comment by panchovm** [comment]
Here are two ideas. The second one is cleaner I think.

### Home. Switcher 41
![Home  Switcher 41](https://user-images.githubusercontent.com/895819/137492432-4be84802-730e-4a35-b619-9e26f99fc56e.gif)

### Home. Switcher 43
![Home  Switcher 43](https://user-images.githubusercontent.com/895819/137492436-1d86ee22-d7ee-45ec-9088-0d8010b61334.gif)

**Comment by zackkrida** [comment]
@panchovm thank you! I like the second one a lot, super simple. Thanks!

**Comment by zackkrida** [comment]
We are no longer implementing this as the redesign will launch soon with audio. Closing.
