### ISSUE TITLE
Add RTL debugging tool to Storybook

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#332]
## Problem
It's hard to debug RTL languages in Storybook without a lot of manual fiddling. To make it easier to develop components, techniques, and pages that are RTL friendly, we should add a toolbar for enabling RTL inside of Storybook.

## Description
We can follow the example from Gutenberg here: https://github.com/WordPress/gutenberg/pull/35711

Our approach with necessarily be different because how we detect whether RTL is active or not is different (we don't use `@wordpress/i18n` is the primary difference) so we'll need to figure out a standard way of detecting it in code and in styles that we can manipulate for these purposes.

For styling, we can probably use the `:root[dit="rtl"]` selector in most cases. For programmatic detection of RTL we'll need to figure something else out.

Vuei18n doesn't have anything built in to help you programatically detect whether the current locale is RTL, so we might have to come up with something on our own for that. `@wordpress/i18n` exports a `useRTL` function that returns a boolean. Perhaps ours could be as simple as:

```
function useRTL() {
  return document.matches('[dir="rtl"]')
}
```

Or something along those lines. Not 100% it would fit all our use cases (it's not reactive to updates to the attribute for example, but I'm sure that could be solved somehow?)

## Additional context
Huge props to ~@talldan~ @mirka for the Gutenberg implementation inspiring this issue.

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
I think it might be good to add the Tailwind plugin so that we use start and end instead of fixed directions. 

`MutationObserver` would be a nice addition for detecting changes to the direction of the page.

**Comment by obulat** [comment]
RTL plugin will be a great addition!

As for detecting the `dir` programmatically: Vue i18n exposes the `$i18n` object in the components, however, the `$i18n.locale` only has the locale code in it. We can still get the direction programmatically by looking in the `$i18n.locales` array, as it does have the `dir` property :
```
const locale = this.$i18n.locales.find((i) => i.code === this.$i18n.locale)  
const dir = locale.dir ? locale.dir : 'ltr'
```
