### ISSUE TITLE
Malformed variable interpolation for translations

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#340]
## Description
Something is wrong with the `translated pot -> json` pipeline. Some variable interpolations are not working as expected

<img width="1456" alt="Captura de Tela 2021-10-19 às 07 55 57" src="https://user-images.githubusercontent.com/24264157/137936792-bd7bc475-aa93-4a66-a4d9-e214b26caed4.png">

## Reproduction
Switch to German and create a query with no results (like `kingfisher` with the source filtered to thingiverse) and note the malformed variable interpolation resulting in `###query###` displaying on the screen.

## Expectation
Variable interpolations should all be transformed from the POT format to the format that VueI18n understands.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by 0kyn** [comment]
I got it, thank you @obulat! I took a wrong track... :sweat_smile:
