### ISSUE TITLE
Default artwork for audio 

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#349]
## Description

Currently we show a plain yellow square when an audio search result doesn't have artwork. We should develop something a bit more compelling, that reinforces the Openverse brand:

## Requirements

- Use the Openverse colors
- The image should clearly represent 'audio'
- (optional) Could be generative/dynamic (for example, a pattern derived from the waveform/peak data, [ugly example here](https://codepen.io/zackkrida/pen/mdMWBoZ))

## Screenshots

![CleanShot 2021-10-25 at 12 33 33@2x](https://user-images.githubusercontent.com/6351754/138737571-3fa96a0b-1280-45af-828e-32024419642b.png)

**Comment by zackkrida** [comment]
@panchovm just reminding you about this over the next few weeks. Thanks!

**Comment by panchovm** [comment]
Here is [the code](https://href.li/?https://editor.p5js.org/javier/sketches/MxBoYqw9a) of the openverse-generated artwork contributed by [Javier Arce](https://github.com/javierarce).

<img width="300" alt="CleanShot 2022-01-10 at 13 32 05@2x" src="https://user-images.githubusercontent.com/895819/148802210-444217d2-eef0-4712-bf8b-a1b158f709cd.png">

We designed a dot pattern based on a bezier curve where distant dots decrease their size simulating a wave effect. I tested different alternatives and the version I like most is `amount = 10`, `spacing = 12`, `border = 0`.

## Mockups

|Results. Desktop|Results with filters. Desktop|Results. Mobile|
|---|---|---|
|![Audio results](https://user-images.githubusercontent.com/895819/148801702-afe5a43c-dc75-4975-b321-cd9e53063d8d.png)|![Audio results  Filters expanded](https://user-images.githubusercontent.com/895819/148801695-28f2205d-d593-4940-967e-d08b65ec6133.png)|![Audio results  Mobile](https://user-images.githubusercontent.com/895819/148801700-fa17d324-2f44-48b1-bd39-760a4dcd9c32.png)|

**Comment by zackkrida** [comment]
Awesome! For devs, here is a fork of Javier's code with the rendered controls removed and with Francisco's preferred settings:

https://editor.p5js.org/zackkrida/sketches/SVPlnIHdq

**Comment by dhruvkb** [comment]
While I'm still unsure how the peaks data would translate to these dots, I'd love to do some work on this.

**Comment by zackkrida** [comment]
That would be awesome @dhruvkb . It might be best to focus on reimplementing the code first and figuring out how to incorporate peak data later. While I love the idea, it's starting to feel like an enhancement with our time constraints.
