### ISSUE TITLE
Allow users to submit CC-licensed content to Search (original #441)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#35]
This issue has been migrated from the [CC Search Frontend repository](https://github.com/creativecommons/cccatalog-frontend/issues/441)

```
Author: kgodey
Date: Thu Jul 25 2019
Labels: 🏷 status: label work required,🙅 status: discontinued,🚧 status: blocked
```

**Comment by zackkrida** [comment]
Closing. This is not a goal that will be directly attained by Openverse, but there may be other projects in this space in the future.
