### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#364]
## Components

- [x] #462
  - [x] #371
  - [x] #375
  - [x]  #490
  - [x] #370 
  - [x] #485 
  - [x] #476
- [x] #453
- [x] #365
- [x] #228
- [x] #395
- [x] #458
- [x] #366
- [x] #405
- [x] #477

## Other

- [x] #376 
- [ ] #482
  - Preserves image aspect ratio in a 5-col grid, scales down when filters are opened
- [x] #368
- [x] #533 
- [ ] #529
- [ ] #480

**Comment by sarayourfriend** [comment]
None of the figma links appear to work any more 🙁

**Comment by zackkrida** [comment]
Oh no! I'll update the ticket, thanks for flagging @sarayourfriend

**Comment by zackkrida** [comment]
Launched as Openverse [`v3.0.0`](https://github.com/WordPress/openverse-frontend/releases)
