### ISSUE TITLE
Filters sidebar

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#368]
## Description

Filters sidebar display all filters that are available for current media type(except for `mature` filter, which is not displayed), and their selected/not selected state. The visibility of the filters should be set by the parent. The filter sidebar should have a [max-width/ set width] ?? of [316px/ 1/5th of the screen width ] ?? on screens that are larger than [mobile - 375px / tablet ???] ?? On mobile screens, it should be full-width.

### Props

`filters`: an object with `filterType` keys and an array of filter objects:

| Name | Type | Description |
|-|-|-|
| filters | an object with `filterType` keys and an array of filter objects | `{ licenses: [ { code: 'cc0', name: 'filters.licenses.cc0', checked: false } ...  ], ... } `

### State

| Name | Type | Description |
|-|-|-|

### Events

| Name | Associated data | Description |
|-|-|-|
| hide | none | The parent should hide the filters on receiving this event
| toggle-filter | `filterType`, `code` | This event should be called on child checkbox 'change' event, and handled by Vuex TOGGLE_FILTER action.
| clear-filters | none | This event should be called on 'Clear filters' button click, and should call Vuex CLEAR_FILTERS action.

## Dependencies

- [x] #405
- [x] License explanation popup depends on #366

## References

- **Figma:**
Desktop:
https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A48756
Mobile:
https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A12225

## Implementation

- [ ] 🙋 I would be interested in implementing this component.

**Comment by obulat** [comment]
@panchovm , 
Could you please clarify a couple of questions about the filters list:
### Width:
Should it be max width  or set width? 
316px (or something else), or 1/5th of the screen width?
### Tablet width:
I guess the mobile design should be used?

Also, are we going to have the 'License explanation' buttons with a popup (what would the popup look like on mobile?) and the 'Clear filters' button?

**Comment by panchovm** [comment]
## Width

The width should be fixed as `316px` and right-aligned. The area that changes its size is the content area where results appear. Here is an example of what I was thinking of for the expanding behavior.

https://user-images.githubusercontent.com/895819/140318644-4740441d-9593-49dc-ac37-dc3c01f2926a.mp4

## Breakpoint
Regarding tablet size, we should pick a Tailwind breakpoint based on issue #391. I would say that tablet is between `md` and `lg` values.

However, I am not sure about the audio component reaction to viewport resize, beyond the component change from **Row M** to **Row L** when showing filters. Here is an example of my point.

https://user-images.githubusercontent.com/895819/140319583-3b596886-b946-47f9-9ce5-e69ae15064b8.mp4

**Comment by dhruvkb** [comment]
Since these layouts are controlled by Vue props `layout` and `size` (i.e. JS), connecting them to CSS breakpoints might be inelegant. If our layouts have specific sizes connected to specific CSS widths, we must retire the `size` prop in favour of TW screen prefixes. This will need a significant rewrite of the audio-player layouts.

The Row L layout has a higher vertical alignment and Row M needs more horizontal space. In that sense, it could make sense to use Row M for wider screens.

**Comment by zackkrida** [comment]
@dhruvkb Could we determine the value of the existing layout and size props based on js media queries, so we don't have to refactor the audio components but can still couple the layouts to the breakpoints?

**Comment by obulat** [comment]
I am going to close this as the main work on the filters sidebar has been completed in #606. Other fixes will need their own issues.
