### ISSUE TITLE
Content switcher on mobile

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#370]
## Description
Since we will start implementing the audio integration based on the redesign (#364), there is room for improvement of the content switcher on mobile.

The current one has a horizontal distribution of content items and a vertical distribution of internal pages. That adds unnecessary complexity to identifying the elements. Besides, it seems reasonable to follow the general style on desktop view.

 <img src="https://user-images.githubusercontent.com/895819/139077452-fdfc9e43-8da5-4acf-a378-931e4d860195.png" width="300"> 

## Alternatives
I was working on different ideas and here is the version I like most.

 <img src="https://user-images.githubusercontent.com/895819/139077691-eda35b83-7b1b-45f1-8c44-0585293449dd.png" width="300"> 

The changes are:
* All elements are vertically distributed.
* The active item has the same style as on desktop and a `check` icon (from [WordPress Design Library](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=8111%3A19295)) for a11y purposes.
* There is more space between sections.
* **Content type** title has `dark-charcoal` color.

**Comment by sarayourfriend** [comment]
I'm going to work on a base component for this, ItemGroup or something like that.

**Comment by zackkrida** [comment]
you're right and i ❤️ that API. Here's another likely use case: 
https://github.com/WordPress/openverse-frontend/issues/329

**Comment by sarayourfriend** [comment]
So maybe a `direction: 'vertical' | 'horizontal'` prop too. If we went for a grid pattern in the future it should be trivial to add a `columns` prop or something like that.

**Comment by sarayourfriend** [comment]
@panchovm what're the focus styles supposed to look like for each item? Just the regular button focus styles with the pink focus ring we've been using?

**Comment by panchovm** [comment]
Here are the [styles for that component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=699%3A2386). I also added a mockup in the **Releases** file showing the `focus` style of Images item.

**Comment by sarayourfriend** [comment]
@panchovm I'm confused, you linked something that looks like the popover buttons, but the issue description doesn't talk about a popover I don't think. These items don't have borders like the image in the description. Maybe I'm looking at the wrong thing? I also can't find the Releases file 😞

**Comment by panchovm** [comment]
Sorry, I added the wrong link. [Here](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=956%3A2871) you can see the mobile view, also adding a screenshot below. The [Release file](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=654%3A14907) has the same mockup but next to all other mockups.

I tried different ideas for the `focus` style of elements inside a popover menu, which convinced me the most.

<img src="https://user-images.githubusercontent.com/895819/141478679-1dcc8c72-2a33-44d3-8f8a-63b96ce43d2f.png" width="300">

**Comment by sarayourfriend** [comment]
I see! I think there's a little confusion because these components look fairly similar but I'm not confident their implementation can be the same, but I will do some exploration to see if that is the case. They're definitelly all based on the Button component in some way but they have slightly different styles (mostly related to borders).

Thank you for clarifying and linking the releases document! I have it bookmarked now.
