### ISSUE TITLE
e2e test suite

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#387]
## Problem

We currently make lots of small regressions in search functionality that aren't covered by our unit tests.

## Description

Add a robust e2e test suite either using the existing Cypress code or by implementing https://github.com/microsoft/playwright, which probably has a smaller learning curve and size footprint.

## Alternatives

There is no alternative 😆

**Comment by sarayourfriend** [comment]
I think @obulat already completed this!
