### ISSUE TITLE
Content report popup doesn't close

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#389]
## Description
If you open the content report popup for an image and send a mature content report, you can sometimes close the popup once, but if you reopen it it doesn't reset back to the original state of the popup and you can now no longer close it.

## Reproduction

1. Go to an image (like `/openverse/photos/03917307-e9d9-4a7d-9607-955230e19a87`)
2. Click the "Report this content" link underneath it
3. Select the option to report mature content and hit next until you see the thank you notice
4. Click the X in the upper corner to close the popup

## Expectation
Clicking the X in the corner or elsewhere on the page outside the popup should close it always. When it is closed, it should also reset back to the original state.

## Additional context
There are no console errors

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Fixed in #561
