### ISSUE TITLE
URL preview image does not show up correctly

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-frontend#393]
## Description

When trying to share links directly to the service, it appears that the link preview image doesn't reference a valid URL.

## Reproduction

1. Copy a link from search.openverse.engineering
2. Paste it into something that will attempt to expand the URL with additional metadata, like Slack or Discord

## Expectation

Either an image should show up, or no image should show up at all.

## Screenshots

![image](https://user-images.githubusercontent.com/10214785/139722273-c5b91556-6d50-4851-90c1-1263911781d7.png)

## Additional context

@zackkrida Says this is related to, but distinct from, the issue with passing this info through the `iframe`.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
This will be partially be fixed by #121, which makes the Open Graph image for each page the _actual image_, but is further by WordPress/openverse#81.
