### ISSUE TITLE
Clean up image assets

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#396]
## Problem

Currently a number of image assets (including SVGs, JPGs and PNGs) are stored directly under `src/assets/`. This is in direct contrast to a number of organised image assets in `src/assets/icons/` and `src/assets/licenses/`.

## Description

The goal is to clean up the folder. Remove unused assets and organise the used ones into a proper folder structure. One way to do so would be to put the assets for the providers into one folder. Another would be to collect the assets for the CC licenses in another folder. 

## Alternatives

Deleting the unused ones would be a good start as cleaning up the rest would be easier.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by MukulKolpe** [comment]
Hey @dhruvkb can I work on this issue?

**Comment by zackkrida** [comment]
Sure @MukulKolpe !

**Comment by dhruvkb** [comment]
A lot of provider logos (pattern `*_logo.png`) in `src/assets/` are unused.
