### ISSUE TITLE
Audio waveform should respond to the spacebar to play or pause the audio.

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#402]
## Problem
When navigating with the keyboard on the various audio track components, you can only play or pause the audio on the play/pause button. This is a problem if you're seeking through the audio via keyboard on the waveform and want to be able to toggle the play/pause using the spacebar (a common operation in most media players).

## Description
We should add a `@keypress.space` listener to the waveform component to toggle the audio play state.

## Additional context
Found while testing keyboard navigation for this PR https://github.com/WordPress/openverse-frontend/pull/399

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
@dhruvkb I wanted to run this by you, but I think there's a way to simplify the audio state management. I know you were looking into some of this before so let me know if this is stepping on work you're already doing or else just generally what you think of this approach.

Basically I think we can use a composable with just some local refs to manage the state of the audio _and_ only use a singleton Audio object throughout the lifetime of the application, regardless of how many players we have on the page. Something like this:

```js
let audio = new Audio()
const isLoaded = (src) => audio.src === src

export function useAudioState({ src }) {
  const status = ref('ejected')
  const position = ref(0)

  const handlePlaybackEnd = () => {
    status.value = 'played'
    // etc
  }

  const handleLoaded = () => {
    statuc.value = 'playing'
    audio.play()
  }

  const play = () => {
    if (isLoaded(src)) {
      audio.play()
      status.value = 'playing'
      return
    }
    
    // destroy the existing audio object and replace it with a new one to destroy existing audio object event listeners from listening
    audio = new Audio(src)
    // these aren't the actual event names, just pseudo-code
    const handleLoaded = () => { /* handle loading, play audio, set status etc */ }
    audio.addEventListener('loaded', handleLoaded)
    const handleEnded = () => { /* handle playback ending, set status, etc */ }
    audio.addEventListener('ended', handleEnded)
    
    // set up position ref updating
  }

  const toggle = () => { /* toggle the status and play/pause the audio playback */ }
  const seekTo = (pos) => { /* handle seeking */ }

  return { status, play, toggle }
}
```

Something along those lines might work, would remove the dependency on the Vuex store and the global "active media item", and would hopefully simplfy things (heck I think it would even make this more easily testable as the composable should be testable in a way that reliance on the physical audio element currently isnt (in that we could mock the global audio object to verify certain methods are called in some conditions).

**Comment by dhruvkb** [comment]
My idea was along the same lines, i.e. having a single audio object but that poses some challenges of its own:
- managing the state of partially played audio tracks (which separate `<audio>` tags can handle automatically)
- caching the audio files so that multiple files can be played without having to "buffer" everytime you go back to an older one

Imo, we should still use the store to communicate between the individual audio components and the global player. That gives us the option to swap out the singleton in favour of something better in the future without having to change the implementation inside the audio-tracks (for all they care is just that the store has the right state).

**Comment by sarayourfriend** [comment]
> managing the state (such as current-time & download status) of partially played audio tracks (which separate <audio> tags can handle automatically)

That's true, we would have to manage them externally, but I seem to remember in discussions with @panchovm that we had decided that we didn't need to save the current playback position when switching between playback for different files.

As for the download status: I'm not sure I follow here. Do we indicate this on the screen currently?

> caching the audio files so that multiple files can be played without having to "buffer" everytime you go back to an older one

I was able to test this, and the browser caches the files even if you destroy the Audio object.

<img width="1216" alt="Captura de Tela 2021-12-23 às 06 18 20" src="https://user-images.githubusercontent.com/24264157/147252733-9ee8d4b6-9e1a-4199-9a9f-d1f98df79329.png">

**Comment by panchovm** [comment]
> I seem to remember in discussions with panchovm that we had decided that we didn't need to save the current playback position when switching between playback for different files.

That is correct, we decided that. Although now I wonder if that was the right decision.

I was simulating the navigation among audio results, and it feels smooth jumping between audio and playing/pausing them to see if it's a relevant result from the first focus, where the whole audio item is focused. I like the idea of `spacebar` to play/pause the on focus element, in the same way as the focus is on the audio control and audiowave.
