### ISSUE TITLE
Improve focus styles on `AudioTrack` subcomponents

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#407]
## Description
The subcomponents of the `AudioTrack` need updated focus styles. See https://github.com/WordPress/openverse-frontend/pull/399#issuecomment-963142168

## Expectation

Focus styles should match @panchovm's designs.

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
@panchovm I was mocking up a version of the audio control button in the same UI style as the search button, and this is how the normal and focused state look like if we establish that as the consistent pattern for all buttons. Do you agree with the direction?
<img width="76" alt="Screenshot 2021-11-30 at 2 35 05 PM" src="https://user-images.githubusercontent.com/16580576/144031605-7e821fe3-76a3-4bc5-9c45-9c8f92a2030b.png">
<img width="76" alt="Screenshot 2021-11-30 at 2 35 09 PM" src="https://user-images.githubusercontent.com/16580576/144031575-5f6d1c6e-d270-4deb-9059-94f970282019.png">

**Comment by panchovm** [comment]
Yes. The focus style for audio control buttons should be inside the button, not overlapping any other area.
