### ISSUE TITLE
Build DMCA form into CC Search (original #966)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#41]
This issue has been migrated from the [CC Search Frontend repository](https://github.com/creativecommons/cccatalog-frontend/issues/966)

```
Author: annatuma
Date: Fri May 15 2020
Labels: 🏷 status: label work required,🙅 status: discontinued
```
Ticket work required.

**Comment by zackkrida** [comment]
I think keeping these forms separate and using a third party service, like Google forms, is fine for now, and building out a dedicated back-end to handle this work feels out of scope for the time being.
