### ISSUE TITLE
Provide HTML code to allow CC Search to be embedded in other websites (original #505)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#42]
This issue has been migrated from the [CC Search Frontend repository](https://github.com/creativecommons/cccatalog-frontend/issues/505)

```
Author: kgodey
Date: Fri Oct 04 2019
Labels: ✨ goal: improvement,🏷 status: label work required,🙅 status: discontinued,🚧 status: blocked
```
A user reached out and asked for an embed code similar to the [OASIS OER](https://oasis.geneseo.edu/about.php) search tool to embed CC Search into their own website.
--------
### Original Comments: 

Issue author *madewithkode* commented on Thu Jan 09 2020:

>Hi, @kgodey, I would love to work on this but i need better understanding of exactly how you'd love the project to be tackled. For instance, where do I add the HTML code? Do I make a separate new file for it? I await your response.
[source](https://github.com/creativecommons/cccatalog-frontend/issues/505#issuecomment-572579522)

*kgodey* commented on Fri Jan 10 2020:

>Hi @madewithkode, this needs more definition before it's ready to be worked on. I suggest looking at one of the issues tagged "help wanted" instead: https://github.com/creativecommons/cccatalog-frontend/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
[source](https://github.com/creativecommons/cccatalog-frontend/issues/505#issuecomment-572813500)

Issue author *madewithkode* commented on Fri Jan 10 2020:

>Alright!
[source](https://github.com/creativecommons/cccatalog-frontend/issues/505#issuecomment-573056479)

*annatuma* commented on Fri Feb 28 2020:

>@panchovm noting that in Q2 (or possibly Q3, if other priorities arise) we'll need to work on what this sort of embed should look like, before it can actually be built.
[source](https://github.com/creativecommons/cccatalog-frontend/issues/505#issuecomment-592706723)

*panchovm* commented on Mon Mar 02 2020:

>Perfect. It sounds like an exciting feature.
[source](https://github.com/creativecommons/cccatalog-frontend/issues/505#issuecomment-593568418)

*zackkrida* commented on Thu Aug 20 2020:

>I'm inclined to think this would be it's own project that uses the search api. I'm not sure it would ultimately live in this repository but the issue can stay here for now.
[source](https://github.com/creativecommons/cccatalog-frontend/issues/505#issuecomment-677807231)

**Comment by zackkrida** [comment]
I'm inclined to close this! I think `search.openverse.engineering/search?embedded=true` is the best we can offer.

**Comment by dhruvkb** [comment]
Yeah, I agree on closing this. We offer
- an API for applications who want to use Search in their apps
- an embedded mode that applications can use in an iframe
- a URL structure `/search?q=...` that anyone can hyperlink to

Any more than this would be its own project that is up to the end users. It's not feasible to provide HTML code that works for third-party sites. Frankly, that should be outside the scope of this project.
