### ISSUE TITLE
RTL touchups

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#421]
## Description
While the site still functions under RTL language direction, it looks extremely unpolished and will give a bad impression (in addition to the frustrating partial translations). What follows is a list of the individual places that need to be touched up to get the site "presentable" for RTL languages.

The following descriptions are all what it should be for RTL languages. For each fix, ensure that it does not cause a regression to the LTR languages.

- [x] #426
    - The navigation items should be aligned with the left side of the screen
    - The dropdown items should not have a large leading gap
    - Should the openverse logo be on the opposite side of the openverse brand text? cc @panchovm
- [x] #424
    - The search input and button should have the correct corners rounded
    - The "I want something I can..." checkboxes should have their spacing fixed to match the LTR language spacing
- [x] #431
    - The table has a double border on the left side
    - The table is missing the border between the Source and Domain column
    - The spacing of the "Suggest a new Source" button with the text and the icon is a little off compared to the LTR version (the left side of the button has too much padding)
    - Trailing slashes for all domains listed should be removed as they get automatically put at the front of the domain in RTL languages (`https://asia.si.edu/` gets visually transformed by the browser into `/https://asia.si.edu`)
- [x] #428
    - The search bar needs to have its button and input corners correctly rounded as well as its padding adjusted for RTL
    - The "safer browsing" flag icon needs to have its padding adjusted to match the LTR language padding
    - The scroll to top button should be moved to the opposite corner
    - License icons and their corresponding text need to have their separation padding adjusted for RTL
- [x] #435
    - "Go to image's website" button needs to have its icon padding adjusted
    - The attribution box and tabs need to have their borders adjusted to be on the correct side for RTL languages
    - The plain text attribution also needs to have its quotation marks corrected as currently they're being moved around by the browser into strange places
    - The license icon needs to have its padding adjusted against the associated text
    - The information table needs to have its padding adjusted as the "dimensions" text overlaps the listed dimensions
    - The leading edge of the information/reuse table needs to be fixed for RTL languages to align with the rest of the text in the result information
- [x] #512
    - The audio tags need to be adjusted for RTL languages, their borders are all over the place
- [x] #513
  -   The audio result license icon spacing compared to the track length needs to be adjusted, see [screenshots and description in the comments](https://github.com/WordPress/openverse-frontend/issues/428#issuecomment-974044511).

## Reproduction
The easiest way to reproduce is to set your language to an RTL language (like Arabic). I'm not sure what the best way to do this is, but the way I did it was to edit to `i18n_redirected` cookie value to be `ar`. I don't know if this cookie is always present, it might exist only because I tested the WordPress.org Openverse theme translations at one point. If that is the case, then follow [the instructions here](https://github.com/WordPress/wordpress.org/blob/master/wordpress.org/public_html/wp-content/themes/pub/wporg-openverse/README.md) to set up the theme on a local WordPress install and set your language via wp-admin. Alternatively, manually edit the `dir` attribute on each page to be `rtl`. The attribute will be reset to `ltr` on each page load, so this is a very tedious option for testing as you'll have to edit the attribute every time you reload the page or navigate to a new one.

Because we will inevitably have partial translations down the line as well (for example when new strings are introduced or existing strings are updated), the site should look passable as RTL even with English strings, so for now the partial translations work in our favor as we fix these issues.

## Expectation

After fixing the issues above, the site should look polished in both LTR and RTL language directions.

For most of these the best solution might be to convert the underlying markup to use Tailwind CSS with the RTL ready start/end based styles.

## Environment

 - Device: 
 - OS: 
 - Browser: 
 - Version: 
 - Other info: 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
Based on a conversation with someone more expert in internationalization some of the text heavy pages will just have their direction attribute temporarily set to `ltr` until they become more fully translated. We can put off some work this way too.

**Comment by zackkrida** [comment]
@WordPress/openverse-frontend Could someone create new issues for the remaining RTL items?
