### ISSUE TITLE
Make Search results page ready for RTL

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#428]
- [x]  The search bar needs to have its button and input corners correctly rounded as well as its padding adjusted for RTL
- [x] The "safer browsing" ~flag icon~ needs to have its padding adjusted to match the LTR language padding: the flag icon is removed in the 'transitional styles' mockups.
 - [x]  The scroll to top button should be moved to the opposite corner
 - [x] License icons and their corresponding text need to have their separation padding adjusted for RTL: this is done in #406 and #422

**Comment by obulat** [comment]
@sarayourfriend , I don't quite understand what the last point means. This is what I can currently see in the audio results:
<img width="1072" alt="Screen Shot 2021-11-19 at 2 27 21 PM" src="https://user-images.githubusercontent.com/15233243/142615472-e82a5b7c-f2e2-4da6-bd1a-393aa5a93da1.png">

**Comment by zackkrida** [comment]
@obulat There's insufficient spacing between  the license icons, the dot and the `--:--`, I believe.
