### ISSUE TITLE
Match Bulma's breakpoints to those of Tailwind

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#440]
## Description

[Tailwind breakpoints](https://tailwindcss.com/docs/breakpoints) are now the standard for development in new components, thanks to the ease provided by the breakpoint prefixed classes. [Bulma's breakpoints](https://bulma.io/documentation/overview/responsiveness/#breakpoints) are still used by some components such as the header and navbar. Because of slight differences in their values, there are regions near the edges where both systems report different device types and lead to inconsistent styles.

## Expectation

Both systems should use the same breakpoints till one is completely replaced by the other. Ideally we would want to customise Bulma as it'll be the one to go.

## Additional context

The Bulma breakpoints can be customised by editing `src/styles/utilities/initial-variables.scss`. The use of the `$gap` variable is unclear. Please update this ticket or comment if you know how it works.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
All I know is that they say that `$gap` is used as "an offset for breakpoints" and their docs show this:

<img width="1176" alt="CleanShot 2021-11-19 at 21 03 36@2x" src="https://user-images.githubusercontent.com/6351754/142710580-e251e764-5095-4c66-b91b-d280577f46ed.png">

**Comment by dhruvkb** [comment]
Yeah! Weirdly enough, saying it is an "offset for breakpoints" is worse than not describing it at all 🤣

**Comment by obulat** [comment]
> All I know is that they say that `$gap` is used as "an offset for breakpoints" and their docs show this:
> 
> <img alt="CleanShot 2021-11-19 at 21 03 36@2x" width="1176" src="https://user-images.githubusercontent.com/6351754/142710580-e251e764-5095-4c66-b91b-d280577f46ed.png">

This is how I understand this table:

| breakpoint | value |
| --- | --- |
| $tablet |769px|
| $desktop |960 + 64 = 1024px|
| $widescreen |1152 + 64 =  1216px|
| $fullhd  |1344 + 64 = 1408px|

Please correct me if my calculations are wrong :)
