### ISSUE TITLE
Component: Content link

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#453]
## Description
We need to add the mobile version of the **Content Link component**. The Design Library has a new `small` version with all three states, as the other instances of the same Figma component.

### Props

| Name | Type | Description |
|-|-|-|
| `media` | string | One of the current media types we support (likely `IMAGE` or `AUDIO`) |
| `results-count` | number | The number of results for the indicated media type |

### Events

| Name | Associated data | Description |
|-|-|-|
| click | `media` | Indicates the media selected to narrow the search results |

## References
**[Design Library: Content link component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=558%3A2284)**

<img src="https://user-images.githubusercontent.com/895819/144045261-3bb239ff-a746-4e9a-a55d-9d3c6a305264.png" width="450">

- [Use on mobile](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A11555)
- [Use on desktop](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A34915)

**Comment by zackkrida** [comment]
@panchovm could you add a reference to the mockup(s) this appears in? I'm actually forgetting 😅

**Comment by panchovm** [comment]
I updated the initial post.

**Comment by krysal** [comment]
@panchovm Is this component ready to go? I'm not sure if the status of ticket work required is updated

**Comment by panchovm** [comment]
Yes, it's ready. [Here is the component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=558%3A2284) with those variants.
