### ISSUE TITLE
Full-width load more button

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#477]
## Problem

The load more button in the redesign is full-width and with different colors. We should replace the existing button with this redesigned version. Hopefully we can extend or adapt our existing Button component for this change.

## Description

![image](https://user-images.githubusercontent.com/6351754/144630036-850380c0-4d96-46f6-9a2d-1874f697606a.png)

Figma Mockup: 

https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A22596

### Implementation details

- On the 'image' result view, the button obscures the last row of results with a fade-in effect. We will need to determine if this positioning challenge and fade effect should be part of this PR or a subsequent one.

Example in figma: https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A14189

**Comment by krysal** [comment]
Solved by #578.
