### ISSUE TITLE
Internal Pages Menu

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#485]
Figma link: https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=25%3A2962

![image](https://user-images.githubusercontent.com/6351754/144713154-13fb52e9-b47f-459b-8109-efd6b1f65a31.png)

## Questions

- Does this need to be a named, standalone component, or just a popover + button in the header component?
- This three dot icon sticks out to me as odd. It's a lighter weight than any of the other icons in the system
- What are the focus + hover styles of these inner links? Related to a similar question in #479

**Comment by obulat** [comment]
I was thinking that it should be a part of the ContentSwitcher component because on mobile there are no dots: a click on the Content button opens both the Content switcher and the list of pages.
