### ISSUE TITLE
Going to `/photos/` without an id should not fetch

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#496]
## Description

If you go to `/search/image/`, you will first see the skeleton of the Single result page, and then be redirected to an error page. 
## Reproduction

1. Run the app with `npm run dev`,  and go to `localhost:8443/photos/`
or 
2. go to `https://wordpress.org/openverse/photos/`
3. See error.

## Expectation

I am not sure what should happen here. Some ideas:
1. We need to check the image ID in the request. We could also probably use a UUID regex, since we do not have any other image IDs. 
2. If the image ID in the request is invalid, we should redirect to the home page? or the 404 page? How do we indicate that the user was redirected because of an invalid URL?

## Screenshots

![noId](https://user-images.githubusercontent.com/15233243/145018788-fb16dfde-f888-4c0c-ae00-fe9d50578d52.gif)

You will also see the

<details>

<summary>following error messages in the console</summary>

```
[Vue warn]: Invalid prop: type check failed for prop "imageId". Expected String, got Undefined 

found in

---> <RelatedImages> at src/components/ImageDetails/RelatedImages.vue
       <PhotoDetailPage> at src/pages/image/_id.vue
         <Nuxt>
           <EmbeddedWithNavSearch> at src/layouts/with-nav-search.vue
             <Root> client.js:57
Error in fetch(): Error: [RWV] ImageService.getRelatedImages() id parameter required to retrieve related images.
    at Object.getRelatedMedia (server.js:38356:13)
    at server.js:37573:36
    at server.js:7170:39
    at Array.map (<anonymous>)
    at VueComponent.callFetches (server.js:7168:37)
    at useRelated (server.js:37578:3)
    at setup (server.js:12051:81)
    at mergedSetupFn (/Users/obulat/Documents/openverse/openverse-frontend/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:2099:113)
    at /Users/obulat/Documents/openverse/openverse-frontend/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:1915:23
    at activateCurrentInstance (/Users/obulat/Documents/openverse/openverse-frontend/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:1830:16)
    ```

</details>

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
I think both use cases should 404. Especially in light of our new 404 page: #256 
We should redirect as soon as possible if there's no image id in the url, otherwise throw a 404 later if the image request fails.
