### ISSUE TITLE
Debounce filter selection

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#505]
## Problem
If you select several filters one after another it will execute one query per filter selected (even if the query takes so long that you never end up seeing it before you select another filter).

## Description

We can debounce executing the query so that it'll only execute a query after some number of milliseconds of no filters being selected. This would prevent any unnecessary queries being executed.

## Alternatives
Require users to click some sort of "apply" button to update filters rather than updating them immediately when they change.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by anton202** [comment]
working on it

**Comment by sarayourfriend** [comment]
Thanks @anton202, it's assigned :tada:
