### ISSUE TITLE
Store filter state in cookie

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#508]
## Problem

Currently the filter "open" state is stored in local storage. This means that for SSR requests, we don't know whether to render the filters open or closed, so we always render them closed. For SSR pages, this means that if the filters are set to _open_ in local storage, there's a brief period of time when the page first loads where the filters will be closed and after the page starts loading, will completely reflow to open the filters.

## Description

There might be a more elegant way to do this but I was thinking we could store this state in a cookie instead of local storage, so that when the page is being rendered on the server we'd be able to read out the open/closed state there.

## Alternatives

I'm not sure of any but there's very well could be a more elegant solution to this problem.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
I like the idea of having the required state known before rendering. I wonder if we really need to have the filter saved 🤔 Maybe, @panchovm knows more about our previous user research: do the users want to have the filter sidebar state saved?

**Comment by panchovm** [comment]
I checked the research outcome from the interviews we ran, and I found nothing related to filter preferences. However, filters were mentioned as crucial for narrowing the results. Therefore, I prefer to show filters open and show beforehand the options.
