### ISSUE TITLE
CC Migration banner doesn't SSR

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#515]
## Description

The migration banner does not render server side so it "pops in" after the page is hydrated on the client.

## Reproduction

1. Visit https://wordpress.org/openverse/?referrer=creativecommons.org
2. Watch the top of the Openverse iframe and note the banner popping in shortly after the page finishes loading

## Expectation
The banner should be SSR rendered. We have the query param already (and we could check the referrer header anyway) so it's definitely possible to know that it should be present server side.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
@omkarg01 Great! I've assigned the issue to you. If you have any questions or would like any help on getting started, please feel free to let us know here and we will be happy to assist 😁

**Comment by omkarg01** [comment]
@sarayourfriend what could be the reason causing this issue?

**Comment by sarayourfriend** [comment]
My guess is that it has to do with this line: https://github.com/WordPress/openverse-frontend/blob/c640af62be364792a7d90608ab3ed8ccafe1a1b1/src/layouts/default.vue#L29

I'm not totally confident, but I think that on the server side, the Vuex store is not fully populated, or is only briefly initialized, in a way that doesn't take into account the fact that we can derive this state based on the query parameter. In fact, I'd almost argue that this shouldn't be in the Vuex store at all as it's not state that needs to be globalized and doesn't change. It could just as easily be a simple function to read the current query params and see if the referrer param is there.

We do hide the migration banner on navigation: https://github.com/WordPress/openverse-frontend/blob/3b7314b064fed26453f06dac4df52a3fc99847aa/src/middleware/middleware.js#L31-L33

We'd need to preserve the ability to do that... Perhaps a potential solution is to keep it in the store, but when reading the value initially to default to deriving it from the query param if the store value is still undefined.
