### ISSUE TITLE
Author link navigates inside the iframe and fails to render

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#521]
## Description

Clicking the author name on an image navigates the iframe to the resource, which will fail for some providers like Flickr

## Reproduction

1. Visit https://wordpress.org/openverse/photos/f2f10f6a-7079-4b2d-bb3f-c764e5b2d7bf
2. Click the author name under the title: "fractalx"
3. Note that the iframe will now render a browser error page.

## Expectation

I guess the only thing we can really do is open a new tab, because we can't guarantee that providers will work inside of iframes 🤷 

## Screenshots

<img width="2032" alt="Captura de Tela 2021-12-13 às 20 56 35" src="https://user-images.githubusercontent.com/24264157/145935673-ff5a94d9-ca9e-40c8-93fe-e466c3805528.png">

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
This issue is an example of #468

**Comment by sarayourfriend** [comment]
Oh, I'd say it's a duplicate of it! Closing this one in favor of that one, thanks @obulat!
