### ISSUE TITLE
Modal versions for breakpoints

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#522]
## Description
As proposed in a discussion and requested by the team, we need to add three versions of the Modal component for all breakpoints we are currently using. The Modal versions are the followings, copied from the proposal discussion:

### Modal S
A flexible full-size page-like with 8-cols, `16px` gutter, and `24px` left and right paddings. The close action is top-left aligned with a `margin-top`, `margin-left`, and `margin-bottom` of `8px`.

### Modal M
A `768px` fixed width with 8-cols, `16px` gutter, and `64px` left and right paddings. The close action is placed outside and top-right aligned with a `margin-top` and `margin-bottom` of `8px`.

### Modal L
A `1024px` fixed width with 8-cols, `32px` gutter, and `64px` left and right paddings. The close action is placed outside and top-right aligned with a `margin-top` of `16px` and `margin-bottom` of `8px`.

## References
The Modals demanded a new component: the **Close modal** button. All design documentation can be found here:
1. **Initial discussion: #507**
2. **[Modal component in Figma, Views page](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/?node-id=344%3A285)**
3. **[Close modal button component in Figma, Components page](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=1320%3A3077)**

The component is related to issue #458

**Comment by sarayourfriend** [comment]
This blocks #480 so I'll start working on this.
