### ISSUE TITLE
Rapidly clicking 'Load more results' button will cause the same page to load multiple times

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#523]
## Description

The Load more button isn't disabled while loading a new page so it is possible to click it repeatedly and cause the same page to be requested and loaded into memory multiple times.

## Reproduction

1. Go to https://wordpress.org/openverse/search/image?q=galah
2. Scroll to the bottom of the results and double click "Load more results" button
3. After the new results load, note the duplicates

## Expectation

The button shouldn't be able to cuase the same page to load multiple times.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
This issue has been solved and cannot be reproduced anymore.
