### ISSUE TITLE
Prevent width shift in VFilterButton when active filter count is single-digit

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#534]
## Problem

When a user is adding filters, and the number goes from 9 to 10, the width of the button shifts.

## Description

We can fix this by wrapping the count in its own html element, centering the contents, and adding horizontal padding. This will _also_ prevent layout shift when switching from showing the filter icon to showing the filter count.

## Additional context

This is blocked until `@nuxtjs/i18` supports `vue-i18n@9`, which allows you to combine the component interpolation and pluralization features, as is necessary to implement this.

https://vue-i18n.intlify.dev/guide/advanced/component.html#pluralization-usage

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
Closing this issue because we are going to implement the new version of the header (#1669) that does not have text for the filter button.
