### ISSUE TITLE
Query text has whitespace around quotes when no content is found

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-frontend#538]
## Description

When no results are found, the search term gets shown as `No image results for " <word> "`, with the additional whitespace between the quote characters and the word. This can be confusing, since it might lead users to believe they had whitespace in their original search term and that was why no images could be found.

## Reproduction

1. Make a search for a term that does not bring back any replies
2. Observe the spaces between the quote character and the search term 

## Expectation

The quotes should wrap the term exactly, e.g. `"<word>"` rather than `" <word> "`.

## Screenshots

![image](https://user-images.githubusercontent.com/10214785/146576755-f06da3c9-9abe-4d5e-b59a-97104c1965a5.png)

## Environment

 - Device: Desktop
 - OS: Xubuntu 18.04
 - Browser: Firefox

## Additional context

The meta search form is the related component: https://github.com/WordPress/openverse-frontend/blob/91f79fdc4eec4c33e9a8e6e347f1e5ee0b4e07a7/src/components/VMetaSearch/VMetaSearchForm.vue

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
I believe this is fixed in `main` but we can leave this open until that is redeployed and confirmed!

**Comment by hasanuzzamanbe** [comment]
I think this problem related to Vue-i18n
Here are some discussions:
https://github.com/kazupon/vue-i18n/issues/963
