### ISSUE TITLE
Add a report content action in single result views

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#543]
## Problem
The current mockups do not have an action for reporting content, and we need to add it as users can find content that needs to be reported.

## Alternatives
The current flow is a two-step process where the radio option shows different info in step two based on the alternative selected. This flow has interaction risks on mobile since it requires an internal navigation to close it and go back and forth.

The proposal is a one-step popover with the original description and reporting reasons, but it displays different content once on the same popover once clicking on an alternative. The interaction goes as it follows:
1. The content information title ("Audio information", "Image information") has a right-aligned link.
2. On hover, the link turns `dark-charcoal`.
3. On click, it opens the popover with radio alternatives unselected and the report button as `disabled`.
4. As clicking on each option, new information is displayed and the report button turns `enabled` as the info is filled correctly. See the image below for the flow.
5. In option **Other**, the text area has a character counter to assure a maximum length. See the image below for the flow.

<img width="1254" alt="CleanShot 2021-12-20 at 15 48 46@2x" src="https://user-images.githubusercontent.com/895819/146817581-16930016-5014-40c1-a26d-efb0ee306dcb.png">

I am curious to see your thoughts, especially on the following:
* **Mobile view.** The single result view is a modal that looks like a page, and it might be a good idea to show this popover as a modal since it focuses the content on a single vertical layout interaction.
* **Clicking outside**. In other popovers, clicking outside closes the box without affecting the viewing info significantly. However, this box contains flows that might frustrate users if it gets closed by unexpected interactions. Like resetting the reason info in the third option.
* **External icon size.** I talked to @dhruvkb days ago about icon sizes, and this one is based in the WordPress Design Library but scaled down to be `16px` square.

https://user-images.githubusercontent.com/895819/146820069-78532fab-b9e1-45fe-b842-ef6717bc2a33.mp4

## Additional context
The popover design has a **shadow popover** style from the [WordPress Design Library](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library).

**Comment by sarayourfriend** [comment]
> Mobile view. The single result view is a modal that looks like a page, and it might be a good idea to show this popover as a modal since it focuses the content on a single vertical layout interaction.

Agreed! A blocking modal makes the most sense on small devices for this case.

> Clicking outside. In other popovers, clicking outside closes the box without affecting the viewing info significantly. However, this box contains flows that might frustrate users if it gets closed by unexpected interactions. Like resetting the reason info in the third option.]

I think this is fine. Our Popover component already allows for this via a `hideOnClickOutside` prop that we can just set to `false` to disable that behavior. Should we add a close button to the top corner of the popover to give users an extra escape hatch (if for some reason the cancel button doesn't make sense to them? We'll also definitely need some way of closing the modal for the last "thank you screen". Either a button or a close cross in the corner that would persist on every "page" of the modal.

> External icon size. I talked to @dhruvkb days ago about icon sizes, and this one is based in the WordPress Design Library but scaled down to be 16px square.

Seems great to me! That icon is defined here:

https://github.com/WordPress/gutenberg/blob/c5d792a74365994280a8a187cc6aa459927bc36b/packages/icons/src/library/external.js#L7

**Comment by panchovm** [comment]
> Should we add a close button to the top corner of the popover to give users an extra escape hatch if for some reason the cancel button doesn't make sense to them?

That makes a lot of sense. I will add it.

> Seems great to me! That icon is [defined here](https://github.com/WordPress/gutenberg/blob/c5d792a74365994280a8a187cc6aa459927bc36b/packages/icons/src/library/external.js#L7)

If `viewBox` is set to be `24px` square, then changing it to `16px` and scaling it down should not be a problem? I am asking this since I was following the diagram below, where the minimum size is set to `24px` [6 is 24px, 8 is 32px (~35px), 10 is 40px, 12 is 48px (~46px), 14 is 56px (~53px) and 20 is 80px (~75px)].

<img width="317" alt="Screenshot 2021-11-30 at 4 43 28 PM" src="https://user-images.githubusercontent.com/895819/146929490-474c69ec-e424-4ddf-a6c0-3e52dfb84126.png">

**Comment by krysal** [comment]
Saving clicks is always welcome, that's a really nice improvement here. Agree with the modal on mobile, as the feedback text/textarea can take up a good portion of the screen, the single result page isn't a modal itself on mobile, right?

As for the icon, SVG scale well, and 16px is a pretty common size so it should not be a problem I think.

**Comment by panchovm** [comment]
> the feedback text/textarea can take up a good portion of the screen

I think we should limit the textarea size to fit the character limit of the message. 

> the single result page isn't a modal itself on mobile, right?

I have been calling it modal in the [Design Library](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=1327%3A3992), but not sure about the implementation.

**Comment by panchovm** [comment]
The [Releases file](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/?node-id=133%3A6869) has been updated with the mockups for desktop and mobile.

One behavior I was thinking of is that once the modal version on mobile is opened, the box height increases as the user clicks on options. The box should not move its position; otherwise, it will break the filling process and be frustrating.
