### ISSUE TITLE
Automatic updating of wp-locales.json on `main`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#546]
## Problem

Currently when changes to wp-locales.json happen, we rely on someone manually opening a PR to update it or to include it as an unrelated change in another PR.

## Description

Instead we could create a post-merge action to update `main` with the latest wp-locales.json when changes exist.

## Alternatives

Could just keep doing what we're doing, but it isn't the best DX.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
I'm interested in working on this to learn more about GitHub actions but not sure when I'll be able to work on it. If anyone else wishes to pick it up before me feel free!

**Comment by obulat** [comment]
This issue has been resolved, and we update locale files automatically or not keep them in the CI and re-create them on every build.
