### ISSUE TITLE
Add E2E tests to CI

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#554]
## Problem

It is currently possible to catastrophically break the frontend in a PR that seems unrelated without knowing: https://github.com/WordPress/openverse-frontend/pull/551

## Description

We need to run the E2E test suite in CI to help prevent this.

## Additional context

@dhruvkb recommended we look into this package to facilitate this: https://github.com/bahmutov/start-server-and-test

However, it's just occurred to me as I write this that we should run the E2E tests with the wp.org theme wrapper, to most closely replicate the production environment.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
Closing this issue as the #555 and adding more tests after it have added decent E2E check to our CI. We can, however, open a new issue for the new E2E tests that we should write.
