### ISSUE TITLE
Use new API URLs in requests to avoid redirects

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#556]
## Problem

The API URL structure changed a little bit when the regular URL conf was replaced with DRF router. Now, there are trailing slashes, and the requests from the frontend are redirected using 301.

## Description

It would be cleaner to add the trailing slashes to the requests by the frontend to avoid redirects.

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
Thanks for checking at this. I'll label this as a high priority as this is causing the "Report this content" feature to fail.

<img width="757" alt="CleanShot 2021-12-23 at 11 12 01@2x" src="https://user-images.githubusercontent.com/9145885/147259578-40c2369b-2998-497b-8994-60afa9f33a89.png">
<img width="1410" alt="CleanShot 2021-12-23 at 11 15 29@2x" src="https://user-images.githubusercontent.com/9145885/147259583-e704925d-4b21-4255-80c4-bcab94eae935.png">
