### ISSUE TITLE
Search results title

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#576]
The newly-redesigned search results pages show the search query as a title, above the results. This title is a quite a large size on the 'all' results view, and smaller on other endpoints.

All results figma: https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A22543
Other results figma: https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A14189

**Comment by krysal** [comment]
Done in #577.
