### ISSUE TITLE
Ignore changes to `wp-locales.json`

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#579]
## Problem

Currently, `wp-locales.json` is updated every time `pnpm run dev` is run, and whenever a translation percentage changes for any locale, `wp-locales.json` shows as changed. This adds noise to every PR.

## Description

We can add `wp-locales.json` to .gitignore so that it is not committed with every PR.

## Additional context

We have done the same for `/src/locales/scripts/valid-locales.json`

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
I was hoping we could do this—thanks for the confirmation!
