### ISSUE TITLE
No results page

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#602]
## Problem
We need to show a friendly message when there are no results. The page should encourage people to try a different search or browse on the additional source sites.

## Description
The mockup is available in the [Releases file](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A6869) as both desktop and mobile. I will add the image as an exportable asset ASAP.

|Desktop|Mobile
|:---|:---|
|![imagen](https://user-images.githubusercontent.com/895819/149401278-35b26799-77b4-4fc7-a632-6a23179086e4.png)|<img src="https://user-images.githubusercontent.com/895819/149401248-05c861e2-e953-4093-9605-479e811b3339.png" width="300">|

## Additional context
On desktop, the source site is a border version of the [secondary button](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=558%3A2286), while on mobile is the same as desktop but full-width and `16px` top and bottom padding. I was not sure about adding these elements as components since are used only on this page. Any ideas on this?

**Comment by dhruvkb** [comment]
@panchovm I think even components that appear once should be a part of the component library.

While we are under time constraints we will sometimes make one-off components to quickly get something done but in the long term our idea should be that any component in use across the site can be found in the library.

**Comment by panchovm** [comment]
Perfect. I added the task for the after release. Thanks

**Comment by panchovm** [comment]
Here is attached the image compressed to have a smaller file size.

[Depressed musician image.zip](https://github.com/WordPress/openverse-frontend/files/7872350/Depressed.musician.image.zip)
