### ISSUE TITLE
Cannot return from 404 page

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#612]
## Description

Once you reach the 404 page, it is impossible to return to any other page other than with a page reload.

## Reproduction

1. Run the dev server.
2. Search for any search term. 
3. Click on the video tab, this will result in a 404 and take you to the 404 page.
4. Click the Openverse logo in the top-left. The URL will change but it will still show the 404 page.
5. Click the Openverse text link in the message. It won't work.
5. Try searching using the Search bar. It won't work but that's a different error.

    ```
    TypeError: _store_search__WEBPACK_IMPORTED_MODULE_8__.mediaSpecificFilters[searchType] is not iterable
    ```

## Expectation

These methods of navigating away from the 404 page should work.

## Environment

 - Device: computer
 - OS: MacOS Monterey 12.1
 - Browser: Vivaldi (based on Chromium)
 - Version: 96.0.4664.137 (Official Build) (arm64)

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Ah, there must be some global state needed that's not in the 404 layout or something?

**Comment by dhruvkb** [comment]
Not sure which PR or commit fixed this, but this has disappeared from `main`. Closing.
