### ISSUE TITLE
Preview link is being included in freesound download formats

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#626]
## Description

The preview audios shouldn't be included in the list of download formats for Freesound. To respect Freesounds authentication requirement for downloads, we should only include the proper download URL that the frontend should display for the download button and none of the preview files.

## Reproduction

1. Visit http://localhost:8443/audio/632d0076-fdbd-4919-8b8f-b498ef246ee8
2. Notice that the preview file is included in the download button dropdown.

## Expectation

Preview files should not be automatically included in the download dropdown.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
I believe including the preview link was actually intentional while we got around the link to the full audio, if not, there is no point in having this link in the catalog either.

**Comment by sarayourfriend** [comment]
> if not, there is no point in having this link in the catalog either.

Which link would we be excluding? From my perspective we need both the download and the preview link.

**Comment by krysal** [comment]
My bad, I was thinking the preview link was being included among download links from the catalog, but checking again it is indeed just a problem of the single result page here. Good find!
