### ISSUE TITLE
Content switcher with Audio as beta and Video as Meta search

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#631]
## Problem
As discussed on the public channel, the audio releases will be in Beta as we are still improving the integration. In parallel, openverse displays a list of additional sources for video content under an open license. None of the current mockups include these two situations.

## Description
Here is a new version of the content switcher showing both actions: Audio in Beta, and Video as Additional type. Here is a screen recording showing the interaction.

### Desktop
https://user-images.githubusercontent.com/895819/149994168-cb7bb81e-aec1-400c-bc8b-2037312bdef7.mp4

### Mobile
https://user-images.githubusercontent.com/895819/149994715-a9822e9e-555d-4345-89f9-b584574cc464.mp4

Note: The video above misses a step. After selecting the video option, the menu closes and video results page is visible. The video item selected is only visible once opening the menu on video results page.

## Additional context
The Beta pill is a new component requested on issue #630

**Comment by obulat** [comment]
@panchovm, I think this issue can be closed now since Audio is not in Beta anymore, and we can see the additional types with the feature flags.

**Comment by panchovm** [comment]
Perfect. That sounds great. Thanks Olga
