### ISSUE TITLE
Display a loading animation on the play/pause button when an audio is being loaded

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#632]
## Problem

Switching between several audio tracks results in small (or sometimes larger) periods of seeming unresponsiveness while the audio track's URL is set to the audio element's current `src` and the audio loads.

Try playing several different audio tracks in a related audio section one after the other to see this feeling of unresponsiveness.

## Description

We could add some kind of loading animation to the play/pause button to indicate that the audio track is being loaded.

cc @panchovm for designs. Can we just use the loader? Or a different spinner? Maybe something else.

## Alternatives

Somehow pre-fetch audio tracks when someone hovers over the play/pause button for a determined period of time, or when someone seeks the audio.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
@panchovm and I actually just identified this too, during our screenshare to fix his local git merge issues. 👍

**Comment by panchovm** [comment]
Resuing an existing pinner related to WordPress sounds better to me. I wonder how the [Gutenberg spinner](https://wordpress.github.io/gutenberg/?path=/docs/components-spinner--default) might look like with the `dark-charcoal` as background color and the moving dot in `white`.

**Comment by sarayourfriend** [comment]
Gutenberg also has [this spinner](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-spinner--default) that I think they'll eventually move towards using instead of the dot one you linked (but I honestly don't know).

**Comment by panchovm** [comment]
I think [this spinner](https://github.com/WordPress/gutenberg/pull/37551) is the last version.

**Comment by panchovm** [comment]
I was recreating the spinner design and here is a quick prototype of how it might look like. I am using a `24px` size with a `1.5px` for border thick, `dark-charcoal-70` for the circle, and `white` for the animating section.

<img src="https://user-images.githubusercontent.com/895819/150022793-e1f704c7-81ee-47c7-893b-6af521e35f6f.png" width="75">

![CleanShot 2022-01-18 at 18 33 03](https://user-images.githubusercontent.com/895819/150022425-de5a9474-4788-4411-ba9c-ebeed0ee01ef.gif)
