### ISSUE TITLE
Audio single result page does not show default artwork if no thumbnail is available

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#636]
## Description

The search results show default artwork for audio results that do not have a thumbnail. The single result page shows a broken image.

## Reproduction

1. Go to single audio result.
2. See error: the broken thumbnail in the audio details section. Note that related audio correctly shows the default artwork.

## Screenshots

<img width="973" alt="Screen Shot 2022-01-19 at 7 49 08 AM" src="https://user-images.githubusercontent.com/15233243/150078722-b0acaced-443c-4ed7-a853-9680fbe5730a.png">

## Expectation

For audio without thumbnails, single result page should show default artwork.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
This issue occurs because `VAudioDetails` does not use the `VAudioThumbnail` component but rather a plain `<img>` tag.
