### ISSUE TITLE
Header searchbar is missing placeholder text

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#644]
## Description

The header searchbar doesn't have default placeholder text.

## Reproduction

1. Visit https://search-staging.openverse.engineering/search/image or https://search-staging.openverse.engineering/search/audio
2. Observe the searchbar is empty
3. Ignore that the pages kind-of work and there's strange layouts!

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
@panchovm what _should_ the default placeholder be on the search routes?

**Comment by panchovm** [comment]
The default placeholder for the search bar should say `Search for content`. If I am understanding correctly what you mean with search routes

**Comment by sarayourfriend** [comment]
@zackkrida Going to open a PR for this.
