### ISSUE TITLE
Make sure all reporting forms work

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#66]
We need to make sure all content reporting forms work. If we need to create new google forms or anything, please feel free to do so and just make sure my a8c email address has ownership access to the google sheets/forms/whatever.

**Comment by dhruvkb** [comment]
Forms:

| Title | Existing URL | New URL |
|-|-|-|
| DMCA Takedown Request Form | [🔗](https://docs.google.com/forms/d/e/1FAIpQLSdZLZpYJGegL8G2FsEAHNsR1nqVx1Wxfp-oj3o0h8rqe9j8dg/viewform) | [🔗](https://docs.google.com/forms/d/e/1FAIpQLSd0I8GsEbGQLdaX4K_F6V2NbHZqN137WMZgnptUpzwd-kbDKA/viewform) |
| How are you using this image? | [🔗](https://docs.google.com/forms/d/e/1FAIpQLSeSApxNMup8Ujt-8Vjv53ngltzhJeaHspMykHCD8VKQ39yXAA/viewform) | [🔗](https://docs.google.com/forms/d/e/1FAIpQLSegPUDIUj_odzclJhhWRfPumSfbHtXDVDCHqRfFl7ZS8cMn2g/viewform) |

**Comment by krysal** [comment]
Will the feedback and bug report forms be removed? There  is no longer an entry in the 'Resources' menu for it (old [feedback](https://search.creativecommons.org/feedback) page), but a link is still present at the bottom of the  `/meta-search` page.
