### ISSUE TITLE
Mobile audio search result is using wrong layout size

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#668]
## Description

Audio search result is incorrectly using `m` audio track size, instead of `s`. Because of this, the track doesn't fit in the screen, and the play button isn't visible, too:

<img width="696" alt="Screen Shot 2022-01-21 at 1 03 59 PM" src="https://user-images.githubusercontent.com/15233243/150507741-61ad106c-3c6e-402d-b7fa-33c670b1d69c.png">

## Reproduction

1. Run the app and open it in a 350px-wide screen.
2. See error.

## Expectation

Mobile screen should use the small layout, and the play button should be visible

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
Expected logic:

if breakpoint is mobile: `s`
else if filter is visible: `l`
else: `m`
