### ISSUE TITLE
Search page titles are hidden when results are loading

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#670]
## Description

The search results title of any of the `/search` endpoints is hidden while results are loading. This causes an unpleasant layout shift and a mis-alignment of our skeleton/placeholder UI. 

We need to refine our state so that the title is _only_ hidden when there are no results for a  completed search.

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
I think that we can solve this by adding a `started` property to the `media.state.fetchState` in the store.
It will be set to `false`:
1. initially.
2. when the query (search term or filters) changes.
3. when the content type changes, and there are no items fetched for this content type (this way, we can show the items that have already been downloaded for the same query).
And it will be set to true whenever `FETCH_MEDIA` is called for the media type.

Then, we will be able to fine-tune the conditions when we show search meta data. We will be able to differentiate the two `noresult` states: when the search returned no results, or when the search hasn't returned any data yet.

In the meantime, as a quick fix, we can simply omit the check for no results in the `VSearchGrid` component, and always show the heading, even if there are no results. This improves the layout for any search that does return a result, and shows the search term a little too prominently when there are no results.
