### ISSUE TITLE
Single audio view lacks 'return to results' link

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#671]
## Description

Currently images have a nice 'return to results' link that effectively mimics the browser back button. Audio results do not.
This will be fixed by #480, I'm not sure if we need interim solution until then.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
This is blocked by design work cc @panchovm

**Comment by panchovm** [comment]
@krysal is working on the image' single result content in #682, and we should reuse the back action section instead of making a mockup that we will delete once we have the modal implementation done.
