### ISSUE TITLE
Small audio track has inconsistent spacing

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#672]
From @panchovm:

It works great and smoothly. I just noticed three things.
1. I'm not sure if we set `130%` for the `line-height` of **Description bold** style, converted to rem value. It seems bigger, as the red area in the image below shows.
2. The spacing between title, author, and other meta-data info is inconsistent; blue area in the image attached. The mockup has a `8px` spacing separating those three rows.
3. The spacing between CC icons should be `2px`. 

<image src="https://user-images.githubusercontent.com/895819/150529614-99c19b2a-4fca-4db8-8311-dc0c36176be6.png" width="400">

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
@panchovm does this seem fixed?

The lines of the title are now closer.
![image](https://user-images.githubusercontent.com/16580576/150554289-eff39007-5348-40aa-864c-4c1851d7d2be.png)

The orange and purple regions are both 8px height.
![image](https://user-images.githubusercontent.com/16580576/150554329-27574fad-945b-4875-ae12-4f43bfb15540.png)

**Comment by panchovm** [comment]
That looks better ✨ .

Title's line-height will always bring us headaches as Figma and browser render the spacings differently. It is something that we might tackle in the future. But for now, this looks cleaner 👍

**Comment by zackkrida** [comment]
There's a cool library that fixes browser's terrible, incorrect x-height for fonts: https://seek-oss.github.io/capsize/ I haven't had a chance to implement it in a project yet

**Comment by panchovm** [comment]
Two more comments regarding spacings, visible in the image attached:
1. There is a spacing between header and content area bigger than spacing between audio items. I would keep it the same. Blue rectangle in the image.
2. And spacing between audio items should be `32px`. Red rectangle in image.

<img src="https://user-images.githubusercontent.com/895819/150569775-61813be3-3f90-4003-b683-b99c0dd4030f.png" width="400">
