### ISSUE TITLE
Audio track title truncation

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#673]
## Description

Currently audio track titles can be any length, which can really alter the appearance of the UI. We should constrain these to one or two lines:

> one line 
<img width="465" alt="CleanShot 2022-01-21 at 08 13 29@2x" src="https://user-images.githubusercontent.com/6351754/150533106-f8cb462d-4d35-4fb1-b582-cd0ce3122e82.png">

> two lines
<img width="572" alt="CleanShot 2022-01-21 at 08 13 54@2x" src="https://user-images.githubusercontent.com/6351754/150533112-97164c5f-d720-4dff-a954-adcd813a8b77.png">

@panchovm which of these do you think is better?

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by panchovm** [comment]
I vote for a third one, the `Row L` component. It seems better to use it for breakpoints where we see the viewport space reduced. The only component version where titles look good is on mobile is in `Row S`.

Notice that `Row L` also truncates audio title, but the remaining space is safer than `Row M`.

### Row L
<img width="1062" alt="CleanShot 2022-01-21 at 10 22 17@2x" src="https://user-images.githubusercontent.com/895819/150534171-6ddae84c-f083-4dc0-a8ff-0b547c4b92e6.png">

**Comment by zackkrida** [comment]
@panchovm Currently, `L` is used when the filters are open, and `M` is used when they are closed. Are you suggesting we use `L` all of the time on desktop?

**Comment by panchovm** [comment]
No. I meant to use `Row L` in breakpoint `md` (from 768px to 1023px), and when filters are open, keeping the L version but with the wave and audio info area smaller.

Here is a screenshot with viewport as `900px` width.

<img width="700" alt="CleanShot 2022-01-21 at 11 00 30@2x" src="https://user-images.githubusercontent.com/895819/150539746-3c6711e0-d3c5-47ec-bcce-33cc50078cdd.png">
