### ISSUE TITLE
Spacing between items in audio results

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#674]
## Problem
The current implementation has a spacing between audio elements of `24px`. This looks tight and slightly noisy as artwork images and audio content information are condensed on the left side.

<img width="1419" alt="CleanShot 2022-01-21 at 10 28 42@2x" src="https://user-images.githubusercontent.com/895819/150535145-1ef9554f-1967-4d36-aec4-f2110a92635c.png">

## Description
In Releases file, the spacing is `56px`, but I played with the inspector and `40px` gives enough white space to the page. See the image below.

<img width="1412" alt="CleanShot 2022-01-21 at 10 31 29@2x" src="https://user-images.githubusercontent.com/895819/150535587-d8b265b9-5cf1-491c-b0fc-e2475365e285.png">

**Comment by dhruvkb** [comment]
@panchovm I updated the page in #679. If 40px feels okay to you, do update the Release mockups at your convenience.

**Comment by panchovm** [comment]
Mockups in Releases were updated with this new spacing
