### ISSUE TITLE
Enabling a filter pushes the content downwards

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#676]
## Description
On desktop, enabling a filter pushes the whole area downwards. I noticed that filter and clear action area increases with this action, and a `footer` element appears hidden.

## Expectation
Activating any filter and showing the clear action should not move the content.

## Screenshots
<img src="https://user-images.githubusercontent.com/895819/150546413-96c070d6-7e09-4424-9027-fd333555853b.gif" width="350">

**Comment by dhruvkb** [comment]
While #684 does fix this slight movement, we will still need to modify the designs to accommodate languages with longer phrases for 'Filter results by'

https://user-images.githubusercontent.com/16580576/150627964-9ea7ae40-0acf-4515-aa38-dd674319cc49.mov
