### ISSUE TITLE
Audio waveform progress bar extends beyond the end of the waveform body

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#692]
## Description

When playing an audio file all the way through to the end, the progress bar will extend beyond the end of the waveform body.

I'm not sure what causes this, but it seeems like it would just be a small math issue or more likely we're ignoring something critical when pulling the [waveform dimensions from `clientWidth`](https://github.com/WordPress/openverse-frontend/blob/0ebfbe66c923c548954b38051d1dcad4fd54b539/src/components/VAudioTrack/VWaveform.vue#L294).

## Reproduction

1. Run main and go to an audio search that includes a short file (it's easiest and most prominent on short files) like http://localhost:8443/audio/5365bca5-7bd8-4344-b8e4-dad1cf219456
2. Play the audio file through to the end
3. Note the progress bar, timestamp, and focus bar (when focused) extending beyond the end of the waveform body.

## Expectation

The progress bar should end exactly at the end of the waveform body.

## Screenshots

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by demophoon** [comment]
:wave:
