### ISSUE TITLE
[i18n] Pluralized translations are not downloaded

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#702]
## Description

Plural translations for languages that use more than one noun variant for plurals is incorrect.

In Russian, there are 3 variants of 'images' plural, depending on the number. 

The 3 variants are available [on `translate.wordpress.org` ](https://translate.wordpress.org/projects/meta/openverse/ru/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=12384747&filters%5Btranslation_id%5D=88548343):

<img width="545" alt="Screen Shot 2022-01-25 at 7 47 17 AM" src="https://user-images.githubusercontent.com/15233243/150928203-0c73775c-65e1-497b-aa75-cadf744a8ea4.png">
However, the `ngx` `json` file exported from GlotPress, only contains a single variant, so the translation is often incorrect:

<img width="341" alt="Screen Shot 2022-01-25 at 7 46 51 AM" src="https://user-images.githubusercontent.com/15233243/150927626-2d931ea1-dda1-4054-abae-90a6e9192b66.png">

## Reproduction

1. Look at the `ru.json` file inside `src/locales/` directory.
2. Find  the following key that uses plurals: `"browse-page.all-result-count-more"`.
3. See error: only 1 variant  "Более {localeCount} изображения", instead of the following variants available in the `po` export:
```
#. Do not translate words between ### ###.
msgctxt "browse-page.image-result-count-more"
msgid "Over ###localeCount### image results"
msgid_plural "Over ###localeCount### image results"
msgstr[0] "Более ###localeCount### изображения"
msgstr[1] "Более ###localeCount### изображений"
msgstr[2] "Более ###localeCount### изображений"
```

## Expectation

All of the results should be downloaded. So, for `browse-page.image-result-count-more` key, the value should be:
`"Более {localeCount} изображения|Более {localeCount} изображений|Более {localeCount} изображений"`

## Additional context

Ideally, the `json` file should have all the available variants. However, it might be faster for us to use `.po` files, and convert them back to the `json` format.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by swissspidy** [comment]
Is there a reason why you use this somewhat outdated NGX-Translate format? NGX-Translate does not support plurals at all, they recommend using MessageFormat for that.

I'd definitely suggest using one of the other available formats and converting it to your needs.

**Comment by obulat** [comment]
Thank you for your comment, @swissspidy ! I wasn't aware that NGX-Translate is an old format. Which `JSON` format would you recommend us to use? The `Vue-i18n` that we are using has a nested `JSON` with i18n messages, something like this:
```
{
"header": { "title": "Openverse" },
"browse-page": { 
  "result-count": "Более {localeCount} изображения|Более {localeCount} изображений|Более {localeCount} изображений"
  }
}
```

**Comment by swissspidy** [comment]
WP core itself uses the Jed 1.x format, which you might be able to convert to your needs.
