### ISSUE TITLE
Incorrect text on the content links

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#706]
## Description

Currently, the content links on the 'All' view both show the text for 'N results' instead of using 'N image results' for image link and 'N audio results' for the audio link:

<img width="770" alt="Screen Shot 2022-01-25 at 3 07 48 PM" src="https://user-images.githubusercontent.com/15233243/150974470-c0f24f45-7b61-4f3f-83b3-b17bcb1a7c90.png">

## Expectation

The content link should have a media-specific label (`image results` and `audio results`)

## Additional context

This is caused by using the default argument (`ALL_MEDIA`) when computing the label, and not passing the actual media type.

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
I think that would be redundant with the 'Images' and 'Audio' headings already present in each button. It's also not in the mockups:

https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A22596

<img width="660" alt="CleanShot 2022-01-25 at 07 14 40@2x" src="https://user-images.githubusercontent.com/6351754/150975197-9b850734-e03d-4d34-8a89-2aed76c296f1.png">

**Comment by obulat** [comment]
> I think that would be redundant with the 'Images' and 'Audio' headings already present in each button. It's also not in the mockups:
> 
> https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A22596
> 
> <img alt="CleanShot 2022-01-25 at 07 14 40@2x" width="660" src="https://user-images.githubusercontent.com/6351754/150975197-9b850734-e03d-4d34-8a89-2aed76c296f1.png">

Oh, this is nice! It simplifies things a lot for translation.
