### ISSUE TITLE
Filter button pushed down below header on medium screens

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#714]
## Description

Likely caused by #688 the content switcher now pushes the filter button to a second row on small-ish displays:

<img width="778" alt="CleanShot 2022-01-25 at 11 09 11@2x" src="https://user-images.githubusercontent.com/6351754/151014426-b21f218d-c412-4574-a771-71558f45eb63.png">

## Reproduction

1. 
2. 
3. 
4. See error.

## Expectation

We might just want to show the mobile header a bit earlier.

## Environment

 - Device: 
 - OS: 
 - Browser: 
 - Version: 
 - Other info: 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
I merged #712 just now, that could not have caused the bug on `main`?

**Comment by zackkrida** [comment]
Oops, meant #688, apologies and edited!
