### ISSUE TITLE
Action button style on Box L and Box M

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#730]
## Description
The `hover` state of **Box L** and **Box M** does not change the control button style according to the [Design Library definition](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=314%3A7372). 

<img src="https://user-images.githubusercontent.com/895819/151377366-2cc6cd20-86b1-4b62-9b87-5ff7158c9225.gif" width="200">

## Expectation
The control button changes its background color and icon color as shown in the screenshot below.

<img width="200" alt="CleanShot 2022-01-27 at 11 23 21@2x" src="https://user-images.githubusercontent.com/895819/151377738-ad9c0c5a-7ac9-4d82-8542-2bff67306f2c.png">

**Comment by anton202** [comment]
@panchovm after clicking the play button should the button be with black background and the pause icon in white?
