### ISSUE TITLE
ImageGrid is not showing license icons

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-frontend#757]
## Description

The `ImageGrid` component is showing only white circles where the license icons should go. To see this bug go to the image results page selecting "Images" in the content type or see the Related Images on the details page view of any image.

## Expectation

The license icons should show on hover on desktop and always on mobile.

## Screenshots

![CleanShot 2022-01-31 at 10 46 42](https://user-images.githubusercontent.com/9145885/151814807-160fe7e7-ba2a-45d9-948a-21a484813264.gif)

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
I've tested and this isn't an issue related to our production infrastructure, and can be safely closed. This was fixed elsewhere, although we haven't identified the exact PR.
