### ISSUE TITLE
Audio title in global player component

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#758]
## Description
On mobile, the global player does not display the audio title correctly. With long audio titles, it shows all characters and blocks the wave area for its interaction. In other cases, it was impossible to close the player.

## Expectation
It should show the audio title in one row with truncated text until reaching the close button area, and be aligned vertically. I would suggest moving upwards the "go to top" button above the player as a transitional solution until we work on a new proposal.

## Screenshots

<img src="https://user-images.githubusercontent.com/895819/151816456-5d2b0549-3c49-459e-903c-531bc865ed42.jpg" width="350">

<img src="https://user-images.githubusercontent.com/895819/151816461-53621661-1a9f-4c0c-b0d8-c4ff6ac94e2b.jpg" width="350">

**Comment by krysal** [comment]
It seems that the back to the top button is also interfering, right?

**Comment by krysal** [comment]
Solved in #773
