### ISSUE TITLE
Closing the global audio player does not stop audio playback

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#775]
## Description

Closing the global audio player does not stop audio playback. When you close it, the audio continues to play.

## Reproduction

1. Go to `/search/audio?q=birds` with a small width viewport and play an audio
2. In the global player, click the `x` to close the global player
3. Note the audio continues to play

## Expectation

The audio should stop playing.

At least I think so. It seems counter-intuitive to me that closing the global audio player _doesn't_ stop the playback.

## Additional context

This should be a matter of calling `activeAudio.value.pause()` in the click handler for the close button.

Found while testing https://github.com/WordPress/openverse-frontend/pull/773

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
Fixed in #1335.
