### ISSUE TITLE
Explore visual regression testing

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#787]
## Problem

Because Openverse strives to be very accessible across language, screen size, and input devices, it can be challenging to sufficiently test every pull request against every application state. Additionally, Openverse currently contains a fair bit of old/dead code. Changing one thing can have unexpected consequences through the system (a recent example is #786). 

All of this points to a problem in our ability to test for visual changes across the system.

## Description

We should explore implementing visual regression testing[^1] or a similar approach to generating visual information about the application after a changeset is made. Some proposed ideas include:

- Paid services like [Percy](https://percy.io/)
- Custom solutions:
  -  A GitHub action that generates manual screenshots of the application in various states and routes, using [Playwright](https://playwright.dev/)
  - Using Playright's [existing visual regression testing](https://hackernoon.com/visual-regression-testing-with-playwright) support

## Alternatives

We could perhaps make our e2e tests more robust and hope for the best, or use more traditional UI snapshot tests to try to catch these types of errors.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

[^1]: https://www.browserstack.com/guide/visual-regression-testing

**Comment by sarayourfriend** [comment]
Closing in favor of the RFC #891
