### ISSUE TITLE
Modal on Windows has two scrollbars

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#79]
When you open the filters modal in a narrow screen on Windows, you see two scrollbars on the right. 

![image](https://user-images.githubusercontent.com/15233243/121477910-1570e480-c9d1-11eb-818d-45609a72d90f.png)

It doesn't happen on MacOS or Android. 

The problem is that we have `overflow-y: auto` both on the modal and the container inside of it. And it behaves differently  on different platforms.

**Comment by saroj-b** [comment]
Can I take this issues ?

**Comment by sarojvrc** [comment]
Can I take this issue?

**Comment by zackkrida** [comment]
Sure @sarojvrc

**Comment by sarojvrc** [comment]
thanks @zackkrida

**Comment by zackkrida** [comment]
Hi @sarojvrc are you still interested in looking at this?

**Comment by sarojvrc** [comment]
Is it possible to create Gitpod.io to work? On my system getting so much lag.

**Comment by dhruvkb** [comment]
@sarojvrc if you have a free, paid or open-source subscription to GitPod, feel free to use it. We wouldn't want to place any restrictions on how and where you write code.

**Comment by sarojvrc** [comment]
I don't have any subscription to GitPod. I'm asking you if any subscriptions.

**Comment by zackkrida** [comment]
@sarojvrc we do not. Where are you seeing lag, perhaps we could help? Is it during `npm install`, `npm run dev`, etc?

**Comment by zackkrida** [comment]
Closing, as this modal no longer exists in the redesigned Openverse.
