### ISSUE TITLE
Move analytics server `sessionId` to localstorage; rename.

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#791]
## Problem

Currently the frontend uses a session cookie (one that expires upon the user closing their browser) to store a persistent identifier for Openverse users. This is a randomly generated [v4 uuid](https://github.com/uuidjs/uuid#uuidv4options-buffer-offset).

https://github.com/WordPress/openverse-frontend/blob/4dc241dbdd8d1a9e103ea0742d9c17850db3c96c/src/utils/session-id.js#L26

We would like to remove cookies from Openverse, as this allows us to aggressively cache our frontend to reduce cost and traffic to our origin servers. 

## Description

We should consider using `localStorage` or `sessionStorage`. The later and lesser-known `sessionStorage` is perhaps the most accurate representation of a 'session' here—it persists for the lifespan of a _browser tab_. So switching to that could actually give us more useful data in the analytics server.

## Alternatives

We could keep this as a cookie and lose the ability to cache or pages, or consider removing session data from our analytics server.

## Additional Information

Doing this would also allow us to remove cookie related js dependencies.

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
SessionStorage does indeed seem to be the better choice for this.

**Comment by sarayourfriend** [comment]
This needs a little thought put into it, in particular around how to ensure that we're actually using the correct session id when SSRing a page within the same session.

@zackkrida and ideas of how to do that?

The initial render is easy enough, just have the SSR generated session ID stored in the Vuex store and upon client-side hydration push that into session storage.

The only thing I could think is to do something like always generate a new ID on the SSR side, and upon client-side hydration, check if the generated session ID matches the one in session storage. If not, replace the session storage with the SSR one and then send some kind of signal to the analytics server tying the two together?

Unless we're defining a "session" as a single SPA load of the page. That's probably the main use case anyway and we don't necessarily need "long lived session ids" do we? It _could_ be useful to tie multiple session ids to each other when possible, I don't think that would violate any privacy promises we've made as it wouldn't aid in identifying a user any more than the existing session ID would.

Maybe let's stick with the short-lived, ephemeral session IDs that only exist once per SPA load? In that case we don't even need to store it in session storage at all. If in the future we want to be able to analyse longer-lived sessions then we can look into tying sessions together into a linked-list type structure of session ids stored on the analytics server.
