### ISSUE TITLE
Image results sometimes `undefined`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#799]
## Description

https://sentry.io/share/issue/c5b2c3a5b8994e3ba29b2e8955435a5e/

The problem appears to be with this block of code:

https://github.com/WordPress/openverse-frontend/blob/3aaf038f5f301df5bab14412ec2ea928b560063b/src/components/VAllResultsGrid/VAllResultsGrid.vue#L100-L104

Sometimes `media['image']` is undefined.

## Reproduction

Not sure how to reproduce. Maybe if you get a result that only has audio? I tried a few different things by searching for results where only audio results come back (like `/search/?q=country%20village%20backyard%20or%20front%20yard%20driveway`) but I couldn't get the error to happen.

The only place where I think `state.results[IMAGE].items` could get set to `undefined` is in the `SET_MEDIA` mutation which is called by `FETCH_SINGLE_MEDIA_TYPE`.

Seems like the _right_ solution here would be to prevent undefined from getting committed, so probably adding something in `FETCH_SINGLE_MEDIA_TYPE` to prevent that from happening would be the way to go. Potentially there's a 400 level response code but that isn't sending a `results` property? 🤔 

## Expectation

A media results array should never be undefined. The worst case is that it should be an empty array.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
This could be a good first issue for someone wanting to better understand the frontend data store 🙂

**Comment by zackkrida** [comment]
I'm quite confident this is fixed; closing!
