### ISSUE TITLE
Search results should output a noindex directive

### ISSUE THREAD

**Issue by jonoalderson** [WordPress/openverse-frontend#808]
## Description
Search results pages, like https://wordpress.org/openverse/search/?q=cat, should output a 'noindex' meta robots directive; either in the existing meta robots tag in the header, or as part of an additional meta robots tag.

Fixing this is critical, as part of our ongoing SEO firefighting efforts across the wp.org ecosystem.

## Reproduction
1. Visit a search results URL
2. View the HTML source doee
3. Note that there is no meta robots tag present which includes a 'noindex' directive.

## Expectation
Search results pages should include a 'noindex' directive.

**Comment by zackkrida** [comment]
@jonoalderson Could you explain why would it be beneficial to `noindex` these search result pages? If anything, to my mind these pages would be one of the few things _to_ index:

- The search results on the page use our thumbnail cache, so the image urls on this page are not duplicated anywhere else on the web. 
- If we make the change in #805, these would be nice landing pages for popular stock image search terms "free cat photos" "CC licensed at photos" and so on.

As a disclaimer that I hope is obvious, I am _not_ an SEO expert so am genuinely seeking to learn here. Thank you!

**Comment by jonoalderson** [comment]
It's best practice not to allow 'infinite crawl spaces' (like search results) not to be indexed. There's no unique or valuable content here, other than the images themselves (which exist on their own URLs; as well as elsewhere).

**Comment by zackkrida** [comment]
Interesting. When I view a search like:

https://www.google.com/search?hl=en&q=dog%20stock%20photos

All of the top results seem to have no unique or valuable content other than generated paragraphs like:

> Choose from hundreds of free stock {term} photos as part of our collection. Be sure to bookmark this page as we will continue to add new pictures on a weekly and monthly basis. These HD {term} images are CC0 licensed, so they can be used and downloaded without attribution.

The line between _best_ and _most effective_ SEO practices always feels quite blurry to me 😅

**Comment by zackkrida** [comment]
Unsplash also heavily leverages pages like this for SEO purposes, as far as generating custom Open graph images for common search results:

https://unsplash.com/s/photos/dogs

<img width="1200" alt="CleanShot 2022-02-04 at 16 32 09@2x" src="https://user-images.githubusercontent.com/6351754/152606049-28dec8ee-69b0-48e8-ad74-94cf015727b5.png">

> [Fancy dynamic link](https://images.unsplash.com/opengraph/1x1.png?auto=format&fit=crop&w=1200&h=630&q=60&mark-w=64&mark-align=top%2Cleft&mark-pad=50&blend-w=1&mark=https%3A%2F%2Fimages.unsplash.com%2Fopengraph%2Flogo.png&blend=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1529472119196-cb724127a98e%3Fcrop%3Dfaces%252Cedges%26cs%3Dtinysrgb%26fit%3Dcrop%26fm%3Djpg%26ixid%3DMnwxMjA3fDB8MXxzZWFyY2h8MXx8ZG9nc3x8MHx8fHwxNjQzOTkyMDE2%26ixlib%3Drb-1.2.1%26q%3D60%26w%3D1200%26auto%3Dformat%26h%3D630%26mark-w%3D750%26mark-align%3Dmiddle%252Ccenter%26blend-mode%3Dnormal%26blend-alpha%3D10%26mark%3Dhttps%253A%252F%252Fimages.unsplash.com%252Fopengraph%252Fsearch-input.png%253Fauto%253Dformat%2526fit%253Dcrop%2526w%253D750%2526h%253D84%2526q%253D60%2526txt-color%253D000000%2526txt-size%253D40%2526txt-align%253Dmiddle%25252Cleft%2526txt-pad%253D80%2526txt-width%253D660%2526txt-clip%253Dellipsis%2526txt%253Ddogs%26blend%3D000000)

**Comment by jonoalderson** [comment]
Those sites have different brands, different strategies, and different technical setups than us. They also have SEO resource which dwarves ours by several orders of magnitude, and websites which aren't uncontrolled tyre fires of tends of millions of pages.

We can get clever with bending the rules tactically once we're in a position where we have a site architecture which isn't haemoraging equity (and a resourced content strategy on top of it) 😉

**Comment by zackkrida** [comment]
Sure, I don't know what the rules are well enough to know when they're being bent, so just sharing what I've seen in comparable products. We'll certainly start with `noindex`-ing all search result endpoints.

**Comment by jonoalderson** [comment]
https://wordpress.org/openverse/search/?q=cats isn't noindex'd; is this definitely done?

**Comment by sarayourfriend** [comment]
The WordPress.org theme would need separate work I guess to move the noindex directive into it.
