### ISSUE TITLE
Requests to invalid / non-existent resources should return a 404 HTTP status

### ISSUE THREAD

**Issue by jonoalderson** [WordPress/openverse-frontend#810]
## Description
Requests to arbitrary, non-existent URLs like https://wordpress.org/openverse/example-request-which-should-404 return a 200 HTTP status. They must instead return a `404` status.

Given that the 'existence' of a request is determined by the iframe'd website loaded after the response, the 200/404 logic switch will need to be based on evaluating the request URL to see if it matches known/valid patterns.

Correcting this is critical, as part of our ongoing SEO firefighting across the wp.org ecosystem.

## Reproduction
1. Request an invalid URL.
4. See that the response has a `200` status code.

## Expectation
Invalid requests should return a `404` status code.

**Comment by sarayourfriend** [comment]
This is also an iframe problem. I don't know how to solve this one.

**Comment by jonoalderson** [comment]
Yeah, given the setup, we'll need to 'predict' the status based on URL. That won't account for post-level existence, but will rule out completely invalid structures, at least.

**Comment by zackkrida** [comment]
Yeah, this is tough, and might need to wait until our post-iframe future. All I can think of is:

1. Sending an event from the iframe when there's a 404, and redirecting to a 404 page
2. Some double-request approach, where the WP Theme makes a low-cost HEAD request to the page and 404s based on the response

**Comment by jonoalderson** [comment]
Yeah, I don't think there's a good fix here :( 
Both of those are rather... unpleasant 😆

**Comment by zackkrida** [comment]
Fixed by launching to openverse.org
