### ISSUE TITLE
All pages should output a canonical URL tag

### ISSUE THREAD

**Issue by jonoalderson** [WordPress/openverse-frontend#812]
## Description
All pages* on the openverse site must output a canonical URL tag, which correctly references the 'definitive' URL for that page.
Currently, many pages omit this property. E.g., https://wordpress.org/openverse/meta-search, https://ja.wordpress.org/openverse/extension, https://wordpress.org/openverse/search-help

_*Where 'page' excludes error states and search-results._

Note that this is not a definitive list of URLs, and that logic should be applied globally to all page and template types, rather than URL-by-URL.

Correcting this is critical, as part of our ongoing SEO firefighting efforts across the wp.org ecosystem.

## Reproduction
1. Visit one of the example pages above.
2. View the HTML source code.
3. See that there is no canonical URL tag.

## Expectation
All pages* should output a (correct) canonical URL tag.

**Comment by jonoalderson** [comment]
Also note that URLs like https://wordpress.org/openverse/image/251f17bc-37a4-4cdd-b054-ceb0d52b445e/?referrer=creativecommons.org currently output an incorrect canonical URL value (of https://wordpress.org/openverse/), which is resulting in the tag being completely ignored.

**Comment by sarayourfriend** [comment]
This is another iframe problem that will be hard/tedius to solve.

Aside from all the usability issues with the iframe, it will force us to duplicate all SEO work in both the actual site and in the wporg theme container.

Still working on figuring out what the path forward is with the iframe. Waiting on feedback from the infrastructure side of things still on whether it's a possibility.

**Comment by zackkrida** [comment]
Fixed by launching to openverse.org. Canonical links are currently relative and will be made absolute in this PR: #2157
