### ISSUE TITLE
Add hreflang directives

### ISSUE THREAD

**Issue by jonoalderson** [WordPress/openverse-frontend#813]
## Description
Openverse pages on wordpress.org - e.g., https://de.wordpress.org/openverse/ - lack `hreflang` directives. Using these to correctly cross-reference our international variant/duplicate URLs is critical to our ongoing SEO firefighting on wp.org.

See https://developers.google.com/search/docs/advanced/crawling/localized-versions for context, and note that these are implemented 'correctly enough' across all(?) other WP subsites, templates and sections.

## Reproduction

1. View the HTML source of an openverse page.
2. See that there are no hreflang directives

## Expectation
All Openverse pages should include `hreflang` directives, which correctly describe all international variants/duplicates, as per other parts of wordpress.org.

**Comment by sarayourfriend** [comment]
@zackkrida I believe this should be fixed in the theme, no? Additionally in Openverse frontend itself I guess but especially in the theme?

**Comment by sarayourfriend** [comment]
@zackkrida I wonder if we can reprioritize this issue and potentially add it to a "post-iframe-removal" milestone?

The Nuxt app itself does already implement this, it's just a theme issue.

If we're not going to be able to do the iframe removal any time soon, then we should probably fix this in the theme, maybe just copy-pasting from the Nuxt app's output. It'll inevitably drift if the data changes but hopefully by then we've made some iframe removal progress.

**Comment by zackkrida** [comment]
Fixed by launching to openverse.org

**Comment by jonoalderson** [comment]
I'd suggest:
- Not outputting `hreflang` values for non-translated pages
- Using the absolute, rather than the relative URL.

**Comment by jonoalderson** [comment]
Tricky. Going to be tough to define procedurally; let's ignore! :)

**Comment by zackkrida** [comment]
Thanks. In any case, the absolute hreflang URLs will land shortly in this PR:
https://github.com/WordPress/openverse-frontend/pull/2157
