### ISSUE TITLE
Mobile browsers squish featured images

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#832]
## Description

The featured images on Firefox Android are squished horizontally

![Screenshot_20220208-134529](https://user-images.githubusercontent.com/24264157/153055336-295fd1cc-8a0c-4614-b0e4-0e67f632201f.png)

This also happens on Mobile Safari on iPad
<img width="834" alt="IMG_8F43334E82DD-1" src="https://user-images.githubusercontent.com/24264157/153056155-3a668ebc-765d-4465-9626-2a7aaed97b70.png">

## Reproduction

1. Visit wp.org/openverse on Firefox Android
2. See the squished featured images

## Expectation

The images should be round

## Environment

 - Device: TCL A507DL
 - OS: Android 10
 - Browser: Firefox for Android (from F-Droid)
 - Version: 
 - Other info: 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
I can't reproduce this any more. @zackkrida you have an Android phone, right? Can you test this and close if it's not reproducible?

**Comment by zackkrida** [comment]
Looks good in Firefox but looks absolutely _bonkers_ in "Samsung Internet Browser" (ignore their [awful] automatic dark mode), which i believe is Chromium based:

![signal-2022-02-22-121404_001](https://user-images.githubusercontent.com/6351754/155183530-87d17518-4ffe-47d2-b759-dc6f8d16b285.jpeg)

**Comment by sarayourfriend** [comment]
Okay that's the same thing I was seeing on my other android testing phone, so I guess it's still a problem.

**Comment by dhruvkb** [comment]
Can't reproduce on Safari on iOS 15.3.

**Comment by sarayourfriend** [comment]
I'm remembering now that I fixed this by updating my FF browser on Android. Wondering if it's just an older version of chrome in that Samsung browser?

**Comment by dhruvkb** [comment]
This works properly in real Chrome on Android too, so definitely something wrong with Samsung's browser specifically.

**Comment by sarayourfriend** [comment]
@zackkrida since you're the only person so far who can still reproduce this would you be willing to try to find a fix? I suspect it's probably something funky going on with the overflows and flex shrinking the items.

**Comment by zackkrida** [comment]
Yeah, definitely! I'm assuming it's an old browser version + flexbox bugs, this seems pretty consistent with old flexbox bugs back when the properties were vendor-prefixed.

**Comment by sarayourfriend** [comment]
I'm not sure anyone can reproduce this at the moment unless they're using an irresponsibly old browser version. Closing this. If it's an issue we can report it again and solve it then.
