### ISSUE TITLE
Only update POT file timestamp if translations have changed

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#842]
## Description

Currently anytime the `.pot` file is generated for translations, the file updates its `POT-Creation-Date` field. This means the `.pot` file is frequently dirty and included in changesets even if no translation strings have changed.

We should find a way to _only_ update the file if the translations have actually changed. Perhaps a way to do this would be to only write the file if `en.json` is dirty.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
Done in #981.
