### ISSUE TITLE
RTL homepage "Search" button covered by featured images at certain specific viewport widths

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#843]
## Description

Reported here https://github.com/WordPress/openverse-frontend/pull/788#pullrequestreview-877725191

## Reproduction

1. Visit the RTL homepage `/ar` for example.
2. Change the screen width until you can reproduce the search button being covered by a featured image as in the screenshot in the PR comment link above.

## Expectation

The featured images should be further off the side of the page to prevent this and match the LTR version.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
This is no longer reproducible.

**Comment by zackkrida** [comment]
I believe this can be safely closed; if anyone observes it again, please re-open!
