### ISSUE TITLE
[Feature] Improve visibility of meta search

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#85]
## Problem

Make meta search more visible, and therefore used more.

## Description

Meta search is currently very obscured when viewing a page with results. It is much more discoverable on the https://wordpress.org/openverse/search/audio and https://wordpress.org/openverse/search/video pages, than when doing an image search: https://wordpress.org/openverse/search/image?q=dogs

<img width="1258" alt="CleanShot 2021-06-29 at 15 16 46@2x" src="https://user-images.githubusercontent.com/6351754/123854928-4c118f00-d8ed-11eb-9cc0-67ba34687461.png">

In this scenario, the "No images found :(" text looks more like a button than meta search does!

## Implementation

- [x] 🙋 I would be interested in implementing this feature (with help and guidance from @panchovm)

**Comment by panchovm** [comment]
I like the idea. And thinking of all changes we need to apply, the audio integration release looks like a good opportunity to make a big change.

My only concern with keeping audio and video meta searches as tabs, is that user research showed a risk of missing the navigational component during a search. We don't have a clear reason for why it happened, but selecting the content type before searching seems a good opportunity to show this alternative feature when Openverse doesn't display any content.

**Comment by zackkrida** [comment]
Agreed. The tabs are a good 'secondary' navigation to switch media types but it will probably be most common to set the media type at the time of search (i.e, the homepage)

**Comment by zackkrida** [comment]
![CleanShot 2021-06-29 at 18 48 29@2x](https://user-images.githubusercontent.com/6351754/123877119-9d7c4700-d90a-11eb-9841-ea1cc7657a62.png)

Simple concept: what if we _always_ show meta search under the results? Obviously with different (good) styles haha

**Comment by panchovm** [comment]
I like the idea. Let me see how it works with the styles I'm currently working with.

My principal improvements are:
1. Adding contrast between Load more button and Source buttons. Sources should not compete with loading more.
2. Trying a single section without background color to link both messages into a single area.

In terms of features, I think the source site search should not have any filter selected on Openverse. This because filters will not work as expected on all sites in the same way. User expectations will differ from search results.

**Comment by panchovm** [comment]
I just noticed that I missed the content type connection of your idea. Did you want to show sources of the same content type or sources of another content type? e.g., if I am seeing images, get a list of audio sources.

**Comment by zackkrida** [comment]
Oh, that's just a lazy screenshot on my part. I want to show from the same media types, so meta sources for images under the image results

**Comment by panchovm** [comment]
I was thinking of something like this.

<img width="1070" alt="Meta search actions" src="https://user-images.githubusercontent.com/895819/124305036-891a9300-db32-11eb-9fed-178a3a7bc5db.png">

The transparent buttons do not compete with the load more results, and I reduced content within the description sentence. However, I'm not sure about the _our partner's site_ part.

**Comment by zackkrida** [comment]
I like the styles and i'll think about the language 🤔

**Comment by zackkrida** [comment]
Fixed via #86 

<img width="885" alt="CleanShot 2021-07-08 at 13 41 12@2x" src="https://user-images.githubusercontent.com/6351754/124967226-2cb3e980-dff2-11eb-91ee-2b7f5de6f70d.png">
