### ISSUE TITLE
Nuxt static assets don't seem to be served via Docker build

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#853]
To reproduce: Visit https://search-staging.openverse.engineering/openverse-default.jpg and observe that the frontend's default opengraph image is not visible. 

When visited locally after `pnpm build && pnpm start`, this file is visible:

![CleanShot 2022-02-10 at 16 40 57@2x](https://user-images.githubusercontent.com/6351754/153501555-07913488-635a-46ac-87d3-4a6da5be93aa.png)

The file isn't visible via `docker build -t openverse/frontend . \ && docker run --rm -p 8443:8443 openverse/frontend:latest`

**Comment by sarayourfriend** [comment]
I don't see the static assets getting copied into the `.nuxt` folder locally. Are they supposed to be there?

**Comment by zackkrida** [comment]
Fixed! ...by accidental commit to `main` https://github.com/WordPress/openverse-frontend/commit/051c4f7d026a5186e822ca4b03e4cb1a57274afe

I've updated our branch protections to include admins 😊 
<img width="444" alt="CleanShot 2022-02-10 at 19 36 06@2x" src="https://user-images.githubusercontent.com/6351754/153520426-43966ab5-f764-4723-9713-016ff1356f9b.png">

**Comment by sarayourfriend** [comment]
Can this be closed @zackkrida ?
