### ISSUE TITLE
Update attribution HTML generation to point to Openverse license/mark glyphs

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#857]
## Description

The attribution html currently still points to search.creativecommons.com. It should use the static assets from openverse, not cc search.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
Solved in production with the [latest release](https://github.com/WordPress/openverse-frontend/releases/tag/v3.1.1).
