### ISSUE TITLE
Global audio player not shown on results page for related audio

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#873]
## Description

The related audio on the audio result page needs the global audio player to show the waveform and more easily control playback.

Part of me thinks we should just show the global audio player on small width devices on the results and audio single result page and only hide it if the search type is changed to anything that doesn't include audio or a non-audio result is selected.

## Reproduction

1. Execute an audio search like `/search/audio/?q=birds` on a narrow enough viewport to show the global audio player
2. Navigate to a result
3. Scroll down to the related audio and play one.
4. Note the lack of global audio player.

## Expectation

We need some way to control playback and seeking on narrow screens in the related audio section.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
This issue has been fixed in production.
