### ISSUE TITLE
SSR Audio results page crashes

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#882]
## Description

The audio results page when loaded from SSR crashes every time: https://search-staging.openverse.engineering/search/audio?q=birds

## Reproduction

1.  Go to https://search-staging.openverse.engineering/search/audio?q=birds
2.  Open console and see errors. Note page is non-interactive.

## Expectation

It shouldn't crash.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Seeing a `t is undefined` error, likely a translation string that isn't working somewhere? Unless `t` is some other random minified function...

**Comment by sarayourfriend** [comment]
I don't think it is. It seems to do with the header buttons which is in the stack trace when you look at it in development build. Could be wrong there though!

**Comment by obulat** [comment]
It seems to have something to do with the server-client markup mismatch caused by using the `v-if` directive with a condition that is based on the screen width.
