### ISSUE TITLE
Audio results page renders mobile version first, even when the UA isn't a mobile browser

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#885]
## Description

When the UA is not a mobile browser, we shouldn't pre-render the search page as mobile. They look significantly different, even the header and the results as well. There's a ton of movement and recalculation after the page actually loads.

## Reproduction

1.  Go to search-staging.openverse.engineering/search/audio?q=galah on average size computer monitor and load it from SSR (reload the page once you're on it)
2.  Take note of the changing results layout and the changing header layout
3. 
4. See error.

## Expectation

We should be more proactive in trying to narrow the circumstances under which someone will see this kind of pop-in. I don't see this happening on other websites, I have to think it's because we're over-using programmatic rendering of elements based on screen width instead of using media queries to hide/show parts of the screen.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
I can see the header on the image results shifting too, I guess in audio is more noticeable because of the different audio player components but it does look is a general problem, not only Audio, right?

**Comment by sarayourfriend** [comment]
Yes. The best way to fix this would be to implement the UI State cookie milestone. It's a pretty small milestone that would fix a _lot_ of SSR vs CSR render bugs caused by page width assumptions across the API in a quick way.

Then we could follow up by moving as much as we can out of the JavaScript based `useMinScreen` composable and actual CSS modifiers.
