### ISSUE TITLE
Constrain Sketchfab Model height on single result view 

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#888]
## Description

Sketchfab models are really tall on the new single result view.

https://search-staging.openverse.engineering/image/00a6a7a4-6605-4cba-bacf-a08b0da546b9

![CleanShot 2022-02-16 at 14 55 41@2x](https://user-images.githubusercontent.com/6351754/154345705-d9634fff-dfc5-4b09-bf9a-b0b84f993303.png)

How could we constrain these so the entire model is visible at once?

CC @panchovm for design thought.

**Comment by panchovm** [comment]
Then a full width and height size view makes sense to me as long as we set a visible view to place the content. I still believe that `1000px` width and `500px` height is a worth exploring solution.
