### ISSUE TITLE
Split tests and static analysis into separate actions in the CI

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#890]
## Problem

Currently our "test" workflow is overloaded with static checks and unit tests and e2e tests. This makes them run one after the other meaning they take longer and also means that if an earlier one fails, you won't get any feedback about later checks.

## Description

Following Gutenberg's pattern, let's split the static analysis checks (linting, types) into a separate workflow entirely.

Additionally, create separate workflows for unit and e2e tests.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
This is an excellent idea!
