### ISSUE TITLE
Non-string UserAgent can crash the app

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#903]
## Description

https://sentry.io/share/issue/e01331b2eb71498080208da9d62de7f1/

If either `context.req.headers['user-agent']` or `navigator.userAgent` return a non-string value, the app crashes, because `useragent.parse` in `'express-useragent' expects a string argument and calls `replace` on it.
This is the error you would see: 
```
TypeError
Cannot read properties of undefined (reading 'replace')
```
Here is the code that causes the error:
https://github.com/WordPress/openverse-frontend/blob/5a3bed0dbab754e88749accc5a59477f7337583b/src/plugins/ua-parse.js#L3-L12

## Reproduction

1. Add `userAgent = null` or `userAgent = undefined` to line 11 in the code above.
2. Run the app and try to open http://localhost:8443
3. See error.

## Expectation

The app should not crash even if the user agent is undefined.
 
## Additional context

I wonder why the user agent can be non-string?

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
> I wonder why the user agent can be non-string?

My guess is some kind of privacy extension? :shrug:
