### ISSUE TITLE
Search from error page only show images

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-frontend#919]
## Description

Making a search from the input field of the 404 error page only show image results.

## Reproduction

1. Navigate to a page that throws 404 error, like https://search-staging.openverse.engineering/non-exist
2. Introduce a term to search for
3. See the wrong state of the results page, it shows the `VContentLink` for images when it's already showing only image results.

<img width="1048" alt="CleanShot 2022-02-21 at 11 21 25@2x" src="https://user-images.githubusercontent.com/9145885/154985118-a611466d-740d-44bb-b0de-b3514db38a8b.png">

## Expectation

The search should be for all content types.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
I can't reproduce this behavior anymore, although I'm not sure where exactly it was fixed. Closing.

**Comment by zackkrida** [comment]
I can't reproduce either! 👍
