### ISSUE TITLE
Insert the screen recording video on web extension page

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#92]
## Description
I made a screen recording video showing the web extension working on firefox. The whole process, from searching to pasting attribution info. We need to display it below the browser buttons.

## Question
I have two videos in different resolutions; both are 00:30 seconds in length, but one in `960 x 600` and one in `1440 x 900`. I used h.264 in both videos, but they are not as high quality as intended. Does it make sense to insert the `1440 x 900` version and scale it down to get a better resolution? The file is 15,2 mb.

**Comment by dhruvkb** [comment]
Referencing #96, which currently uses the 1440 x 900 video.
