### ISSUE TITLE
Add types to `utils/decode-media-data.js`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#923]
## Description

Add type checking to `decode-media-data.js`. This module has dependencies. One is already typed and the other was typed in https://github.com/WordPress/openverse-frontend/issues/922. Make sure to add it to `tsconfig.json`'s `include` list.

~~Blocked by https://github.com/WordPress/openverse-frontend/issues/922~~

## Additional context

Part of an ongoing effort to add type checking to parts of the project that can be type checked.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
Closing this issue because it was fixed in #1058.
