### ISSUE TITLE
Add types to `utils/case.js`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#930]
## Description

Add type checking to `case.js`. This module has one external dependency which already publishes types. Make sure to add it to `tsconfig.json`'s `include` list.

## Additional context

Part of an ongoing effort to add type checking to parts of the project that can be type checked.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
There seems to be no file named `utils/case.js`. Also going by the output of
```bash
$ git log --all --full-history -- "**/case.js"
```
there never was as any file by this name.

**Comment by sarayourfriend** [comment]
Hah, very weird! I have no idea what I must have been looking at when I created this issue, I swear I was just going file by file. Oh well! Closing this :+1:
