### ISSUE TITLE
Add types to `composables/use-storage.js`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#954]
## Description

Add type checking to `use-storage.js`. This module has one untyped dependency that will be typed in #952. Make sure to add it to `tsconfig.json`'s `include` list.

## Additional context

Part of an ongoing effort to add type checking to parts of the project that can be type checked.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
Fixed in #1184
