### ISSUE TITLE
Enable type checking for `composables/use-i18n.js`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#957]
## Description

Enable type checking for `use-i18n.js`. This module has zero dependencies and probably does not require any modifications to it to be type checked. Make sure to add it to `tsconfig.json`'s `include` list.

## Additional context

Part of an ongoing effort to add type checking to parts of the project that can be type checked.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
Fixed in #1182
