### ISSUE TITLE
Add types to `composables/use-window-scroll.js`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#964]
## Description

Add type checking to `use-window-scroll.js`. This module has one untyped dependency that will be typed in #952. Make sure to add it to `tsconfig.json`'s `include` list.

Blocked by #952 

## Additional context

Part of an ongoing effort to add type checking to parts of the project that can be type checked.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
This issue was solved in #1590.
