### ISSUE TITLE
Add types to `data/bug-report-service.js`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#968]
## Description

Add type checking to `bug-report-service.js`. This module has zero untyped dependencies. Make sure to add it to `tsconfig.json`'s `include` list.

## Additional context

Part of an ongoing effort to add type checking to parts of the project that can be type checked.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
Closing this issue because `bug-report-service` was removed in #1045.
