### ISSUE TITLE
Add new Privacy page explaining our use of cookies and linking to WordPress privacy policy

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#978]
## Problem

We want to add a page to describe our usage of cookies after adding the UI state cookie.

## Description

Add new Privacy page that explains our use of cookies and links to WP.org's Privacy policy. Replace the page menu privacy link to use the internal one.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
@panchovm, is there an updated design for the new Privacy page? Do we need to discuss the new page(-s)?

**Comment by zackkrida** [comment]
I suspect what we really need is some copy, and that the page _design_ could simply use the existing layout for text-based pages, like here: https://wordpress.org/openverse/search-help

**Comment by panchovm** [comment]
Exactly what @zackkrida said. We can revamp those long-reading pages once we finish most of the standalone tasks.

**Comment by zackkrida** [comment]
A first-pass at some copy:

```md
# Privacy

The Openverse project seeks to make the privacy and saftey of our users a priority. Openverse adheres to the [privacy policy of all WordPress.org websites](https://wordpress.org/about/privacy/). Please see that document for a full description of how Openverse uses and protects any information that you give us.

## Cookies 

Openverse uses cookies to store information about visitor's preferences and information about their web browsers. We use this information to improve the user experience of the site. These are considered "Necessary" or "Strictly necessary cookies" and you may disable these by changing your browser settings, but this may affect how Openverse functions.

## Contact Us

Any questions about Openverse and privacy can be sent to openverse@wordpress.org, shared as a [GitHub issue](https://github.com/WordPress/openverse/issues/new/choose), or discussed with our community in the #openverse channel of the [Making WordPress Chat](https://make.wordpress.org/chat/). 
```
