### ISSUE TITLE
Focused image result license icons are wrong colors

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#992]
## Description

License icon color on the search result pages is correct in development, but incorrect in the built application due to the CSS ordering issue.

- Pink here: https://search-staging.openverse.engineering/search/?q=mars
- White here: https://search-staging.openverse.engineering/search/image?q=mars

## Expectation

These license icons should be the default text color in both places.

## Screenshots

![CleanShot 2022-02-22 at 14 09 19@2x](https://user-images.githubusercontent.com/6351754/155201834-89ef0221-26d7-4486-bf6a-f80ee1bd6db4.png)

![CleanShot 2022-02-22 at 14 09 13@2x](https://user-images.githubusercontent.com/6351754/155201838-679a4f94-5439-4d09-addc-7a505b570bad.png)

**Comment by zackkrida** [comment]
@WordPress/openverse-frontend Could someone please assign themselves to this issue and take care of it before 2022-02-24 at 12PM EST? I'd like to get this fixes before we do a release of the frontend.

**Comment by sarayourfriend** [comment]
> License icon color on the search result pages is correct in development, but incorrect in the built application due to the CSS ordering issue.

Okay we just need to fix the CSS ordering issue, this whack-a-mole approach we've taken so far is not tenable.

I'll work on this ASAP using the template override method we discussed previously.

**Comment by krysal** [comment]
This disparity is quite unpredictable. Now I'm watching the player without styled play-pause button in [staging](https://search-staging.openverse.engineering/search/audio?q=honey) but locally is fine.

<img width="687" alt="CleanShot 2022-02-23 at 10 54 26@2x" src="https://user-images.githubusercontent.com/9145885/155345239-3e754ba3-0834-40e6-b998-87cf52fcd4e9.png">

**Comment by zackkrida** [comment]
@krysal what browser is that?

**Comment by krysal** [comment]
Chrome 98.0.4758.102 & Firefox 97.0b9

**Comment by obulat** [comment]
> I have a theory that a lot of the regressions we were seeing were just weird bundle ordering things we weren't aware were happening.
And we used quick-fixes to fix them, and now they are not working because everything work as it was supposed to in the beginning, and the fixes break things :)
The button from your screenshot, @krysal , has `bg-dark-charcoal  plain_-pb5e` classes overriding each other. Plain has a transparent background, that overrides the dark charcoal
