### ISSUE TITLE
Add peaks to the AudioDetail interface

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#996]
## Problem

`AudioDetail` interface doesn't have the `peaks` key which will be soon used for the waveforms, and is accessed in the `VWaveform` component implementations.

## Description

Add an optional `peaks` key to the `AudioDetail` interface:
https://github.com/WordPress/openverse-frontend/blob/e77826c836215554e2212548a1360e6ebc439782/src/store/types.d.ts#L82-L90

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by ChrisCoastal** [comment]
Hello, I was wondering if I could be assigned to work on this issue? Thanks!

**Comment by obulat** [comment]
Sure, @ChrisCoastal ! Please, go ahead :)

**Comment by ChrisCoastal** [comment]
Thanks so much. Is this just as straightforward as it seems? Adding a typed key to AudioDetail?
